/**
 * HOSTILE CASE TABLES for the two planning-graph boundaries on the
 * `scheduler-activation` axis: `ACTIVE_GRAPH_PROJECTION_LAYER` and
 * `GRAPH_BODY_RECORD_LAYER` (coverage task-c5be7926). Both readers entered the
 * tree in commit 9b9e44e; the active-graph one was repaired at d60a48f under
 * task-dd4ffa0c — attributed with `git log --follow`, not from the board.
 *
 * NOT a `*.security.ts` file and it holds NO assertions: the lane collects that
 * suffix, and the slice that imports these tables is where every verdict is
 * reached. This module only ARRANGES durable state and calls production.
 *
 * WHY THESE TWO SIT ON THIS AXIS. Both answer "which planning graph is in force
 * for admission" — the projection decides whether a project HAS a current graph,
 * and the body record decides whether that graph's bytes can be handed back. The
 * digest vocabulary the body record passes through (`GraphContentIssueCode`) is a
 * different subject and is rostered separately as `GRAPH_CONTENT_LAYERS` on the
 * integrity axis.
 *
 * EVERY REVISION HISTORY IS GENERATED BY THE REAL REDUCER. `reduceGraphRevision`
 * emits the events, and only those events are committed. Hand-written event
 * literals are banned here for the same reason the daemon's own suite bans them:
 * nothing writes graph-revision events in production yet, so an authored shape
 * would let both sides drift together while staying green. The command INPUT is
 * restated because `@moe/core`'s revision fixtures pin their own `GRAPH_HASH`,
 * and these fixtures need histories bound to a hash the CODEC actually produced.
 *
 * THE ONE PLANTED ROW, declared rather than hidden: the identity-mismatch arm
 * commits real codec bytes under a DIFFERENT content-hash aggregate. Production
 * is content-addressed, so `putGraphBody` cannot file bytes under a foreign key —
 * which is exactly why the read-side identity check would be unguarded by any
 * fixture that only ever went through the writer. The bytes are the codec's own;
 * only the key they are filed under is hostile.
 */

import { join } from "node:path";

import { reduceGraphRevision } from "../../packages/core/src/planning/graph-revision-reducer.js";
import type {
  GraphRevisionCommand,
  GraphRevisionEvent,
  GraphRevisionState,
} from "../../packages/core/src/planning/graph-revision-contract.js";
import { encodeGraphContent } from "../../packages/scheduler/src/graph-content.js";
import type {
  GraphContent,
  GraphEdge,
  GraphNode,
  GraphRevisionContent,
  GraphSnapshot,
} from "../../packages/scheduler/src/index.js";
import { SqliteEventStore } from "../../packages/store/src/index.js";

import {
  ACTIVE_GRAPH_PROJECTION_LAYER,
  graphRevisionAggregateId,
  readCurrentActiveGraph,
} from "../../apps/daemon/src/planning/active-graph-projection.js";
import {
  GRAPH_BODY_EVENT_TYPE,
  GRAPH_BODY_RECORD_CODES,
  GRAPH_BODY_RECORD_LAYER,
  graphBodyAggregateId,
  putGraphBody,
  readGraphBody,
} from "../../apps/daemon/src/planning/graph-body-record.js";
import { hostileRoot } from "./hostile-harness.js";
import type { HostileCase, HostileRaceCase } from "./scheduler-activation-hostile-cases.js";

const PROJECT_ID = "proj-hostile-planning-graph";
const ENCODER = new TextEncoder();

// --- durable roots -----------------------------------------------------------

const openStores: SqliteEventStore[] = [];

/** A real file-backed store on a fresh hostile root. Registered for cleanup. */
function openPlanningStore(label: string): { store: SqliteEventStore; path: string } {
  const path = join(hostileRoot(label), "store.sqlite");
  const store = SqliteEventStore.openForProject(path, PROJECT_ID);
  openStores.push(store);
  return { store, path };
}

/**
 * A SECOND connection to the same durable file. The race arms need two real
 * connections rather than two calls on one handle: a single handle can serialise
 * the interleaving away, and the property under test is about the DURABLE state,
 * not about one connection's internal ordering.
 */
function openSecondConnection(path: string): SqliteEventStore {
  const store = SqliteEventStore.openForProject(path, PROJECT_ID);
  openStores.push(store);
  return store;
}

/**
 * Close every store this module opened. Handles first, roots after: a held SQLite
 * handle kills the vitest worker, and in a `fileParallelism: false` lane that takes
 * every file scheduled after it with no output at all.
 */
export function closePlanningGraphStores(): number {
  let closed = 0;
  for (const store of openStores.splice(0)) {
    try {
      store.close();
      closed += 1;
    } catch {
      // A double close is not a verdict; the root is removed by the harness either way.
    }
  }
  return closed;
}

// --- content fixtures (the codec is the only producer of a hash) -------------

function baseSnapshot(): GraphSnapshot {
  const nodes: readonly GraphNode[] = [
    { nodeKey: "dev-a", executionBearing: true },
    { nodeKey: "dev-b", executionBearing: true },
    { nodeKey: "dev-c", executionBearing: true },
  ];
  const edges: readonly GraphEdge[] = [
    { edgeKey: "dev-e1", producerNodeKey: "dev-a", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e2", producerNodeKey: "dev-b", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e3", producerNodeKey: "dev-a", consumerNodeKey: "dev-b", kind: "ADVISORY" },
  ];
  return { nodes, edges, completionNodeKey: "dev-c" };
}

/** Real codec output. A fixture that failed to encode throws rather than degrading. */
function encoded(author: string): GraphContent {
  const content = {
    author,
    completionNode: "dev-c",
    decompositionBudget: 24,
    parentRevision: "rev-000000000000",
    policyRevision: "pol-000000000001",
    repositoryBaseTree: "4".repeat(40),
    snapshot: baseSnapshot(),
  } as unknown as GraphRevisionContent;
  const result = encodeGraphContent(content);
  if (!result.ok) {
    throw new Error(`planning-graph fixture failed to encode: ${JSON.stringify(result.issues)}`);
  }
  return result.value;
}

const PRIMARY = encoded("human:architect-primary");
const RIVAL = encoded("human:architect-rival");

/**
 * The identity arms are ABOUT two different hashes, so equal hashes would leave them
 * asserting nothing about identity. A refusal would still be produced (the bytes would
 * simply be found), so this is checked here rather than left to a confusing arm failure.
 */
if (RIVAL.graphContentHash === PRIMARY.graphContentHash) {
  throw new Error("planning-graph fixtures collapsed: two authors produced one content hash");
}

// --- reducer command input (input only; the reducer owns every rule) ---------

type Step = (current: GraphRevisionState | undefined) => GraphRevisionCommand;

function seededHash(seed: string): string {
  return seed.repeat(64).slice(0, 64);
}

const PLAN_HASH = seededHash("11");

/**
 * The approval binding is derived from the revision's OWN content hash: the
 * reducer refuses `REVISION_REBOUND` when an approval binds a hash the revision
 * was not created with, so a shared constant would leave the second revision
 * short of ACTIVE and the split-brain arms would be arranging nothing.
 */
function bindingOf(graphHash: string) {
  return {
    budgetHash: seededHash("55"),
    expectedGoalVersion: 3,
    graphHash,
    policyHash: seededHash("66"),
    qualityHash: seededHash("33"),
  } as const;
}

const SUBMISSION = { submissionRef: "submission-1", truthClass: "DAEMON_VERIFIED" } as const;

function versionOf(current: GraphRevisionState | undefined): number {
  return current === undefined ? 0 : current.version;
}

function createOf(revisionId: string, graphContentHash: string): Step {
  return () => ({
    commandId: `cmd-create-${revisionId}`,
    expectedVersion: 0,
    goalRef: "goal-1",
    graphContentHash,
    kind: "graph_revision.create",
    planHash: PLAN_HASH,
    revisionId,
  }) as GraphRevisionCommand;
}

const submit: Step = (current) => ({
  commandId: "cmd-submit",
  expectedVersion: versionOf(current),
  kind: "graph_revision.submit",
  witness: SUBMISSION,
}) as GraphRevisionCommand;

function approveAndActivateOf(graphHash: string, tag: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    activation: {
      ...binding,
      activationRef: `activation-${tag}`,
      graphEpoch: 1,
      truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: `approval-${tag}`, truthClass: "HUMAN_APPROVED" },
    commandId: `cmd-approve-${tag}`,
    expectedVersion: versionOf(current),
    kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

/** Drives the REAL reducer and returns the events it actually emitted. */
function drive(steps: readonly Step[]): {
  events: readonly GraphRevisionEvent[];
  state: GraphRevisionState;
} {
  let current: GraphRevisionState | undefined;
  const events: GraphRevisionEvent[] = [];
  for (const step of steps) {
    const command = step(current);
    const result = reduceGraphRevision(current, command);
    if (!result.ok) {
      throw new Error(`planning-graph fixture command ${command.kind} rejected`);
    }
    current = result.state;
    events.push(...result.events);
  }
  if (current === undefined) {
    throw new Error("planning-graph fixture path produced no state");
  }
  return { events, state: current };
}

function commitRevision(
  store: SqliteEventStore,
  revisionId: string,
  events: readonly GraphRevisionEvent[],
): void {
  const aggregateId = graphRevisionAggregateId(PROJECT_ID, revisionId);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(`seed-${revisionId}`),
    commandId: `seed-${revisionId}`,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: events.map((event, index) => ({
      eventId: `seed-${revisionId}-${index}`,
      eventType: event.kind,
      payload: ENCODER.encode(JSON.stringify(event)),
    })),
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** A revision driven all the way to ACTIVE and committed. The body is NOT written. */
function seedActiveRevision(
  store: SqliteEventStore,
  revisionId: string,
  content: GraphContent,
  tag: string,
): void {
  const driven = drive([
    createOf(revisionId, content.graphContentHash),
    submit,
    approveAndActivateOf(content.graphContentHash, tag),
  ]);
  commitRevision(store, revisionId, driven.events);
}

/** The whole lawful path: an ACTIVE revision AND the body its hash names. */
function seedActiveRevisionWithBody(
  store: SqliteEventStore,
  revisionId: string,
  content: GraphContent,
  tag: string,
): void {
  seedActiveRevision(store, revisionId, content, tag);
  const put = putGraphBody(store, PROJECT_ID, content);
  if (!put.ok) {
    throw new Error(`planning-graph fixture could not record a body: ${put.code}`);
  }
}

/**
 * THE LAWFUL ACTIVE PATH, exposed for the foundation-dispatch slice on this same axis.
 *
 * `deriveFoundationDispatchFacts` reads `readCurrentActiveGraph` FIRST, so none of its own
 * refusals is reachable without a graph THIS module's authority admits. Re-deriving a
 * revision history over there would police a copy of the reducer rather than the reducer,
 * and the two would drift the first time the lifecycle changed. Same content and same
 * driver as the accepted control below, so a fixture that stops reaching ACTIVE reddens in
 * both places at once.
 */
export function seedAcceptedActiveGraph(
  store: SqliteEventStore,
  revisionId: string,
  tag: string,
): void {
  seedActiveRevisionWithBody(store, revisionId, PRIMARY, tag);
}

// --- captured outcomes, for properties no {code, layer} case can carry -------

export interface PlanningGraphProof {
  readonly arm: string;
  readonly outcome: unknown;
}

const projectionProofs: PlanningGraphProof[] = [];

/**
 * Every `readCurrentActiveGraph` answer this module captured, RECORDED rather than
 * rebuilt. The refusal shape separates `layer` (who answered the caller) from
 * `sourceLayer` (who actually refused), and a `{code, layer}` case cannot see that
 * distinction — a wrapped body refusal and an originated one carry the same two
 * fields. The slice reads these to pin the separation itself.
 */
export function planningGraphProofs(): readonly PlanningGraphProof[] {
  return [...projectionProofs];
}

function captureProjection(arm: string, outcome: unknown): unknown {
  projectionProofs.push({ arm, outcome });
  return outcome;
}

/**
 * The ACCEPTED control. Every arm below is a refusal, and a projection that refuses
 * everything explains all of them equally well while holding no rule at all. The
 * control drives the SAME production reader over the whole lawful path.
 */
export async function runAcceptedActiveGraphControl(): Promise<unknown> {
  const { store } = openPlanningStore("active-graph-control");
  seedActiveRevisionWithBody(store, "graph-revision-1", PRIMARY, "control");
  return captureProjection("CONTROL", readCurrentActiveGraph(store, PROJECT_ID));
}

/** What the control must observe, restated by hand so a drifting fixture reddens. */
export const ACCEPTED_CONTROL_EXPECTATION = Object.freeze({
  graphContentHash: PRIMARY.graphContentHash,
  revisionId: "graph-revision-1",
  snapshotIdentity: PRIMARY.snapshotIdentity,
});

// --- the durable body: fixtures, proofs and its controls --------------------

const bodyProofs: PlanningGraphProof[] = [];

/**
 * Every `readGraphBody`/`putGraphBody` answer captured here. `GraphBodyRefusal.code` is a
 * UNION of this module's own vocabulary with the CODEC's (`GraphContentIssueCode`), so
 * "a code came back" does not say which family answered — and the two mean different
 * things: an own-family refusal is a custody failure, a codec-family one is a content
 * failure passed through with `sourceLayer` naming the codec. The slice pins the split.
 */
export function graphBodyProofs(): readonly PlanningGraphProof[] {
  return [...bodyProofs];
}

function captureBody(arm: string, outcome: unknown): unknown {
  bodyProofs.push({ arm, outcome });
  return outcome;
}

/** Production's own frozen list, re-exported so the slice pins the family by membership. */
export { GRAPH_BODY_RECORD_CODES };

/**
 * Commit a body row DIRECTLY, bypassing `putGraphBody`.
 *
 * Declared rather than hidden: production is content-addressed, so the writer cannot file
 * bytes under a key that is not their own hash. A misfiled or corrupt row is therefore
 * unreachable through the writer, and a read-side identity check no fixture can reach is
 * an UNGUARDED check. The bytes handed in are always the codec's own; only the key they
 * are filed under, or one drifted character inside them, is hostile.
 */
function plantBody(store: SqliteEventStore, key: string, bytes: Uint8Array): void {
  const aggregateId = graphBodyAggregateId(PROJECT_ID, key);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(`plant-${key}`),
    commandId: `plant-${key}`,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: [{ eventId: `plant-${key}`, eventType: GRAPH_BODY_EVENT_TYPE, payload: bytes }],
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** How many durable body rows exist under one content hash. Read back, never assumed. */
function bodyRowCount(store: SqliteEventStore, key: string): number {
  return store
    .readEvents(graphBodyAggregateId(PROJECT_ID, key))
    .filter((event) => event.eventType === GRAPH_BODY_EVENT_TYPE).length;
}

/**
 * Real content whose `bytes` are a plausible HAND-SERIALISATION rather than codec output.
 * Structurally perfect — hex64 hash, a Uint8Array, the true content — and refusable only
 * because the decoder cannot reproduce the declared hash from those bytes. This is the
 * mint-your-own-identity seam the codec exists to withhold.
 */
function forgedContent(source: GraphContent): GraphContent {
  return {
    ...source,
    bytes: ENCODER.encode(JSON.stringify(source.content)),
  } as unknown as GraphContent;
}

let forgedRowCount = -1;

/** The durable count read back AFTER the forged race, so a refusal that still wrote reddens. */
function forgedDurableAdmissions(): number {
  return forgedRowCount;
}

/**
 * The ACCEPTED control for the body record: bytes written through the real writer and read
 * back through the real reader. Without it, three refusals are equally explained by a
 * custodian that refuses everything.
 */
export async function runAcceptedGraphBodyControl(): Promise<unknown> {
  const { store } = openPlanningStore("graph-body-control");
  const put = putGraphBody(store, PROJECT_ID, PRIMARY);
  if (!put.ok) {
    throw new Error(`the graph-body control could not record a body: ${put.code}`);
  }
  return captureBody("CONTROL", readGraphBody(store, PROJECT_ID, PRIMARY.graphContentHash));
}

/**
 * The PASSTHROUGH positive control: one drifted character inside otherwise canonical bytes,
 * so the CODEC answers and the record passes its verdict through. Without it, "every body
 * refusal came from this module's own vocabulary" would be a property nothing could break —
 * the codec family would look unreachable rather than merely unused.
 */
export async function runGraphBodyPassthroughControl(): Promise<unknown> {
  const { store } = openPlanningStore("graph-body-passthrough");
  const text = new TextDecoder("utf-8", { fatal: true }).decode(PRIMARY.bytes);
  const tampered = ENCODER.encode(text.replace(PRIMARY.graphContentHash, "b".repeat(64)));
  plantBody(store, PRIMARY.graphContentHash, tampered);
  return captureBody("PASSTHROUGH", readGraphBody(store, PROJECT_ID, PRIMARY.graphContentHash));
}

/** What the body control must observe, restated by hand so a drifting fixture reddens. */
export const BODY_CONTROL_EXPECTATION = Object.freeze({
  graphContentHash: PRIMARY.graphContentHash,
  snapshotIdentity: PRIMARY.snapshotIdentity,
});

// --- the case tables ---------------------------------------------------------

export const PLANNING_GRAPH_CASES: readonly HostileCase[] = Object.freeze([
  {
    constant: "ACTIVE_GRAPH_PROJECTION_LAYER",
    arm: "BEFORE",
    // A real DRAFT history, not an empty store: an empty project and a project whose
    // revision never reached ACTIVE must both refuse, and only the second proves the
    // lifecycle filter is doing the refusing.
    name: "a revision that never reached ACTIVE yields no current graph before any activation",
    arranged: ACTIVE_GRAPH_PROJECTION_LAYER,
    expected: { code: "ACTIVE_GRAPH_ABSENT", layer: ACTIVE_GRAPH_PROJECTION_LAYER },
    run: async () => {
      const { store } = openPlanningStore("active-graph-before");
      const driven = drive([createOf("graph-revision-1", PRIMARY.graphContentHash)]);
      commitRevision(store, "graph-revision-1", driven.events);
      return captureProjection("BEFORE", readCurrentActiveGraph(store, PROJECT_ID));
    },
  },
  {
    constant: "ACTIVE_GRAPH_PROJECTION_LAYER",
    arm: "AFTER",
    // AFTER a real activation committed: the revision IS active, so the lifecycle filter
    // admits it and the refusal can only come from the body the hash names being missing.
    // The wrapping is the point — this arm is answered BY the projection about a refusal
    // the body record produced, which the slice pins field by field.
    name: "an ACTIVE revision whose body was never recorded refuses after the activation committed",
    arranged: ACTIVE_GRAPH_PROJECTION_LAYER,
    expected: { code: "ACTIVE_GRAPH_BODY_UNAVAILABLE", layer: ACTIVE_GRAPH_PROJECTION_LAYER },
    run: async () => {
      const { store } = openPlanningStore("active-graph-after");
      seedActiveRevision(store, "graph-revision-1", PRIMARY, "after");
      return captureProjection("AFTER", readCurrentActiveGraph(store, PROJECT_ID));
    },
  },
  {
    constant: "GRAPH_BODY_RECORD_LAYER",
    arm: "BEFORE",
    // BEFORE any body was recorded. Absence must not collapse into corruption: they are
    // different facts about custody, and one code for both would hide a lost row.
    name: "a body never recorded is absent, not corrupt, before any write lands",
    arranged: GRAPH_BODY_RECORD_LAYER,
    expected: { code: "GRAPH_BODY_ABSENT", layer: GRAPH_BODY_RECORD_LAYER },
    run: async () => {
      const { store } = openPlanningStore("graph-body-before");
      return captureBody("BEFORE", readGraphBody(store, PROJECT_ID, PRIMARY.graphContentHash));
    },
  },
  {
    constant: "GRAPH_BODY_RECORD_LAYER",
    arm: "AFTER",
    // AFTER a lawful body landed through the real writer: canonical codec bytes filed under
    // ANOTHER content's key still refuse. The decoder alone cannot catch this — those bytes
    // are perfectly self-consistent — so only the key-versus-digest check answers.
    name: "canonical bytes filed under a rival key are refused after a lawful body landed",
    arranged: GRAPH_BODY_RECORD_LAYER,
    expected: { code: "GRAPH_BODY_IDENTITY_MISMATCH", layer: GRAPH_BODY_RECORD_LAYER },
    run: async () => {
      const { store } = openPlanningStore("graph-body-after");
      const put = putGraphBody(store, PROJECT_ID, PRIMARY);
      if (!put.ok) {
        throw new Error(`the lawful write this arm builds on refused: ${put.code}`);
      }
      plantBody(store, RIVAL.graphContentHash, PRIMARY.bytes);
      return captureBody("AFTER", readGraphBody(store, PROJECT_ID, RIVAL.graphContentHash));
    },
  },
]);

export const PLANNING_GRAPH_RACES: readonly HostileRaceCase[] = Object.freeze([
  {
    constant: "ACTIVE_GRAPH_PROJECTION_LAYER",
    // Two ACTIVE revisions is the one condition a current-graph reader exists to detect,
    // and it is committed here from TWO connections to the same durable file. Neither
    // racing reader may resolve it: handing out authority during a split brain is the
    // defect, and "the later one wins" would be a resolution dressed as a read.
    name: "two readers over a split brain committed from two connections both refuse, neither resolves",
    arranged: ACTIVE_GRAPH_PROJECTION_LAYER,
    expected: { code: "ACTIVE_GRAPH_SPLIT_BRAIN", layer: ACTIVE_GRAPH_PROJECTION_LAYER },
    maxAdmitted: 0,
    run: async () => {
      const { store, path } = openPlanningStore("active-graph-race");
      seedActiveRevisionWithBody(store, "graph-revision-1", PRIMARY, "race-primary");
      const rival = openSecondConnection(path);
      seedActiveRevisionWithBody(rival, "graph-revision-2", RIVAL, "race-rival");
      return [
        captureProjection("RACE", readCurrentActiveGraph(store, PROJECT_ID)),
        captureProjection("RACE", readCurrentActiveGraph(rival, PROJECT_ID)),
      ] as const;
    },
  },
  {
    constant: "GRAPH_BODY_RECORD_LAYER",
    // Two connections racing to mint an identity the codec never produced. A returned
    // refusal is not evidence that nothing was written, which is why this race reads the
    // durable row count back: the defect worth catching is a custodian that answers "no"
    // to both callers while a forged body lands anyway.
    name: "two connections racing to write a hand-serialised body are both refused and no row lands",
    arranged: GRAPH_BODY_RECORD_LAYER,
    expected: { code: "GRAPH_BODY_NOT_ENCODED", layer: GRAPH_BODY_RECORD_LAYER },
    maxAdmitted: 0,
    durableAdmissions: forgedDurableAdmissions,
    run: async () => {
      const { store, path } = openPlanningStore("graph-body-race");
      const rival = openSecondConnection(path);
      const forged = forgedContent(PRIMARY);
      const outcomes = [
        captureBody("RACE", putGraphBody(store, PROJECT_ID, forged)),
        captureBody("RACE", putGraphBody(rival, PROJECT_ID, forged)),
      ] as const;
      forgedRowCount = bodyRowCount(store, PRIMARY.graphContentHash);
      return outcomes;
    },
  },
]);

export { ACTIVE_GRAPH_PROJECTION_LAYER, GRAPH_BODY_RECORD_LAYER, PROJECT_ID as PLANNING_GRAPH_PROJECT_ID };
