/**
 * HOSTILE CASE TABLES for the two planning-graph boundaries on the
 * `scheduler-activation` axis: `ACTIVE_GRAPH_PROJECTION_LAYER` and
 * `GRAPH_BODY_RECORD_LAYER` (coverage task-c5be7926). Both readers entered the
 * tree in commit 9b9e44e; the active-graph one was repaired at d60a48f under
 * task-dd4ffa0c — attributed with `git log --follow`, not from the board.
 *
 * NOT a `*.security.ts` file and it holds NO assertions: the lane collects that
 * suffix, and the slice that imports these tables is where every verdict is
 * reached. This module only ARRANGES durable state and calls production.
 *
 * WHY THESE TWO SIT ON THIS AXIS. Both answer "which planning graph is in force
 * for admission" — the projection decides whether a project HAS a current graph,
 * and the body record decides whether that graph's bytes can be handed back. The
 * digest vocabulary the body record passes through (`GraphContentIssueCode`) is a
 * different subject and is rostered separately as `GRAPH_CONTENT_LAYERS` on the
 * integrity axis.
 *
 * EVERY REVISION HISTORY IS GENERATED BY THE REAL REDUCER. `reduceGraphRevision`
 * emits the events, and only those events are committed. Hand-written event
 * literals are banned here for the same reason the daemon's own suite bans them:
 * nothing writes graph-revision events in production yet, so an authored shape
 * would let both sides drift together while staying green. The command INPUT is
 * restated because `@moe/core`'s revision fixtures pin their own `GRAPH_HASH`,
 * and these fixtures need histories bound to a hash the CODEC actually produced.
 *
 * THE ONE PLANTED ROW, declared rather than hidden: the identity-mismatch arm
 * commits real codec bytes under a DIFFERENT content-hash aggregate. Production
 * is content-addressed, so `putGraphBody` cannot file bytes under a foreign key —
 * which is exactly why the read-side identity check would be unguarded by any
 * fixture that only ever went through the writer. The bytes are the codec's own;
 * only the key they are filed under is hostile.
 */

import { join } from "node:path";

import {
  createAcceptanceContract,
} from "../../packages/core/src/planning/acceptance-contract-codec.js";
import { createPlanRevision } from "../../packages/core/src/planning/plan-revision-codec.js";
import { reduceGraphRevision } from "../../packages/core/src/planning/graph-revision-reducer.js";
import type {
  GraphRevisionCommand,
  GraphRevisionEvent,
  GraphRevisionState,
} from "../../packages/core/src/planning/graph-revision-contract.js";
import {
  ADMISSION_PURPOSES,
  createNodeDefinition,
  deriveNodeAuthoritySet,
  encodeGraphContent,
  snapshotIdentityHash,
  validateGraphSnapshot,
} from "../../packages/scheduler/src/index.js";
import type {
  GraphContent,
  GraphEdge,
  GraphNode,
  GraphRevisionContent,
  GraphSnapshot,
  NodeAuthoritySection,
  NodeDefinition,
} from "../../packages/scheduler/src/index.js";
import { SqliteEventStore } from "../../packages/store/src/index.js";

import { ACTIVATION_WORLD_NODE_KEY } from "../../apps/daemon/src/activation/activation-world-fixtures.js";
import { readDurableLedger } from "../../apps/daemon/src/bootstrap/bootstrap-ledger.js";
import {
  GOAL_ID as ACTIVATION_GOAL_ID,
  RUN_ID as ACTIVATION_RUN_ID,
} from "../../apps/daemon/src/bootstrap/bootstrap-test-fixtures.js";
import {
  ACTIVE_GRAPH_PROJECTION_LAYER,
  graphRevisionAggregateId,
  readCurrentActiveGraph,
} from "../../apps/daemon/src/planning/active-graph-projection.js";
import {
  GRAPH_BODY_EVENT_TYPE,
  GRAPH_BODY_RECORD_CODES,
  GRAPH_BODY_RECORD_LAYER,
  graphBodyAggregateId,
  putGraphBody,
  readGraphBody,
} from "../../apps/daemon/src/planning/graph-body-record.js";
import {
  EXPANSION_ADMISSION_CODE_LAYERS,
  EXPANSION_ADMISSION_SERVER_OWNED_KEYS,
  decodeExpansionAdmissionEnvelope,
  decodeExpansionAdmissionPayload,
} from "../../apps/daemon/src/planning/expansion-admission-contracts.js";
import { readExpansionAdmissionBindings } from "../../apps/daemon/src/planning/expansion-admission-bindings.js";
import {
  EXPANSION_APPROVAL_EVENT_TYPE,
  commitExpansionApproval,
  expansionApprovalAggregateId,
} from "../../apps/daemon/src/planning/expansion-admission-records.js";
import {
  EXPANSION_REQUEST_CODE_LAYERS,
  EXPANSION_REQUEST_SERVER_OWNED_KEYS,
  decodeExpansionRequestEnvelope,
  decodeExpansionRequestPayload,
} from "../../apps/daemon/src/planning/expansion-request-contracts.js";
import { commitExpansionRequest } from "../../apps/daemon/src/planning/expansion-request-commit.js";
import { readExpansionRequestAuthority } from "../../apps/daemon/src/planning/expansion-request-current-authority.js";
import {
  EXPANSION_HOLD_EVENT_TYPE,
  expansionHoldAggregateId,
} from "../../apps/daemon/src/planning/expansion-request-records.js";
import {
  holdCommandOf,
  holdStateOf,
  runRecordOf,
} from "../../apps/daemon/src/planning/expansion-request-test-fixtures.js";
import { hostileRoot } from "./hostile-harness.js";
import type { HostileCase, HostileRaceCase } from "./scheduler-activation-hostile-cases.js";

const PROJECT_ID = "proj-hostile-planning-graph";
const ENCODER = new TextEncoder();

// --- durable roots -----------------------------------------------------------

const openStores: SqliteEventStore[] = [];

/** A real file-backed store on a fresh hostile root. Registered for cleanup. */
function openPlanningStore(
  label: string, projectId: string = PROJECT_ID,
): { store: SqliteEventStore; path: string } {
  const path = join(hostileRoot(label), "store.sqlite");
  const store = SqliteEventStore.openForProject(path, projectId);
  openStores.push(store);
  return { store, path };
}

/**
 * A SECOND connection to the same durable file. The race arms need two real
 * connections rather than two calls on one handle: a single handle can serialise
 * the interleaving away, and the property under test is about the DURABLE state,
 * not about one connection's internal ordering.
 */
function openSecondConnection(path: string, projectId: string = PROJECT_ID): SqliteEventStore {
  const store = SqliteEventStore.openForProject(path, projectId);
  openStores.push(store);
  return store;
}

/**
 * Close every store this module opened. Handles first, roots after: a held SQLite
 * handle kills the vitest worker, and in a `fileParallelism: false` lane that takes
 * every file scheduled after it with no output at all.
 */
export function closePlanningGraphStores(): number {
  let closed = 0;
  for (const store of openStores.splice(0)) {
    try {
      store.close();
      closed += 1;
    } catch {
      // A double close is not a verdict; the root is removed by the harness either way.
    }
  }
  return closed;
}

// --- content fixtures (the codec is the only producer of a hash) -------------

function baseSnapshot(): GraphSnapshot {
  const nodes: readonly GraphNode[] = [
    { nodeKey: "dev-a", executionBearing: true },
    { nodeKey: "dev-b", executionBearing: true },
    { nodeKey: "dev-c", executionBearing: true },
  ];
  const edges: readonly GraphEdge[] = [
    { edgeKey: "dev-e1", producerNodeKey: "dev-a", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e2", producerNodeKey: "dev-b", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e3", producerNodeKey: "dev-a", consumerNodeKey: "dev-b", kind: "ADVISORY" },
  ];
  return { nodes, edges, completionNodeKey: "dev-c" };
}


/**
 * V3 NODE AUTHORITY (task-8c7e6ce4). `GraphRevisionContent` v3 makes `nodeAuthority`
 * MANDATORY and `bindAuthority` RE-DERIVES the stated set rather than adopting it, so the
 * seven-field body this file used to seal can no longer encode. Everything below COMPOSES
 * the published producers - `createPlanRevision` / `createAcceptanceContract` then
 * `createNodeDefinition` and `deriveNodeAuthoritySet` - and judges nothing: each helper
 * hands back what production returned, or throws carrying production's own `code@layer`,
 * so a fixture that stopped building can never read as a boundary that stopped refusing.
 */
const authorityHex = (digit: string): string => digit.repeat(64);

const planDraftFor = (nodeKeys: readonly string[]): Record<string, unknown> => ({
  affectedCriterionIds: ["criterion-planning"],
  affectedNodeIds: [...nodeKeys],
  approvalState: "APPROVED",
  authorRef: "principal-planning",
  graphBinding: {
    graphContentHash: authorityHex("a"), graphRevisionRef: "graph-revision-planning",
  },
  parentRevisionId: null,
  rejectionRef: null,
  revisionId: "plan-revision-planning",
  steps: [{ description: "Land the node.", kind: "IMPLEMENTATION", stepId: "step-planning" }],
  verificationRecipeRefs: ["recipe-planning"],
});

const acceptanceDraftFor = (nodeKeys: readonly string[]): Record<string, unknown> => ({
  applicability: {
    graphContentHash: authorityHex("a"), graphRevisionRef: "graph-revision-planning",
    nodeIds: [...nodeKeys], nodeKind: "LEAF",
  },
  authorRef: "principal-planning",
  contractId: "acceptance-planning",
  obligations: [{
    criterionId: "criterion-planning",
    evidenceRequirements: [{
      evidenceRef: "artifact-planning", kind: "ARTIFACT", requirementId: "requirement-planning",
    }],
    statement: "The node ships its focused verification.",
    verificationRecipeRefs: ["recipe-planning"],
  }],
});

/** A MONOTONIC contract owes a matching registry proof, else the node codec refuses
 *  NODE_AUTHORITY_MONOTONIC_PROOF_MISSING @ NODE_AUTHORITY_PROOFS. */
const AUTHORITY_REGISTRY_ENTRY: Record<string, unknown> = {
  parameterSchema: { digest: authorityHex("b"), kind: "JSON_SCHEMA" },
  predicateRef: "predicate-planning",
  proofRationale: "An artifact seal cannot become unsealed.",
  schemaId: "schema-planning",
  schemaVersion: 1,
  sourceOperationClass: "ARTIFACT_SEAL",
};

/** ONE contract per HARD edge ENTERING a node. `graphBindingDigest` is PRODUCTION's
 *  `snapshotIdentityHash` over the ACCEPTED graph, never a literal: a digest this structure
 *  did not produce refuses NODE_AUTHORITY_RECURSION_BINDING_MISMATCH at derive time. */
const hardEdgeRequirement = (edge: GraphEdge, binding: string): Record<string, unknown> => ({
  edgeKey: edge.edgeKey,
  requirement: {
    contract: {
      alternateProducers: [] as string[],
      alternativeRuling: { kind: "NOT_APPLICABLE", reason: "No alternate producer exists." },
      consumer: {
        contractHash: authorityHex("c"), criterionRef: "criterion-planning",
        kind: "PRECONDITION",
      },
      consumerNodeKey: edge.consumerNodeKey,
      consumptionHorizon: "RESULT_SEAL",
      edgeKind: "ARTIFACT_CONSUMPTION",
      graphBindingDigest: binding,
      invalidationFacts: [{
        sourceFactDigest: authorityHex("e"), sourceFactRef: "fact-planning",
        sourceFactVersion: 1,
      }],
      minimumQualifyingMilestone: "RESULT_SEALED",
      necessity: {
        failedConsumerCriterionRef: "criterion-planning", failureKind: "MISSING_ARTIFACT",
        truthClass: "OBSERVED",
      },
      producer: {
        artifactOrInterfaceRef: "artifact-planning", digest: authorityHex("f"),
        kind: "ARTIFACT_CONSUMPTION",
      },
      producerNodeKey: edge.producerNodeKey,
      recheckPredicateRef: "predicate-planning",
      satisfactionPredicate: {
        parametersDigest: authorityHex("1"), predicateRef: "predicate-planning",
        schemaId: "schema-planning", schemaVersion: 1,
      },
      satisfactionWitnesses: [{
        sourceOperationClass: "ARTIFACT_SEAL", witnessDigest: authorityHex("2"),
        witnessRef: "witness-planning", witnessVersion: 1,
      }],
      stability: "MONOTONIC",
      truthClass: "OBSERVED",
    },
    edgeKind: "ARTIFACT_CONSUMPTION",
  },
});

/** Admitted by PRODUCTION or not built at all. */
function nodeDefinitionFor(
  nodeKey: string, snapshot: GraphSnapshot, binding: string,
): NodeDefinition {
  const nodeKeys = snapshot.nodes.map((node) => node.nodeKey);
  const plan = createPlanRevision(planDraftFor(nodeKeys));
  if (!plan.ok) throw new Error(`plan revision fixture refused: ${plan.code}`);
  const acceptance = createAcceptanceContract(acceptanceDraftFor(nodeKeys));
  if (!acceptance.ok) throw new Error(`acceptance fixture refused: ${acceptance.code}`);
  const completes = nodeKey === snapshot.completionNodeKey;
  const built = createNodeDefinition({
    acceptanceContract: acceptance.contract,
    draft: {
      admissionAmounts: [...ADMISSION_PURPOSES].sort().map((purpose, index) => ({
        meter: "runner.authorized_ms", purpose, quantity: index + 1,
      })),
      admissionGatePolicy: "POLICY_ALLOWANCE",
      capability: "capability-implement",
      completionLinkage: completes ? nodeKey : null,
      constraints: ["constraint-planning"],
      directHardDependencies: snapshot.edges
        .filter((edge) => edge.kind === "HARD" && edge.consumerNodeKey === nodeKey)
        .map((edge) => hardEdgeRequirement(edge, binding)),
      joinRole: completes ? "COMPLETION" : "NONE",
      nodeKey,
      objective: `Land ${nodeKey}.`,
      policySliceHash: authorityHex("3"),
      readScopes: ["services/api/src"],
      repositoryBaseTree: authorityHex("4"),
      resources: ["resource-planning"],
      verificationRecipeRevisions: ["recipe-planning"],
      writeScopes: ["services/api/src/node"],
    },
    planRevision: plan.revision,
    predicateRegistry: [AUTHORITY_REGISTRY_ENTRY],
  });
  if (!built.ok) {
    throw new Error(built.issues.map((issue) => `${issue.code}@${issue.layer}`).join(","));
  }
  return built.value.definition;
}

/** `definitions` is sorted by `nodeKey` because `readAuthoritySection` requires the two
 *  arrays index-aligned and STRICTLY ASCENDING, and `deriveNodeAuthoritySet` already returns
 *  its entries in that order. `authorities` is the PRODUCER'S own value. */
function authoritySectionFor(snapshot: GraphSnapshot): NodeAuthoritySection {
  const validated = validateGraphSnapshot(snapshot);
  if (!validated.ok) {
    throw new Error(`graph fixture refused: ${validated.issues[0]?.code ?? "?"}`);
  }
  const binding = snapshotIdentityHash(validated.graph);
  const definitions = snapshot.nodes
    .map((node) => node.nodeKey)
    .slice()
    .sort()
    .map((nodeKey) => nodeDefinitionFor(nodeKey, snapshot, binding));
  const derived = deriveNodeAuthoritySet(snapshot, definitions);
  if (!derived.ok) {
    throw new Error(derived.issues.map((issue) => `${issue.code}@${issue.layer}`).join(","));
  }
  return { authorities: derived.value, definitions };
}

/** Real codec output. A fixture that failed to encode throws rather than degrading. */
function encoded(author: string): GraphContent {
  const snapshot = baseSnapshot();
  const content: GraphRevisionContent = {
    author,
    completionNode: "dev-c",
    decompositionBudget: 24,
    nodeAuthority: authoritySectionFor(snapshot),
    parentRevision: "rev-000000000000",
    policyRevision: "pol-000000000001",
    repositoryBaseTree: "4".repeat(40),
    snapshot,
  };
  const result = encodeGraphContent(content);
  if (!result.ok) {
    throw new Error(`planning-graph fixture failed to encode: ${JSON.stringify(result.issues)}`);
  }
  return result.value;
}

const PRIMARY = encoded("human:architect-primary");
const RIVAL = encoded("human:architect-rival");

/**
 * The identity arms are ABOUT two different hashes, so equal hashes would leave them
 * asserting nothing about identity. A refusal would still be produced (the bytes would
 * simply be found), so this is checked here rather than left to a confusing arm failure.
 */
if (RIVAL.graphContentHash === PRIMARY.graphContentHash) {
  throw new Error("planning-graph fixtures collapsed: two authors produced one content hash");
}

// --- reducer command input (input only; the reducer owns every rule) ---------

type Step = (current: GraphRevisionState | undefined) => GraphRevisionCommand;

function seededHash(seed: string): string {
  return seed.repeat(64).slice(0, 64);
}

const PLAN_HASH = seededHash("11");

/**
 * The approval binding is derived from the revision's OWN content hash: the
 * reducer refuses `REVISION_REBOUND` when an approval binds a hash the revision
 * was not created with, so a shared constant would leave the second revision
 * short of ACTIVE and the split-brain arms would be arranging nothing.
 */
function bindingOf(graphHash: string) {
  return {
    budgetHash: seededHash("55"),
    expectedGoalVersion: 3,
    graphHash,
    policyHash: seededHash("66"),
    qualityHash: seededHash("33"),
  } as const;
}

const SUBMISSION = { submissionRef: "submission-1", truthClass: "DAEMON_VERIFIED" } as const;

function versionOf(current: GraphRevisionState | undefined): number {
  return current === undefined ? 0 : current.version;
}

function createOf(revisionId: string, graphContentHash: string): Step {
  return () => ({
    commandId: `cmd-create-${revisionId}`,
    expectedVersion: 0,
    goalRef: "goal-1",
    graphContentHash,
    kind: "graph_revision.create",
    planHash: PLAN_HASH,
    revisionId,
  }) as GraphRevisionCommand;
}

const submit: Step = (current) => ({
  commandId: "cmd-submit",
  expectedVersion: versionOf(current),
  kind: "graph_revision.submit",
  witness: SUBMISSION,
}) as GraphRevisionCommand;

function approveAndActivateOf(graphHash: string, tag: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    activation: {
      ...binding,
      activationRef: `activation-${tag}`,
      graphEpoch: 1,
      truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: `approval-${tag}`, truthClass: "HUMAN_APPROVED" },
    commandId: `cmd-approve-${tag}`,
    expectedVersion: versionOf(current),
    kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

/** Drives the REAL reducer and returns the events it actually emitted. */
function drive(steps: readonly Step[]): {
  events: readonly GraphRevisionEvent[];
  state: GraphRevisionState;
} {
  let current: GraphRevisionState | undefined;
  const events: GraphRevisionEvent[] = [];
  for (const step of steps) {
    const command = step(current);
    const result = reduceGraphRevision(current, command);
    if (!result.ok) {
      throw new Error(`planning-graph fixture command ${command.kind} rejected`);
    }
    current = result.state;
    events.push(...result.events);
  }
  if (current === undefined) {
    throw new Error("planning-graph fixture path produced no state");
  }
  return { events, state: current };
}

function commitRevision(
  store: SqliteEventStore,
  revisionId: string,
  events: readonly GraphRevisionEvent[],
): void {
  const aggregateId = graphRevisionAggregateId(PROJECT_ID, revisionId);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(`seed-${revisionId}`),
    commandId: `seed-${revisionId}`,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: events.map((event, index) => ({
      eventId: `seed-${revisionId}-${index}`,
      eventType: event.kind,
      payload: ENCODER.encode(JSON.stringify(event)),
    })),
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** A revision driven all the way to ACTIVE and committed. The body is NOT written. */
function seedActiveRevision(
  store: SqliteEventStore,
  revisionId: string,
  content: GraphContent,
  tag: string,
): void {
  const driven = drive([
    createOf(revisionId, content.graphContentHash),
    submit,
    approveAndActivateOf(content.graphContentHash, tag),
  ]);
  commitRevision(store, revisionId, driven.events);
}

/** The whole lawful path: an ACTIVE revision AND the body its hash names. */
function seedActiveRevisionWithBody(
  store: SqliteEventStore,
  revisionId: string,
  content: GraphContent,
  tag: string,
): void {
  seedActiveRevision(store, revisionId, content, tag);
  const put = putGraphBody(store, PROJECT_ID, content);
  if (!put.ok) {
    throw new Error(`planning-graph fixture could not record a body: ${put.code}`);
  }
}

/**
 * THE LAWFUL ACTIVE PATH, exposed for the foundation-dispatch slice on this same axis.
 *
 * `deriveFoundationDispatchFacts` reads `readCurrentActiveGraph` FIRST, so none of its own
 * refusals is reachable without a graph THIS module's authority admits. Re-deriving a
 * revision history over there would police a copy of the reducer rather than the reducer,
 * and the two would drift the first time the lifecycle changed. Same content and same
 * driver as the accepted control below, so a fixture that stops reaching ACTIVE reddens in
 * both places at once.
 */
export function seedAcceptedActiveGraph(
  store: SqliteEventStore,
  revisionId: string,
  tag: string,
): void {
  seedActiveRevisionWithBody(store, revisionId, PRIMARY, tag);
}

// --- captured outcomes, for properties no {code, layer} case can carry -------

export interface PlanningGraphProof {
  readonly arm: string;
  readonly outcome: unknown;
}

const projectionProofs: PlanningGraphProof[] = [];

/**
 * Every `readCurrentActiveGraph` answer this module captured, RECORDED rather than
 * rebuilt. The refusal shape separates `layer` (who answered the caller) from
 * `sourceLayer` (who actually refused), and a `{code, layer}` case cannot see that
 * distinction — a wrapped body refusal and an originated one carry the same two
 * fields. The slice reads these to pin the separation itself.
 */
export function planningGraphProofs(): readonly PlanningGraphProof[] {
  return [...projectionProofs];
}

function captureProjection(arm: string, outcome: unknown): unknown {
  projectionProofs.push({ arm, outcome });
  return outcome;
}

/**
 * The ACCEPTED control. Every arm below is a refusal, and a projection that refuses
 * everything explains all of them equally well while holding no rule at all. The
 * control drives the SAME production reader over the whole lawful path.
 */
export async function runAcceptedActiveGraphControl(): Promise<unknown> {
  const { store } = openPlanningStore("active-graph-control");
  seedActiveRevisionWithBody(store, "graph-revision-1", PRIMARY, "control");
  return captureProjection("CONTROL", readCurrentActiveGraph(store, PROJECT_ID));
}

/** What the control must observe, restated by hand so a drifting fixture reddens. */
export const ACCEPTED_CONTROL_EXPECTATION = Object.freeze({
  graphContentHash: PRIMARY.graphContentHash,
  revisionId: "graph-revision-1",
  snapshotIdentity: PRIMARY.snapshotIdentity,
});

// --- the durable body: fixtures, proofs and its controls --------------------

const bodyProofs: PlanningGraphProof[] = [];

/**
 * Every `readGraphBody`/`putGraphBody` answer captured here. `GraphBodyRefusal.code` is a
 * UNION of this module's own vocabulary with the CODEC's (`GraphContentIssueCode`), so
 * "a code came back" does not say which family answered — and the two mean different
 * things: an own-family refusal is a custody failure, a codec-family one is a content
 * failure passed through with `sourceLayer` naming the codec. The slice pins the split.
 */
export function graphBodyProofs(): readonly PlanningGraphProof[] {
  return [...bodyProofs];
}

function captureBody(arm: string, outcome: unknown): unknown {
  bodyProofs.push({ arm, outcome });
  return outcome;
}

/** Production's own frozen list, re-exported so the slice pins the family by membership. */
export { GRAPH_BODY_RECORD_CODES };

/**
 * Commit a body row DIRECTLY, bypassing `putGraphBody`.
 *
 * Declared rather than hidden: production is content-addressed, so the writer cannot file
 * bytes under a key that is not their own hash. A misfiled or corrupt row is therefore
 * unreachable through the writer, and a read-side identity check no fixture can reach is
 * an UNGUARDED check. The bytes handed in are always the codec's own; only the key they
 * are filed under, or one drifted character inside them, is hostile.
 */
function plantBody(store: SqliteEventStore, key: string, bytes: Uint8Array): void {
  const aggregateId = graphBodyAggregateId(PROJECT_ID, key);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(`plant-${key}`),
    commandId: `plant-${key}`,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: [{ eventId: `plant-${key}`, eventType: GRAPH_BODY_EVENT_TYPE, payload: bytes }],
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** How many durable body rows exist under one content hash. Read back, never assumed. */
function bodyRowCount(store: SqliteEventStore, key: string): number {
  return store
    .readEvents(graphBodyAggregateId(PROJECT_ID, key))
    .filter((event) => event.eventType === GRAPH_BODY_EVENT_TYPE).length;
}

/**
 * Real content whose `bytes` are a plausible HAND-SERIALISATION rather than codec output.
 * Structurally perfect — hex64 hash, a Uint8Array, the true content — and refusable only
 * because the decoder cannot reproduce the declared hash from those bytes. This is the
 * mint-your-own-identity seam the codec exists to withhold.
 */
function forgedContent(source: GraphContent): GraphContent {
  return {
    ...source,
    bytes: ENCODER.encode(JSON.stringify(source.content)),
  } as unknown as GraphContent;
}

let forgedRowCount = -1;

/** The durable count read back AFTER the forged race, so a refusal that still wrote reddens. */
function forgedDurableAdmissions(): number {
  return forgedRowCount;
}

/**
 * The ACCEPTED control for the body record: bytes written through the real writer and read
 * back through the real reader. Without it, three refusals are equally explained by a
 * custodian that refuses everything.
 */
export async function runAcceptedGraphBodyControl(): Promise<unknown> {
  const { store } = openPlanningStore("graph-body-control");
  const put = putGraphBody(store, PROJECT_ID, PRIMARY);
  if (!put.ok) {
    throw new Error(`the graph-body control could not record a body: ${put.code}`);
  }
  return captureBody("CONTROL", readGraphBody(store, PROJECT_ID, PRIMARY.graphContentHash));
}

/**
 * The PASSTHROUGH positive control: one drifted character inside otherwise canonical bytes,
 * so the CODEC answers and the record passes its verdict through. Without it, "every body
 * refusal came from this module's own vocabulary" would be a property nothing could break —
 * the codec family would look unreachable rather than merely unused.
 */
export async function runGraphBodyPassthroughControl(): Promise<unknown> {
  const { store } = openPlanningStore("graph-body-passthrough");
  const text = new TextDecoder("utf-8", { fatal: true }).decode(PRIMARY.bytes);
  const tampered = ENCODER.encode(text.replace(PRIMARY.graphContentHash, "b".repeat(64)));
  plantBody(store, PRIMARY.graphContentHash, tampered);
  return captureBody("PASSTHROUGH", readGraphBody(store, PROJECT_ID, PRIMARY.graphContentHash));
}

/** What the body control must observe, restated by hand so a drifting fixture reddens. */
export const BODY_CONTROL_EXPECTATION = Object.freeze({
  graphContentHash: PRIMARY.graphContentHash,
  snapshotIdentity: PRIMARY.snapshotIdentity,
});

/**
 * LAWFUL bodies for the expansion decoders, restated here rather than imported from a
 * production fixture: these arms are about what the decoders REFUSE, and a shared fixture that
 * drifted would make the hostile variant differ in a second way without anyone noticing.
 */
function lawfulRequestPayload(): Record<string, unknown> {
  return {
    goalRef: "goal-1", parentNodeRef: "node-1", parentRunRef: "run-1", rationale: "expand it",
  };
}

function lawfulRequestEnvelope(): Record<string, unknown> {
  return {
    commandId: "cmd-1", correlationId: "corr-1", decidedAt: "2026-08-27T00:00:00.000Z",
    payload: lawfulRequestPayload(), principalId: "principal-1", projectId: "project-1",
  };
}

function lawfulAdmissionPayload(): Record<string, unknown> {
  return {
    approval: null, approvalCommand: null, criteria: null, goalRef: "goal-1",
    opportunity: null, parentNodeRef: "node-1", parentRunRef: "run-1", policy: null,
    proposal: null, supersession: null,
  };
}

function lawfulAdmissionEnvelope(): Record<string, unknown> {
  return {
    commandId: "cmd-1", correlationId: "corr-1", decidedAt: "2026-08-27T00:00:00.000Z",
    payload: lawfulAdmissionPayload(), principalId: "principal-1", projectId: "project-1",
  };
}

function expansionRequestCommitInput(commandId: string, requestTag: string) {
  const hold = holdStateOf(holdCommandOf({ commandId, holdId: "hold-code-map" }));
  return {
    envelope: {
      commandId, correlationId: `corr-${commandId}`, decidedAt: "2026-08-27T00:00:00.000Z",
      payload: {}, principalId: "principal-code-map", projectId: PROJECT_ID,
    },
    goalRef: "goal-code-map",
    goalVersion: 4,
    hold,
    holdAggregateId: expansionHoldAggregateId(PROJECT_ID, hold.holdId),
    requestBytes: ENCODER.encode(requestTag),
    run: runRecordOf(hold, "goal-code-map", 4),
  };
}

function seedRequestGoalFence(store: SqliteEventStore): void {
  const aggregateId = "goal-code-map";
  for (let version = 0; version < 4; version += 1) {
    const bytes = ENCODER.encode(`goal-fence-${version}`);
    store.commit({
      aggregateId,
      commandBytes: bytes,
      commandId: `goal-fence-${version}`,
      committedAt: "2026-08-27T00:00:00.000Z",
      events: [{ eventId: `goal-fence-${version}`, eventType: "GoalFenceSeeded", payload: bytes }],
      expectedVersion: version,
    });
  }
}

function expansionRequestEventCount(store: SqliteEventStore): number {
  const aggregateId = expansionHoldAggregateId(PROJECT_ID, "hold-code-map");
  return store.readEvents(aggregateId)
    .filter((event) => event.eventType === EXPANSION_HOLD_EVENT_TYPE).length;
}

function activationAdmissionPayload() {
  const decoded = decodeExpansionAdmissionPayload({
    approval: null, approvalCommand: null, criteria: null, goalRef: ACTIVATION_GOAL_ID,
    opportunity: null, parentNodeRef: ACTIVATION_WORLD_NODE_KEY,
    parentRunRef: ACTIVATION_RUN_ID, policy: null, proposal: null, supersession: null,
  });
  if (!decoded.ok) throw new Error(`activation admission payload refused: ${decoded.code}`);
  return decoded.payload;
}

function expansionApprovalInput(commandId: string, requestTag: string) {
  return {
    commandId,
    correlationId: `corr-${commandId}`,
    decidedAt: "2026-08-27T00:00:00.000Z",
    holdId: "hold-code-map",
    principalId: "principal-code-map",
    projectId: PROJECT_ID,
    record: {
      approvalIdentity: "approval-code-map",
      preparationIdentity: "preparation-code-map",
      proposalIdentity: "proposal-code-map",
    },
    requestBytes: ENCODER.encode(requestTag),
  };
}

function expansionApprovalEventCount(store: SqliteEventStore): number {
  const aggregateId = expansionApprovalAggregateId(PROJECT_ID, "hold-code-map");
  return store.readEvents(aggregateId)
    .filter((event) => event.eventType === EXPANSION_APPROVAL_EVENT_TYPE).length;
}

let requestRaceDurableDelta = -1;
let admissionRaceDurableDelta = -1;

// --- the case tables ---------------------------------------------------------

export const PLANNING_GRAPH_CASES: readonly HostileCase[] = Object.freeze([
  {
    constant: "ACTIVE_GRAPH_PROJECTION_LAYER",
    arm: "BEFORE",
    // A real DRAFT history, not an empty store: an empty project and a project whose
    // revision never reached ACTIVE must both refuse, and only the second proves the
    // lifecycle filter is doing the refusing.
    name: "a revision that never reached ACTIVE yields no current graph before any activation",
    arranged: ACTIVE_GRAPH_PROJECTION_LAYER,
    expected: { code: "ACTIVE_GRAPH_ABSENT", layer: ACTIVE_GRAPH_PROJECTION_LAYER },
    run: async () => {
      const { store } = openPlanningStore("active-graph-before");
      const driven = drive([createOf("graph-revision-1", PRIMARY.graphContentHash)]);
      commitRevision(store, "graph-revision-1", driven.events);
      return captureProjection("BEFORE", readCurrentActiveGraph(store, PROJECT_ID));
    },
  },
  {
    constant: "ACTIVE_GRAPH_PROJECTION_LAYER",
    arm: "AFTER",
    // AFTER a real activation committed: the revision IS active, so the lifecycle filter
    // admits it and the refusal can only come from the body the hash names being missing.
    // The wrapping is the point — this arm is answered BY the projection about a refusal
    // the body record produced, which the slice pins field by field.
    name: "an ACTIVE revision whose body was never recorded refuses after the activation committed",
    arranged: ACTIVE_GRAPH_PROJECTION_LAYER,
    expected: { code: "ACTIVE_GRAPH_BODY_UNAVAILABLE", layer: ACTIVE_GRAPH_PROJECTION_LAYER },
    run: async () => {
      const { store } = openPlanningStore("active-graph-after");
      seedActiveRevision(store, "graph-revision-1", PRIMARY, "after");
      return captureProjection("AFTER", readCurrentActiveGraph(store, PROJECT_ID));
    },
  },
  {
    constant: "GRAPH_BODY_RECORD_LAYER",
    arm: "BEFORE",
    // BEFORE any body was recorded. Absence must not collapse into corruption: they are
    // different facts about custody, and one code for both would hide a lost row.
    name: "a body never recorded is absent, not corrupt, before any write lands",
    arranged: GRAPH_BODY_RECORD_LAYER,
    expected: { code: "GRAPH_BODY_ABSENT", layer: GRAPH_BODY_RECORD_LAYER },
    run: async () => {
      const { store } = openPlanningStore("graph-body-before");
      return captureBody("BEFORE", readGraphBody(store, PROJECT_ID, PRIMARY.graphContentHash));
    },
  },
  {
    constant: "GRAPH_BODY_RECORD_LAYER",
    arm: "AFTER",
    // AFTER a lawful body landed through the real writer: canonical codec bytes filed under
    // ANOTHER content's key still refuse. The decoder alone cannot catch this — those bytes
    // are perfectly self-consistent — so only the key-versus-digest check answers.
    name: "canonical bytes filed under a rival key are refused after a lawful body landed",
    arranged: GRAPH_BODY_RECORD_LAYER,
    expected: { code: "GRAPH_BODY_IDENTITY_MISMATCH", layer: GRAPH_BODY_RECORD_LAYER },
    run: async () => {
      const { store } = openPlanningStore("graph-body-after");
      const put = putGraphBody(store, PROJECT_ID, PRIMARY);
      if (!put.ok) {
        throw new Error(`the lawful write this arm builds on refused: ${put.code}`);
      }
      plantBody(store, RIVAL.graphContentHash, PRIMARY.bytes);
      return captureBody("AFTER", readGraphBody(store, PROJECT_ID, RIVAL.graphContentHash));
    },
  },
  // --- expansion request and admission decoders (roster rows task-d1145412) -------------
  // Both contracts mint their own layer for every code, so each `expected.layer` below is
  // READ OFF the production map rather than typed as a literal.
  {
    constant: "EXPANSION_REQUEST_LAYERS",
    arm: "BEFORE",
    // BEFORE any payload is looked at: the SERVER envelope carries one member the caller must
    // never present. `exactExpansionRecord` (expansion-request-contracts.ts:177) refuses on
    // ARITY, and it is the only mechanism that can — every text bound below it passes, and no
    // payload decode runs at all.
    name: "an envelope carrying one server-owned key is refused before any payload is decoded",
    arranged: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_ENVELOPE_MALFORMED,
    expected: {
      code: "EXPANSION_REQUEST_ENVELOPE_MALFORMED",
      layer: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_ENVELOPE_MALFORMED,
    },
    run: async () => decodeExpansionRequestEnvelope({
      ...lawfulRequestEnvelope(),
      [EXPANSION_REQUEST_SERVER_OWNED_KEYS[7]]: "graph.request_expansion",
    }),
  },
  {
    constant: "EXPANSION_REQUEST_LAYERS",
    arm: "AFTER",
    // AFTER the same payload decoded lawfully: only `rationale` changes, and only by a NUL.
    // The arity fence still passes (four keys, all present), so `boundedExpansionText`
    // (:171) is the sole refusing mechanism — the divergence rail 7A asks for.
    name: "a NUL smuggled into rationale is refused after the same payload decoded lawfully",
    arranged: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_PAYLOAD_MALFORMED,
    expected: {
      code: "EXPANSION_REQUEST_PAYLOAD_MALFORMED",
      layer: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_PAYLOAD_MALFORMED,
    },
    run: async () => {
      const lawful = decodeExpansionRequestPayload(lawfulRequestPayload());
      if (!lawful.ok) {
        throw new Error(`the lawful decode this arm builds on refused: ${lawful.code}`);
      }
      return decodeExpansionRequestPayload({
        ...lawfulRequestPayload(), rationale: `expand${String.fromCharCode(0)}now`,
      });
    },
  },
  {
    constant: "EXPANSION_ADMISSION_LAYERS",
    arm: "BEFORE",
    // BEFORE anything durable is read: a blank principal id. The exact-key fence passes (six
    // keys), so `text` (expansion-admission-contracts.ts:205) is the only mechanism left.
    name: "a blank principal id is refused before the admission reads any durable state",
    arranged: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_ENVELOPE_MALFORMED,
    expected: {
      code: "EXPANSION_ADMISSION_ENVELOPE_MALFORMED",
      layer: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_ENVELOPE_MALFORMED,
    },
    run: async () => decodeExpansionAdmissionEnvelope({
      ...lawfulAdmissionEnvelope(), principalId: "",
    }),
  },
  {
    constant: "EXPANSION_ADMISSION_LAYERS",
    arm: "AFTER",
    // AFTER the same payload decoded lawfully: one server-owned member added. Every text bound
    // still passes, so `exactly` (:193) is the sole refuser.
    name: "a server-owned key added to a lawful payload is refused after that payload decoded",
    arranged: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_PAYLOAD_MALFORMED,
    expected: {
      code: "EXPANSION_ADMISSION_PAYLOAD_MALFORMED",
      layer: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_PAYLOAD_MALFORMED,
    },
    run: async () => {
      const lawful = decodeExpansionAdmissionPayload(lawfulAdmissionPayload());
      if (!lawful.ok) {
        throw new Error(`the lawful decode this arm builds on refused: ${lawful.code}`);
      }
      return decodeExpansionAdmissionPayload({
        ...lawfulAdmissionPayload(),
        [EXPANSION_ADMISSION_SERVER_OWNED_KEYS[8]]: "hold-1",
      });
    },
  },
  {
    constant: "EXPANSION_REQUEST_CODE_LAYERS",
    arm: "BEFORE",
    // The empty durable ledger is the only refuser: no decoder is called, and the authority
    // reader mints CURRENT_AUTHORITY. `arranged` is deliberately independent of the map so a
    // mutant collapsing this code to REQUEST goes red at the slice's series check.
    name: "an absent durable goal is refused by current authority before any request is committed",
    arranged: "CURRENT_AUTHORITY",
    expected: {
      code: "EXPANSION_REQUEST_GOAL_ABSENT",
      layer: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_GOAL_ABSENT,
    },
    run: async () => {
      const { store } = openPlanningStore("expansion-request-map-before");
      return readExpansionRequestAuthority({
        ledger: readDurableLedger(store, PROJECT_ID),
        payload: { goalRef: "goal-never-opened", parentNodeRef: "node-1", parentRunRef: "run-1" },
        projectId: PROJECT_ID,
        store,
      });
    },
  },
  {
    constant: "EXPANSION_REQUEST_CODE_LAYERS",
    arm: "AFTER",
    // AFTER one lawful two-leg commit, only the durable idempotency fence can answer the same
    // command identity with different bytes. Its DURABLE_STORE face proves this is not a decoder
    // refusal that merely happens to share a request-family code.
    name: "different bytes under a committed request identity refuse at the ledger after the write",
    arranged: "LEDGER",
    expected: {
      code: "EXPANSION_REQUEST_LEDGER_IDEMPOTENCY_CONFLICT",
      layer: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_LEDGER_IDEMPOTENCY_CONFLICT,
    },
    run: async () => {
      const { store } = openPlanningStore("expansion-request-map-after");
      seedRequestGoalFence(store);
      const lawful = commitExpansionRequest(store, expansionRequestCommitInput("cmd-map-after", "lawful"));
      if (!lawful.ok) throw new Error(`lawful request commit refused: ${lawful.code}`);
      const refusal = commitExpansionRequest(
        store, expansionRequestCommitInput("cmd-map-after", "different"),
      );
      if (refusal.ok || refusal.sourceLayer !== "DURABLE_STORE") {
        throw new Error("request conflict did not preserve its DURABLE_STORE source layer");
      }
      return refusal;
    },
  },
  {
    constant: "EXPANSION_ADMISSION_CODE_LAYERS",
    arm: "BEFORE",
    // The plan's proposed HOLD_UNAVAILABLE arm cannot diverge by layer: production stamps both
    // that wrapper and its delegated absent-hold face LEDGER. This constructible sibling keeps
    // the wrapper proof: AUTHORITY is minted here while CURRENT_AUTHORITY travels upstream.
    name: "an absent durable goal is wrapped as admission authority unavailable before any hold",
    arranged: "AUTHORITY",
    expected: {
      code: "EXPANSION_ADMISSION_AUTHORITY_UNAVAILABLE",
      layer: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_AUTHORITY_UNAVAILABLE,
    },
    run: async () => {
      const { store } = openPlanningStore("expansion-admission-map-before");
      const refusal = readExpansionAdmissionBindings(
        store, PROJECT_ID, activationAdmissionPayload(),
      );
      if (refusal.ok || refusal.upstream?.layer !== "CURRENT_AUTHORITY") {
        throw new Error("admission authority refusal did not preserve CURRENT_AUTHORITY upstream");
      }
      return refusal;
    },
  },
  {
    constant: "EXPANSION_ADMISSION_CODE_LAYERS",
    arm: "AFTER",
    // AFTER one lawful approval record, the same hold is protected only by expectedVersion: 0.
    // The top-level RECORD layer is independent of the delegated DURABLE_STORE source.
    name: "a second approval for one hold refuses at the record boundary after the first landed",
    arranged: "RECORD",
    expected: {
      code: "EXPANSION_ADMISSION_RECORD_CONFLICT",
      layer: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_RECORD_CONFLICT,
    },
    run: async () => {
      const { store } = openPlanningStore("expansion-admission-map-after");
      const lawful = commitExpansionApproval(
        store, expansionApprovalInput("cmd-approval-first", "first"),
      );
      if (!lawful.ok) throw new Error(`lawful approval commit refused: ${lawful.code}`);
      const refusal = commitExpansionApproval(
        store, expansionApprovalInput("cmd-approval-second", "second"),
      );
      if (refusal.ok || refusal.upstream?.layer !== "DURABLE_STORE") {
        throw new Error("approval conflict did not preserve its DURABLE_STORE upstream layer");
      }
      return refusal;
    },
  },
]);

export const PLANNING_GRAPH_RACES: readonly HostileRaceCase[] = Object.freeze([
  {
    constant: "ACTIVE_GRAPH_PROJECTION_LAYER",
    // Two ACTIVE revisions is the one condition a current-graph reader exists to detect,
    // and it is committed here from TWO connections to the same durable file. Neither
    // racing reader may resolve it: handing out authority during a split brain is the
    // defect, and "the later one wins" would be a resolution dressed as a read.
    name: "two readers over a split brain committed from two connections both refuse, neither resolves",
    arranged: ACTIVE_GRAPH_PROJECTION_LAYER,
    expected: { code: "ACTIVE_GRAPH_SPLIT_BRAIN", layer: ACTIVE_GRAPH_PROJECTION_LAYER },
    maxAdmitted: 0,
    run: async () => {
      const { store, path } = openPlanningStore("active-graph-race");
      seedActiveRevisionWithBody(store, "graph-revision-1", PRIMARY, "race-primary");
      const rival = openSecondConnection(path);
      seedActiveRevisionWithBody(rival, "graph-revision-2", RIVAL, "race-rival");
      return [
        captureProjection("RACE", readCurrentActiveGraph(store, PROJECT_ID)),
        captureProjection("RACE", readCurrentActiveGraph(rival, PROJECT_ID)),
      ] as const;
    },
  },
  {
    constant: "GRAPH_BODY_RECORD_LAYER",
    // Two connections racing to mint an identity the codec never produced. A returned
    // refusal is not evidence that nothing was written, which is why this race reads the
    // durable row count back: the defect worth catching is a custodian that answers "no"
    // to both callers while a forged body lands anyway.
    name: "two connections racing to write a hand-serialised body are both refused and no row lands",
    arranged: GRAPH_BODY_RECORD_LAYER,
    expected: { code: "GRAPH_BODY_NOT_ENCODED", layer: GRAPH_BODY_RECORD_LAYER },
    maxAdmitted: 0,
    durableAdmissions: forgedDurableAdmissions,
    run: async () => {
      const { store, path } = openPlanningStore("graph-body-race");
      const rival = openSecondConnection(path);
      const forged = forgedContent(PRIMARY);
      const outcomes = [
        captureBody("RACE", putGraphBody(store, PROJECT_ID, forged)),
        captureBody("RACE", putGraphBody(rival, PROJECT_ID, forged)),
      ] as const;
      forgedRowCount = bodyRowCount(store, PRIMARY.graphContentHash);
      return outcomes;
    },
  },
  {
    constant: "EXPANSION_REQUEST_LAYERS",
    // A record with a null prototype is ADMITTED by `exactExpansionRecord` — only the
    // accessor-defined member refuses it, and both concurrent decoders must say so. A getter
    // that ran would prove the descriptor check never happened.
    name: "two concurrent decodes of an accessor-backed payload both refuse and neither reads it",
    arranged: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_PAYLOAD_MALFORMED,
    expected: {
      code: "EXPANSION_REQUEST_PAYLOAD_MALFORMED",
      layer: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_PAYLOAD_MALFORMED,
    },
    maxAdmitted: 0,
    run: async () => {
      const hostile = Object.create(null) as Record<string, unknown>;
      Object.defineProperties(hostile, {
        goalRef: { enumerable: true, value: "goal-1" },
        parentNodeRef: { enumerable: true, value: "node-1" },
        parentRunRef: { enumerable: true, value: "run-1" },
        rationale: { enumerable: true, get: () => "expand" },
      });
      return [
        decodeExpansionRequestPayload(hostile),
        decodeExpansionRequestPayload(hostile),
      ] as const;
    },
  },
  {
    constant: "EXPANSION_ADMISSION_LAYERS",
    // An ARRAY is the shape a caller reaches for when a record is expected; `exactly` refuses
    // it before any member is read, and neither concurrent decoder may admit it.
    name: "two concurrent decodes of an array payload both refuse, neither admits a member",
    arranged: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_PAYLOAD_MALFORMED,
    expected: {
      code: "EXPANSION_ADMISSION_PAYLOAD_MALFORMED",
      layer: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_PAYLOAD_MALFORMED,
    },
    maxAdmitted: 0,
    run: async () => {
      const hostile = [lawfulAdmissionPayload()];
      return [
        decodeExpansionAdmissionPayload(hostile),
        decodeExpansionAdmissionPayload(hostile),
      ] as const;
    },
  },
  {
    constant: "EXPANSION_REQUEST_CODE_LAYERS",
    // One lawful row exists first. Both real connections then replay its command identity with
    // different bytes, so only the durable idempotency fence can refuse; the delta readback
    // proves neither refusal hid an extra hold event.
    name: "two connections conflicting with one committed request both refuse and append nothing",
    arranged: "LEDGER",
    expected: {
      code: "EXPANSION_REQUEST_LEDGER_IDEMPOTENCY_CONFLICT",
      layer: EXPANSION_REQUEST_CODE_LAYERS.EXPANSION_REQUEST_LEDGER_IDEMPOTENCY_CONFLICT,
    },
    maxAdmitted: 0,
    durableAdmissions: () => requestRaceDurableDelta,
    run: async () => {
      const { store, path } = openPlanningStore("expansion-request-map-race");
      seedRequestGoalFence(store);
      const lawful = commitExpansionRequest(store, expansionRequestCommitInput("cmd-map-race", "lawful"));
      if (!lawful.ok) throw new Error(`lawful request race seed refused: ${lawful.code}`);
      const before = expansionRequestEventCount(store);
      const rival = openSecondConnection(path);
      const outcomes = [
        commitExpansionRequest(store, expansionRequestCommitInput("cmd-map-race", "different")),
        commitExpansionRequest(rival, expansionRequestCommitInput("cmd-map-race", "different")),
      ] as const;
      for (const outcome of outcomes) {
        if (outcome.ok || outcome.sourceLayer !== "DURABLE_STORE") {
          throw new Error("request race lost its DURABLE_STORE refusal source");
        }
      }
      requestRaceDurableDelta = expansionRequestEventCount(store) - before;
      return outcomes;
    },
  },
  {
    constant: "EXPANSION_ADMISSION_CODE_LAYERS",
    // One approval is durable first. Both connections target its already-versioned aggregate;
    // the RECORD wrapper must preserve DURABLE_STORE upstream and the durable delta must be zero.
    name: "two connections racing a second approval both refuse and record no extra binding",
    arranged: "RECORD",
    expected: {
      code: "EXPANSION_ADMISSION_RECORD_CONFLICT",
      layer: EXPANSION_ADMISSION_CODE_LAYERS.EXPANSION_ADMISSION_RECORD_CONFLICT,
    },
    maxAdmitted: 0,
    durableAdmissions: () => admissionRaceDurableDelta,
    run: async () => {
      const { store, path } = openPlanningStore("expansion-admission-map-race");
      const lawful = commitExpansionApproval(
        store, expansionApprovalInput("cmd-approval-race-first", "first"),
      );
      if (!lawful.ok) throw new Error(`lawful approval race seed refused: ${lawful.code}`);
      const before = expansionApprovalEventCount(store);
      const rival = openSecondConnection(path);
      const outcomes = [
        commitExpansionApproval(rival, expansionApprovalInput("cmd-approval-race-second", "second")),
        commitExpansionApproval(store, expansionApprovalInput("cmd-approval-race-second", "second")),
      ] as const;
      for (const outcome of outcomes) {
        if (outcome.ok || outcome.upstream?.layer !== "DURABLE_STORE") {
          throw new Error("approval race lost its DURABLE_STORE upstream refusal");
        }
      }
      admissionRaceDurableDelta = expansionApprovalEventCount(store) - before;
      return outcomes;
    },
  },
]);

export { ACTIVE_GRAPH_PROJECTION_LAYER, GRAPH_BODY_RECORD_LAYER, PROJECT_ID as PLANNING_GRAPH_PROJECT_ID };
