import type { ScheduleDefinition } from "./schedule-model.js";
import {
  ALL_LANDED_EDGES,
  EDGE,
  FAULT,
  RACE,
  REVISION_RACE,
  RUN_RACE,
  defineSchedule,
} from "./schedule-universe-tables.js";

/**
 * Canonical CORE schedule universe, invariant half (design 20.1 #CORE-I1..#CORE-I22).
 *
 * All four aggregates with landed reducers (GOAL, GRAPH_REVISION, PLANNING_RUN, PROJECT)
 * are checked against the derived edge and race-pair universe. Nothing is referenced
 * abstractly: an aggregate that has landed must be asserted, never assumed.
 */

const two = "TWO_EVENT" as const;
const multi = "MULTI_EVENT" as const;

export const CORE_INVARIANT_SCHEDULES: readonly ScheduleDefinition[] = Object.freeze([
  defineSchedule("CORE-I1-PAIR", ["CORE-I1"], two,
    [EDGE.gActivate, EDGE.gCancelDraft], [RACE.dActivateCancel], [FAULT.lock]),
  defineSchedule("CORE-I1-PARTIAL-ORDER", ["CORE-I1"], multi,
    [EDGE.gActivate, EDGE.gCancelDraft, EDGE.gPauseDraft], [RACE.dCancelPause],
    [FAULT.lock, FAULT.commit]),
  defineSchedule("CORE-I1-PLANNING-CLAIM", ["CORE-I1"], two,
    [EDGE.runClaim, EDGE.runResume], RUN_RACE.readyClaim, [FAULT.lock]),
  defineSchedule("CORE-I2-PAIR", ["CORE-I2"], two,
    [EDGE.pQuiesceReady, EDGE.pRecover], [RACE.pActivateQuiesce], [FAULT.restore]),
  defineSchedule("CORE-I2-PLANNING-LEASE", ["CORE-I2"], two,
    [EDGE.runRelease, EDGE.runRecover], RUN_RACE.lease, [FAULT.lock, FAULT.ack]),
  defineSchedule("CORE-I3-PAIR", ["CORE-I3"], two,
    ALL_LANDED_EDGES, [RACE.cCloseInvalidate], [FAULT.commit]),
  defineSchedule("CORE-I3-PLANNING-DRAFT", ["CORE-I3"], two,
    [EDGE.runCreate, EDGE.runReady, EDGE.runCancelDraft], RUN_RACE.draftReadiness, [FAULT.begin]),
  defineSchedule("CORE-I4-PAIR", ["CORE-I4"], two,
    [EDGE.gClose, EDGE.gInvalidate], [RACE.cCancelInvalidate], [FAULT.artifact]),
  defineSchedule("CORE-I4-PARTIAL-ORDER", ["CORE-I4"], multi,
    [EDGE.gClose, EDGE.gInvalidate, EDGE.gComplete], [RACE.cCloseInvalidate, RACE.cCancelClose],
    [FAULT.artifact, FAULT.commit]),
  defineSchedule("CORE-I4-PLANNING-SEAL", ["CORE-I4"], two,
    [EDGE.runPropose, EDGE.runSeal, EDGE.runRefuse], RUN_RACE.seal, [FAULT.artifact]),
  defineSchedule("CORE-I5-PAIR", ["CORE-I5"], two,
    [EDGE.gCloseAtomic], [RACE.eCancelClose], [FAULT.commit, FAULT.ack]),
  defineSchedule("CORE-I5-PLANNING-DRAIN", ["CORE-I5"], two,
    [EDGE.runProposeDrain, EDGE.runCancelPlanning], RUN_RACE.submission,
    [FAULT.outbox, FAULT.commit]),
  defineSchedule("CORE-I6-PAIR", ["CORE-I6"], two,
    [EDGE.gClose, EDGE.gComplete], [RACE.eClosePause], [FAULT.commit]),
  defineSchedule("CORE-I6-PARTIAL-ORDER", ["CORE-I6"], multi,
    [EDGE.gClose, EDGE.gComplete, EDGE.gInvalidate], [RACE.cCloseInvalidate],
    [FAULT.commit, FAULT.artifact]),
  defineSchedule("CORE-I7-PAIR", ["CORE-I7"], two,
    [EDGE.gPauseExecuting, EDGE.gResumeExecuting], [RACE.ePauseResume], [FAULT.begin]),
  defineSchedule("CORE-I8-PAIR", ["CORE-I8"], two,
    [EDGE.gReopenCompleted, EDGE.revActivate], [RACE.eCancelPause], [FAULT.registration]),
  defineSchedule("CORE-I8-PARTIAL-ORDER", ["CORE-I8"], multi,
    [EDGE.gReopenCompleted, EDGE.revActivate, EDGE.revApprove], [RACE.dActivateResume],
    [FAULT.registration, FAULT.effect]),
  defineSchedule("CORE-I8-REVISION-DECISION", ["CORE-I8"], two,
    [EDGE.revApprove, EDGE.revActivateCompound, EDGE.revRejectApproved, EDGE.revRejectPending],
    [...REVISION_RACE.pending, ...REVISION_RACE.approved], [FAULT.registration, FAULT.effect]),
  defineSchedule("CORE-I9-PAIR", ["CORE-I9"], two,
    [EDGE.gPauseDraft, EDGE.gResumeDraft], [RACE.dPauseResume], [FAULT.ack]),
  defineSchedule("CORE-I10-PAIR", ["CORE-I10"], two,
    [EDGE.gActivate, EDGE.gReopenCancelled], [RACE.dActivatePause], [FAULT.begin]),
  defineSchedule("CORE-I11-PAIR", ["CORE-I11"], two,
    [EDGE.gActivate, EDGE.gCancelExecuting], [RACE.eCancelResume], [FAULT.effect]),
  defineSchedule("CORE-I12-PAIR", ["CORE-I12"], two,
    [EDGE.gActivate, EDGE.gCloseAtomic], [RACE.dCancelResume], [FAULT.commit]),
  defineSchedule("CORE-I12-PLANNING-APPROVAL", ["CORE-I12"], two,
    [EDGE.runApprove, EDGE.runApproveReplay, EDGE.runActivateCompound, EDGE.runRevise],
    RUN_RACE.review, [FAULT.commit]),
  defineSchedule("CORE-I13-PAIR", ["CORE-I13"], two,
    [EDGE.pBind, EDGE.pActivate], [RACE.pActivateBind], [FAULT.registration]),
  defineSchedule("CORE-I13-PLANNING-AUTHORITY", ["CORE-I13"], two,
    [EDGE.runActivate, EDGE.runCancelApproved], RUN_RACE.approvedDecision, [FAULT.registration]),
  defineSchedule("CORE-I14-PAIR", ["CORE-I14"], two,
    [EDGE.gClose, EDGE.gCloseAtomic], [RACE.eCloseResume], [FAULT.artifact]),
  defineSchedule("CORE-I14-PARTIAL-ORDER", ["CORE-I14"], multi,
    [EDGE.gClose, EDGE.gCloseAtomic, EDGE.gComplete], [RACE.cCancelClose],
    [FAULT.artifact, FAULT.checkpoint]),
  defineSchedule("CORE-I15-PAIR", ["CORE-I15"], two,
    [EDGE.pBind, EDGE.pQuiesceBootstrap], [RACE.pBindQuiesce], [FAULT.artifact]),
  defineSchedule("CORE-I16-PAIR", ["CORE-I16"], two,
    [EDGE.gCancelExecuting, EDGE.gResumeExecuting], [RACE.eCancelPause], [FAULT.outbox]),
  defineSchedule("CORE-I16-PARTIAL-ORDER", ["CORE-I16"], multi,
    [EDGE.gCancelExecuting, EDGE.gResumeExecuting, EDGE.gPauseExecuting],
    [RACE.ePauseResume, RACE.eCancelResume], [FAULT.outbox, FAULT.effect]),
  defineSchedule("CORE-I17-PAIR", ["CORE-I17"], two,
    [EDGE.pQuiesceReady, EDGE.pRecover], [RACE.pActivateQuiesce], [FAULT.checkpoint]),
  defineSchedule("CORE-I17-PARTIAL-ORDER", ["CORE-I17"], multi,
    [EDGE.pQuiesceReady, EDGE.pRecover, EDGE.pQuiesceBootstrap], [RACE.pBindQuiesce],
    [FAULT.checkpoint, FAULT.begin]),
  defineSchedule("CORE-I17-PLANNING-RECOVERY", ["CORE-I17"], multi,
    [EDGE.runRelease, EDGE.runRecover, EDGE.runResume], RUN_RACE.recovery,
    [FAULT.checkpoint, FAULT.restore]),
  defineSchedule("CORE-I18-PAIR", ["CORE-I18"], two,
    [EDGE.gInvalidate, EDGE.gClose], [RACE.cCloseInvalidate], [FAULT.ack]),
  defineSchedule("CORE-I19-PAIR", ["CORE-I19"], two,
    [EDGE.gCancelClosing, EDGE.gReopenCancelled], [RACE.cCancelClose], [FAULT.outbox]),
  defineSchedule("CORE-I20-PAIR", ["CORE-I20"], two,
    [EDGE.gPauseExecuting, EDGE.gResumeDraft], [RACE.dPauseResume], [FAULT.begin]),
  defineSchedule("CORE-I21-PAIR", ["CORE-I21"], two,
    [EDGE.gActivate, EDGE.gPauseExecuting], [RACE.dCancelPause], [FAULT.lock]),
  defineSchedule("CORE-I21-PARTIAL-ORDER", ["CORE-I21"], multi,
    [EDGE.gActivate, EDGE.gPauseExecuting, EDGE.gResumeExecuting, EDGE.gCancelDraft],
    [RACE.eClosePause], [FAULT.lock, FAULT.ack]),
  defineSchedule("CORE-I22-PAIR", ["CORE-I22"], two,
    [EDGE.pRegister, EDGE.pQuiesceReady, EDGE.pRecover], [RACE.pActivateQuiesce], [FAULT.restore]),
  defineSchedule("CORE-I22-PARTIAL-ORDER", ["CORE-I22"], multi,
    [EDGE.pRegister, EDGE.pQuiesceReady, EDGE.pRecover, EDGE.pQuiesceBootstrap],
    [RACE.pActivateBind], [FAULT.restore, FAULT.checkpoint]),
]);
