/**
 * Accepted-history contract for graph revision event replay: every legal lifecycle path rebuilds
 * the exact state the command reducer produced, and a redelivery is idempotent rather than additive.
 *
 * Every history here is generated by driving the real `reduceGraphRevision` — see
 * `graph-revision-replay-test-fixtures.ts` for why the reducer is the only honest oracle.
 * Refusal coverage lives in `graph-revision-replay-refusal.test.ts`.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { expect, it } from "vitest";

import type { GraphRevisionState } from "./graph-revision-contract.js";
import { GRAPH_REVISION_EVENT_KINDS } from "./graph-revision-replay.js";
import {
  LEGAL_PATHS,
  approve,
  approveAndActivate,
  approveAndActivateSuccessor,
  create,
  createSuccessor,
  drive,
  replayed,
  submit,
  supersede,
} from "./graph-revision-replay-test-fixtures.js";
import {
  GRAPH_REVISION_COMMAND_KINDS,
  reduceGraphRevision,
} from "./graph-revision-reducer.js";
import { APPROVAL } from "./graph-revision-test-fixtures.js";

it.each(LEGAL_PATHS)("replays %s into the reducer's exact state", (_name, steps, lifecycle) => {
  const driven = drive(steps);
  const result = replayed(driven.events);
  expect(result.state).toEqual(driven.state);
  expect(result.state.lifecycle).toBe(lifecycle);
  expect(result.events).toEqual(driven.events);
});

it.each(LEGAL_PATHS)("returns a deeply frozen state for %s", (_name, steps) => {
  const result = replayed(drive(steps).events);
  expect(Object.isFrozen(result.state)).toBe(true);
  expect(Object.isFrozen(result.events)).toBe(true);
});

it("generates a nonzero path set covering every command kind, event kind and lifecycle", () => {
  expect(LEGAL_PATHS.length).toBeGreaterThan(0);
  const commandKinds = new Set<string>();
  const eventKinds = new Set<string>();
  const lifecycles = new Set<string>();
  for (const [, steps] of LEGAL_PATHS) {
    const driven = drive(steps);
    let current: GraphRevisionState | undefined;
    for (const step of steps) {
      const command = step(current);
      commandKinds.add(command.kind);
      const result = reduceGraphRevision(current, command);
      if (!result.ok) throw new Error(`fixture command ${command.kind} rejected`);
      current = result.state;
    }
    for (const event of driven.events) eventKinds.add(event.kind);
    lifecycles.add(driven.state.lifecycle);
  }
  expect([...commandKinds].sort()).toEqual([...GRAPH_REVISION_COMMAND_KINDS].sort());
  expect([...eventKinds].sort()).toEqual([...GRAPH_REVISION_EVENT_KINDS].sort());
  expect([...lifecycles].sort())
    .toEqual(["ACTIVE", "APPROVED", "DRAFT", "PENDING_APPROVAL", "REJECTED", "SUPERSEDED"]);
});

it("accepts ACTIVE as a control and rebuilds the bound epoch and identity", () => {
  const driven = drive([create, submit, approveAndActivate]);
  const result = replayed(driven.events);
  expect(result.state.lifecycle).toBe("ACTIVE");
  expect(result.state.graphEpoch).toBe(1);
  // Exactly the five binding keys: the approval's ref and truth class are decision evidence,
  // never part of the identity the state carries forward.
  expect(result.state.boundHashes).toEqual({
    budgetHash: APPROVAL.budgetHash, expectedGoalVersion: APPROVAL.expectedGoalVersion,
    graphHash: APPROVAL.graphHash, policyHash: APPROVAL.policyHash,
    qualityHash: APPROVAL.qualityHash,
  });
  expect(result.state).toEqual(driven.state);
});

it("accepts SUPERSEDED as a control and keeps the predecessor's bound epoch", () => {
  const driven = drive([create, submit, approveAndActivate, supersede]);
  const result = replayed(driven.events);
  expect(result.state.lifecycle).toBe("SUPERSEDED");
  expect(result.state.graphEpoch).toBe(1);
  expect(result.state).toEqual(driven.state);
});

it("rebuilds a successor's succession epoch from the activation witness alone", () => {
  const driven = drive([createSuccessor, submit, approveAndActivateSuccessor]);
  const result = replayed(driven.events);
  expect(result.state.graphEpoch).toBe(2);
  expect(result.state).toEqual(driven.state);
});

it("treats a compound approval's two events as distinct despite one shared commandId", () => {
  const driven = drive([create, submit, approveAndActivate]);
  const approved = driven.events.filter((event) => event.kind === "GraphRevisionApproved");
  const activated = driven.events.filter((event) => event.kind === "GraphRevisionActivated");
  expect(approved).toHaveLength(1);
  expect(activated).toHaveLength(1);
  // The precondition that makes this case load-bearing: one commandId, two consecutive versions.
  expect(approved[0]?.commandId).toBe(activated[0]?.commandId);
  expect(activated[0]?.version).toBe((approved[0]?.version ?? 0) + 1);
  expect(replayed(driven.events).state).toEqual(driven.state);
});

it("ignores a byte-identical redelivery without advancing state or duplicating events", () => {
  const driven = drive([create, submit, approve]);
  const doubled = [...driven.events, driven.events[driven.events.length - 1]];
  const result = replayed(doubled);
  expect(result.state).toEqual(driven.state);
  expect(result.events).toEqual(driven.events);
});

it("ignores a full byte-identical history replayed twice end to end", () => {
  const driven = drive([create, submit, approveAndActivate]);
  const result = replayed([...driven.events, ...driven.events]);
  expect(result.state).toEqual(driven.state);
  expect(result.events).toEqual(driven.events);
});

it("publishes the event-kind vocabulary the contract union declares", () => {
  expect(Object.isFrozen(GRAPH_REVISION_EVENT_KINDS)).toBe(true);
  expect([...GRAPH_REVISION_EVENT_KINDS].sort()).toEqual([
    "GraphRevisionActivated", "GraphRevisionApproved", "GraphRevisionCreated",
    "GraphRevisionRejected", "GraphRevisionSubmitted", "GraphRevisionSuperseded",
  ]);
});

/**
 * Byte-exact, not line-wise: vitest rewrites a `./foo.js` specifier back to `foo.ts`, so nothing
 * else in this package can tell a correct bridge from a CRLF one that real Node would still load
 * but that would drift from every other bridge on disk.
 */
it("ships a byte-exact LF bridge for the replay module", () => {
  const bridge = join(dirname(fileURLToPath(import.meta.url)), "graph-revision-replay.js");
  expect(readFileSync(bridge, "utf8")).toBe('export * from "./graph-revision-replay.ts";\n');
});

it("does not mutate or retain the caller's history array", () => {
  const driven = drive([create, submit, approve]);
  const history = [...driven.events];
  const result = replayed(history);
  expect(history).toEqual([...driven.events]);
  expect(result.events).not.toBe(history);
});
