/**
 * "What is the current active graph for this project?", answered from durable
 * revision events through a REAL file-backed SqliteEventStore.
 *
 * EVERY history here is GENERATED by driving the real `reduceGraphRevision` and
 * committing the events it actually emitted. Hand-written event literals are
 * banned on purpose: nothing writes graph-revision events in production yet
 * (measured, zero non-test writers), so a hand-authored shape would let this
 * projection pass against events production will never produce, and the two
 * would drift together while staying green.
 *
 * The reducer fixtures are RESTATED here rather than imported. `@moe/core`'s
 * `graph-revision-test-fixtures.ts` is test-only and unreachable from its root,
 * and the exports map publishes no subpaths — so a deep import is refused at
 * runtime. What is restated is only the COMMAND INPUT; the events, the state and
 * every lifecycle rule still come from the production reducer.
 *
 * WINDOWS HANDLE DISCIPLINE: the store closes in a `finally` inside the temp
 * directory's own `finally`. A handle held across `rmSync` throws EPERM and kills
 * the vitest worker with no output.
 */

import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  createAcceptanceContract, createPlanRevision, reduceGraphRevision,
} from "@moe/core";
import type {
  GraphRevisionCommand,
  GraphRevisionEvent,
  GraphRevisionState,
} from "@moe/core";
import {
  ADMISSION_PURPOSES,
  createNodeDefinition,
  deriveNodeAuthoritySet,
  encodeGraphContent,
  snapshotIdentityHash,
  validateGraphSnapshot,
} from "@moe/scheduler";
import type {
  GraphContent,
  GraphEdge,
  GraphNode,
  GraphRevisionContent,
  GraphSnapshot,
  NodeAuthoritySection,
  NodeDefinition,
} from "@moe/scheduler";
import { SqliteEventStore } from "@moe/store";
import { describe, expect, it } from "vitest";

import { putGraphBody } from "./graph-body-record.js";
import {
  ACTIVE_GRAPH_PROJECTION_CODES,
  ACTIVE_GRAPH_PROJECTION_LAYER,
  graphRevisionAggregateId,
  readCurrentActiveGraph,
} from "./active-graph-projection.js";

const PROJECT_ID = "proj-active-graph-0001";
const ENCODER = new TextEncoder();

// --- content fixtures --------------------------------------------------------

function baseSnapshot(completionNodeKey = "dev-c"): GraphSnapshot {
  const nodes: readonly GraphNode[] = [
    { nodeKey: "dev-a", executionBearing: true },
    { nodeKey: "dev-b", executionBearing: true },
    { nodeKey: "dev-c", executionBearing: true },
  ];
  const edges: readonly GraphEdge[] = [
    { edgeKey: "dev-e1", producerNodeKey: "dev-a", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e2", producerNodeKey: "dev-b", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e3", producerNodeKey: "dev-a", consumerNodeKey: "dev-b", kind: "ADVISORY" },
  ];
  return { nodes, edges, completionNodeKey };
}

// --- v3 node-authority fixtures (task-8c7e6ce4) ------------------------------

/**
 * `GraphRevisionContent` v3 (task-6ba1ff89) makes `nodeAuthority` MANDATORY, and
 * `encodeGraphContent` RE-DERIVES the set it is handed rather than adopting it
 * (`graph-content.ts:120-141`), so a hand-built section can never pass. Everything below
 * COMPOSES the published producers — `createPlanRevision` / `createAcceptanceContract`
 * (@moe/core), then `createNodeDefinition` and `deriveNodeAuthoritySet` (@moe/scheduler) —
 * and judges nothing: each helper hands back what production returned, or throws carrying
 * production's own code, so a fixture that stopped building is never mistaken for a
 * boundary that stopped refusing.
 */
const AUTHORITY_HEX = (digit: string): string => digit.repeat(64);

const planDraftFor = (nodeKeys: readonly string[]): Record<string, unknown> => ({
  affectedCriterionIds: ["criterion-a"],
  affectedNodeIds: [...nodeKeys],
  approvalState: "APPROVED",
  authorRef: "principal-a",
  graphBinding: { graphContentHash: AUTHORITY_HEX("a"), graphRevisionRef: "graph-revision-a" },
  parentRevisionId: null,
  rejectionRef: null,
  revisionId: "plan-revision-a",
  steps: [{ description: "Land the node.", kind: "IMPLEMENTATION", stepId: "step-a" }],
  verificationRecipeRefs: ["recipe-a"],
});

const acceptanceDraftFor = (nodeKeys: readonly string[]): Record<string, unknown> => ({
  applicability: {
    graphContentHash: AUTHORITY_HEX("a"), graphRevisionRef: "graph-revision-a",
    nodeIds: [...nodeKeys], nodeKind: "LEAF",
  },
  authorRef: "principal-a",
  contractId: "acceptance-contract-a",
  obligations: [{
    criterionId: "criterion-a",
    evidenceRequirements: [
      { evidenceRef: "artifact-a", kind: "ARTIFACT", requirementId: "requirement-a" },
    ],
    statement: "The node ships its focused verification.",
    verificationRecipeRefs: ["recipe-a"],
  }],
});

/** A MONOTONIC contract owes a matching registry proof, else the codec refuses
 *  NODE_AUTHORITY_MONOTONIC_PROOF_MISSING @ NODE_AUTHORITY_PROOFS. */
const AUTHORITY_REGISTRY_ENTRY: Record<string, unknown> = {
  parameterSchema: { digest: AUTHORITY_HEX("b"), kind: "JSON_SCHEMA" },
  predicateRef: "predicate-a",
  proofRationale: "An artifact seal cannot become unsealed.",
  schemaId: "schema-a",
  schemaVersion: 1,
  sourceOperationClass: "ARTIFACT_SEAL",
};

/** ONE contract per HARD edge ENTERING a node. `graphBindingDigest` is PRODUCTION's
 *  `snapshotIdentityHash` over the ACCEPTED graph, never a literal: a digest that did not
 *  come from this structure refuses NODE_AUTHORITY_RECURSION_BINDING_MISMATCH at derive
 *  time (`node-authority-recursion.ts:164-167`). */
const hardEdgeRequirement = (edge: GraphEdge, binding: string): Record<string, unknown> => ({
  edgeKey: edge.edgeKey,
  requirement: {
    contract: {
      alternateProducers: [] as string[],
      alternativeRuling: { kind: "NOT_APPLICABLE", reason: "No alternate producer exists." },
      consumer: {
        contractHash: AUTHORITY_HEX("c"), criterionRef: "criterion-a", kind: "PRECONDITION",
      },
      consumerNodeKey: edge.consumerNodeKey,
      consumptionHorizon: "RESULT_SEAL",
      edgeKind: "ARTIFACT_CONSUMPTION",
      graphBindingDigest: binding,
      invalidationFacts: [
        { sourceFactDigest: AUTHORITY_HEX("e"), sourceFactRef: "fact-a", sourceFactVersion: 1 },
      ],
      minimumQualifyingMilestone: "RESULT_SEALED",
      necessity: {
        failedConsumerCriterionRef: "criterion-a", failureKind: "MISSING_ARTIFACT",
        truthClass: "OBSERVED",
      },
      producer: {
        artifactOrInterfaceRef: "artifact-a", digest: AUTHORITY_HEX("f"),
        kind: "ARTIFACT_CONSUMPTION",
      },
      producerNodeKey: edge.producerNodeKey,
      recheckPredicateRef: "predicate-a",
      satisfactionPredicate: {
        parametersDigest: AUTHORITY_HEX("1"), predicateRef: "predicate-a",
        schemaId: "schema-a", schemaVersion: 1,
      },
      satisfactionWitnesses: [{
        sourceOperationClass: "ARTIFACT_SEAL", witnessDigest: AUTHORITY_HEX("2"),
        witnessRef: "witness-a", witnessVersion: 1,
      }],
      stability: "MONOTONIC",
      truthClass: "OBSERVED",
    },
    edgeKind: "ARTIFACT_CONSUMPTION",
  },
});

/** Admitted by PRODUCTION or not built at all: a body the codec refuses could never reach
 *  the encode this fixture exists to feed. */
function nodeDefinitionFor(
  nodeKey: string, snapshot: GraphSnapshot, binding: string,
): NodeDefinition {
  const nodeKeys = snapshot.nodes.map((node) => node.nodeKey);
  const plan = createPlanRevision(planDraftFor(nodeKeys));
  if (!plan.ok) throw new Error(`plan revision fixture refused: ${plan.code}`);
  const acceptance = createAcceptanceContract(acceptanceDraftFor(nodeKeys));
  if (!acceptance.ok) throw new Error(`acceptance fixture refused: ${acceptance.code}`);
  const completes = nodeKey === snapshot.completionNodeKey;
  const built = createNodeDefinition({
    acceptanceContract: acceptance.contract,
    draft: {
      admissionAmounts: [...ADMISSION_PURPOSES].sort().map((purpose, index) => ({
        meter: "runner.authorized_ms", purpose, quantity: index + 1,
      })),
      admissionGatePolicy: "POLICY_ALLOWANCE",
      capability: "capability-implement",
      completionLinkage: completes ? nodeKey : null,
      constraints: ["constraint-a"],
      directHardDependencies: snapshot.edges
        .filter((edge) => edge.kind === "HARD" && edge.consumerNodeKey === nodeKey)
        .map((edge) => hardEdgeRequirement(edge, binding)),
      joinRole: completes ? "COMPLETION" : "NONE",
      nodeKey,
      objective: `Land ${nodeKey}.`,
      policySliceHash: AUTHORITY_HEX("3"),
      readScopes: ["services/api/src"],
      repositoryBaseTree: AUTHORITY_HEX("4"),
      resources: ["resource-a"],
      verificationRecipeRevisions: ["recipe-a"],
      writeScopes: ["services/api/src/node"],
    },
    planRevision: plan.revision,
    predicateRegistry: [AUTHORITY_REGISTRY_ENTRY],
  });
  if (!built.ok) {
    throw new Error(built.issues.map((issue) => `${issue.code}@${issue.layer}`).join(","));
  }
  return built.value.definition;
}

/**
 * The authenticated half of a v3 record. `definitions` is sorted by `nodeKey` because
 * `readAuthoritySection` requires the two arrays index-aligned and STRICTLY ASCENDING
 * (`graph-content-fields.ts:121-147`), and `deriveNodeAuthoritySet` already returns its
 * entries in that order. `authorities` is the PRODUCER'S own value, never a rebuilt one:
 * `bindAuthority` re-derives and refuses GRAPH_CONTENT_AUTHORITY_DISAGREEMENT on any
 * stated set that is not the derived one.
 */
function authoritySectionFor(snapshot: GraphSnapshot): NodeAuthoritySection {
  const validated = validateGraphSnapshot(snapshot);
  if (!validated.ok) {
    throw new Error(`graph fixture refused: ${validated.issues[0]?.code ?? "?"}`);
  }
  const binding = snapshotIdentityHash(validated.graph);
  const definitions = snapshot.nodes
    .map((node) => node.nodeKey)
    .slice()
    .sort()
    .map((nodeKey) => nodeDefinitionFor(nodeKey, snapshot, binding));
  const derived = deriveNodeAuthoritySet(snapshot, definitions);
  if (!derived.ok) {
    throw new Error(derived.issues.map((issue) => `${issue.code}@${issue.layer}`).join(","));
  }
  return { authorities: derived.value, definitions };
}

function encoded(author: string): GraphContent {
  const snapshot = baseSnapshot();
  const content: GraphRevisionContent = {
    author,
    completionNode: "dev-c",
    decompositionBudget: 24,
    nodeAuthority: authoritySectionFor(snapshot),
    parentRevision: "rev-000000000000",
    policyRevision: "pol-000000000001",
    repositoryBaseTree: "4".repeat(40),
    snapshot,
  };
  const result = encodeGraphContent(content);
  if (!result.ok) throw new Error(`fixture failed to encode: ${JSON.stringify(result.issues)}`);
  return result.value;
}

const PRIMARY = encoded("human:architect-primary");
const SUCCESSOR_CONTENT = encoded("human:architect-successor");

// --- reducer command fixtures (input only; the reducer owns every rule) -------

function seededHash(seed: string): string {
  return seed.repeat(64).slice(0, 64);
}

const PLAN_HASH = seededHash("11");
/**
 * The binding is derived from the revision's OWN content hash. It cannot be a
 * shared constant: the reducer refuses `REVISION_REBOUND` when an approval binds
 * a graph hash the revision was not created with, so a second revision seeded
 * from the first one's binding never reaches ACTIVE at all.
 */
function bindingOf(graphHash: string) {
  return {
    budgetHash: seededHash("55"),
    expectedGoalVersion: 3,
    graphHash,
    policyHash: seededHash("66"),
    qualityHash: seededHash("33"),
  } as const;
}

const SUBMISSION = { submissionRef: "submission-1", truthClass: "DAEMON_VERIFIED" } as const;
const CANONICALIZER = "canon-v1";
const CARRY_HASH = seededHash("44");
const BINDING_HASH = seededHash("66");

function carryFact(digest: string) {
  return {
    canonicalizerVersion: CANONICALIZER, dependenciesPresent: true,
    environmentClosureUnchanged: true, policySliceUnchanged: true,
    predecessorResultUnchanged: true, sourceHash: digest, targetHash: digest,
  };
}

const CARRY = {
  kind: "CARRY", nodeKey: "node-carry", predecessorAuthorityHash: CARRY_HASH,
  safeCarry: { authority: carryFact(CARRY_HASH), inputBinding: carryFact(BINDING_HASH) },
  successorAuthorityHash: CARRY_HASH,
} as const;

type Step = (current: GraphRevisionState | undefined) => GraphRevisionCommand;

function versionOf(current: GraphRevisionState | undefined): number {
  return current === undefined ? 0 : current.version;
}

function createOf(revisionId: string, graphContentHash: string): Step {
  return () => ({
    commandId: `cmd-create-${revisionId}`, expectedVersion: 0, goalRef: "goal-1",
    graphContentHash, kind: "graph_revision.create", planHash: PLAN_HASH, revisionId,
  }) as GraphRevisionCommand;
}

const submit: Step = (current) => ({
  commandId: "cmd-submit", expectedVersion: versionOf(current),
  kind: "graph_revision.submit", witness: SUBMISSION,
}) as GraphRevisionCommand;

/**
 * Approval WITHOUT activation, which lands the revision in APPROVED. Its absence
 * was a real hole: with every fixture jumping straight to ACTIVE via the compound
 * command, widening the projection's lifecycle filter to accept APPROVED changed
 * no test outcome. This is the fixture that makes that filter observable.
 */
function approveOnlyOf(graphHash: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    approval: { ...binding, approvalRef: "approval-1", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

function approveAndActivateOf(graphHash: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    activation: {
      ...binding, activationRef: "activation-1", graphEpoch: 1, truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: "approval-1", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

function successorBindingOf(current: GraphRevisionState) {
  return {
    graphContentHash: SUCCESSOR_CONTENT.graphContentHash,
    graphEpoch: current.graphEpoch + 1,
    predecessorGraphContentHash: current.graphContentHash,
    predecessorRevisionId: current.revisionId,
    revisionId: "graph-revision-2",
  };
}

const supersede: Step = (current) => {
  if (current === undefined) throw new Error("supersede needs a live state");
  return {
    commandId: "cmd-supersede", expectedVersion: current.version, kind: "graph.supersede",
    supersession: {
      dispositions: [CARRY],
      expectedPredecessor: {
        graphContentHash: current.graphContentHash, graphEpoch: current.graphEpoch,
        revisionId: current.revisionId,
      },
      successor: successorBindingOf(current),
      supportedCanonicalizerVersions: [CANONICALIZER],
    },
  } as unknown as GraphRevisionCommand;
};

function approveAndActivateSuccessorOf(predecessor: GraphRevisionState): Step {
  const successor = successorBindingOf(predecessor);
  const binding = bindingOf(successor.graphContentHash);
  return (current) => ({
    activation: {
      ...binding, activationRef: "activation-2", graphEpoch: successor.graphEpoch,
      succession: {
        predecessorGraphContentHash: successor.predecessorGraphContentHash,
        predecessorGraphEpoch: predecessor.graphEpoch,
        predecessorRevisionId: successor.predecessorRevisionId,
      },
      truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: "approval-2", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve-2", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

// --- harness -----------------------------------------------------------------

function withStore<T>(name: string, run: (store: SqliteEventStore) => T): T {
  const directory = mkdtempSync(join(tmpdir(), `moe-active-graph-${name}-`));
  try {
    const store = SqliteEventStore.openForProject(join(directory, "store.sqlite"), PROJECT_ID);
    try {
      return run(store);
    } finally {
      store.close();
    }
  } finally {
    rmSync(directory, { force: true, maxRetries: 5, recursive: true });
  }
}

/** Drives the REAL reducer and returns the events it actually emitted. */
function drive(steps: readonly Step[]): { events: GraphRevisionEvent[]; state: GraphRevisionState } {
  let current: GraphRevisionState | undefined;
  const events: GraphRevisionEvent[] = [];
  for (const step of steps) {
    const result = reduceGraphRevision(current, step(current));
    if (!result.ok) throw new Error(`fixture command rejected: ${result.error.code}`);
    current = result.state;
    events.push(...result.events);
  }
  if (current === undefined) throw new Error("path produced no state");
  return { events, state: current };
}

function commitEvents(
  store: SqliteEventStore,
  revisionId: string,
  events: readonly GraphRevisionEvent[],
  tag = "seed",
): void {
  const aggregateId = graphRevisionAggregateId(PROJECT_ID, revisionId);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(`${tag}-${revisionId}`),
    commandId: `${tag}-${revisionId}`,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: events.map((event, index) => ({
      eventId: `${tag}-${revisionId}-${index}`,
      eventType: event.kind,
      payload: ENCODER.encode(JSON.stringify(event)),
    })),
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** Seed a revision AND the body its content hash names — the normal, whole path. */
function seedActive(store: SqliteEventStore, revisionId: string, content: GraphContent) {
  const driven = drive([
    createOf(revisionId, content.graphContentHash), submit,
    approveAndActivateOf(content.graphContentHash),
  ]);
  commitEvents(store, revisionId, driven.events);
  putGraphBody(store, PROJECT_ID, content);
  return driven;
}

function revisionEventCount(store: SqliteEventStore, revisionId: string): number {
  return store.readEvents(graphRevisionAggregateId(PROJECT_ID, revisionId)).length;
}

// --- tests -------------------------------------------------------------------

describe("current active graph projection", () => {
  it("returns the single ACTIVE revision with identity, epoch and decoded content", () => {
    withStore("accept", (store) => {
      const driven = seedActive(store, "graph-revision-1", PRIMARY);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(true);
      if (!read.ok) throw new Error(`unexpected refusal ${read.code}`);

      expect(read.revisionId).toBe("graph-revision-1");
      expect(read.graphEpoch).toBe(driven.state.graphEpoch);
      expect(read.graphEpoch).toBe(1);
      expect(read.planHash).toBe(PLAN_HASH);
      expect(read.graphContentHash).toBe(PRIMARY.graphContentHash);
      expect(read.content).toEqual(PRIMARY.content);
      expect(read.snapshot).toEqual(baseSnapshot());
      expect(read.provenance.aggregateId)
        .toBe(graphRevisionAggregateId(PROJECT_ID, "graph-revision-1"));

      // dec-64b2391c pinned at the consumer: the structural identity is answered
      // beside the content hash and is never equal to it.
      expect(read.snapshotIdentity).toBe(PRIMARY.snapshotIdentity);
      expect(read.snapshotIdentity).not.toBe(read.graphContentHash);

      expect(Object.isFrozen(read)).toBe(true);
    });
  });

  it("refuses with no snapshot authority when no revision is ACTIVE", () => {
    withStore("absent", (store) => {
      // DRAFT only: a real history that simply never reached ACTIVE.
      const driven = drive([createOf("graph-revision-1", PRIMARY.graphContentHash)]);
      commitEvents(store, "graph-revision-1", driven.events);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a non-active project yielded a snapshot");
      expect(read.code).toBe("ACTIVE_GRAPH_ABSENT");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      expect(read.sourceLayer).toBeNull();
      expect(read).not.toHaveProperty("snapshot");
    });
  });

  it("treats an APPROVED revision as NOT active, even with its body stored", () => {
    withStore("approved", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
        approveOnlyOf(PRIMARY.graphContentHash),
      ]);
      // The revision is genuinely APPROVED — one legal step short of ACTIVE — and
      // its body IS present, so nothing else can be the reason for the refusal.
      expect(driven.state.lifecycle).toBe("APPROVED");
      expect(driven.state.graphEpoch).toBe(0);
      commitEvents(store, "graph-revision-1", driven.events);
      putGraphBody(store, PROJECT_ID, PRIMARY);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("an APPROVED revision was served as the active graph");
      expect(read.code).toBe("ACTIVE_GRAPH_ABSENT");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      expect(read.sourceLayer).toBeNull();
    });
  });

  it("refuses split-brain rather than picking a winner between two ACTIVE revisions", () => {
    withStore("split", (store) => {
      seedActive(store, "graph-revision-1", PRIMARY);
      seedActive(store, "graph-revision-9", SUCCESSOR_CONTENT);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("split-brain was resolved instead of refused");
      expect(read.code).toBe("ACTIVE_GRAPH_SPLIT_BRAIN");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      // Distinct from absence: collapsing the two would hide a real split.
      expect(read.code).not.toBe("ACTIVE_GRAPH_ABSENT");
    });
  });

  it("returns only the successor when a SUPERSEDED predecessor precedes it", () => {
    withStore("supersede", (store) => {
      const first = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit, approveAndActivateOf(PRIMARY.graphContentHash),
        supersede,
      ]);
      expect(first.state.lifecycle).toBe("SUPERSEDED");
      commitEvents(store, "graph-revision-1", first.events);
      putGraphBody(store, PROJECT_ID, PRIMARY);

      const second = drive([
        createOf("graph-revision-2", SUCCESSOR_CONTENT.graphContentHash), submit,
        approveAndActivateSuccessorOf(first.state),
      ]);
      commitEvents(store, "graph-revision-2", second.events);
      putGraphBody(store, PROJECT_ID, SUCCESSOR_CONTENT);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(true);
      if (!read.ok) throw new Error(`unexpected refusal ${read.code}`);
      expect(read.revisionId).toBe("graph-revision-2");
      expect(read.graphContentHash).toBe(SUCCESSOR_CONTENT.graphContentHash);
      // The epoch is a BOUND reference carried from the goal, not a local counter.
      expect(read.graphEpoch).toBe(first.state.graphEpoch + 1);
      expect(read.graphEpoch).toBe(2);
    });
  });

  it("surfaces the CORE REPLAY's own code, naming core as the layer that refused", () => {
    withStore("conflict", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit, approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      commitEvents(store, "graph-revision-1", driven.events);
      // One deliberate drift from a GENERATED history: the same version redelivered
      // with different bytes. The core replay owns this rule; the projection must
      // not have an opinion about it.
      const first = driven.events[0];
      if (first === undefined) throw new Error("generated history was empty");
      const drifted = { ...first, goalRef: "goal-DRIFTED" } as unknown as GraphRevisionEvent;
      commitEvents(store, "graph-revision-1", [drifted], "drift");

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a conflicting history still produced a snapshot");
      expect(read.code).toBe("GRAPH_REVISION_REPLAY_IDENTITY_CONFLICT");
      // WHICH layer refused, kept distinct from which layer reported.
      expect(read.sourceLayer).toBe("CORE_GRAPH_REVISION_REPLAY");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
    });
  });

  it("refuses with its own code when the ACTIVE revision's body is missing", () => {
    withStore("no-body", (store) => {
      // Revision seeded WITHOUT its body: the hash names bytes nobody stored.
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit, approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      commitEvents(store, "graph-revision-1", driven.events);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a bodiless revision produced a snapshot");
      expect(read.code).toBe("ACTIVE_GRAPH_BODY_UNAVAILABLE");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      expect(read.sourceLayer).toBe("GRAPH_BODY_RECORD");
      // The underlying cause survives rather than being flattened away.
      expect(read.sourceCode).toBe("GRAPH_BODY_ABSENT");
    });
  });

  it("is byte-stable across consecutive reads and appends nothing", () => {
    withStore("stable", (store) => {
      seedActive(store, "graph-revision-1", PRIMARY);
      const before = revisionEventCount(store, "graph-revision-1");

      const first = readCurrentActiveGraph(store, PROJECT_ID);
      const second = readCurrentActiveGraph(store, PROJECT_ID);

      expect(JSON.stringify(first)).toBe(JSON.stringify(second));
      expect(first).toEqual(second);
      expect(revisionEventCount(store, "graph-revision-1")).toBe(before);
    });
  });

  it("discovers aggregates payload-free instead of paging the whole event store", () => {
    withStore("payload-free", (store) => {
      seedActive(store, "graph-revision-1", PRIMARY);
      const counts = { readEventsAfter: 0 };
      const counted = new Proxy(store, {
        get(target, property) {
          if (property === "readEventsAfter") {
            return (...args: Parameters<SqliteEventStore["readEventsAfter"]>) => {
              counts.readEventsAfter += 1;
              return target.readEventsAfter(...args);
            };
          }
          const value = Reflect.get(target, property, target) as unknown;
          return typeof value === "function"
            ? (value as (...functionArguments: readonly unknown[]) => unknown).bind(target)
            : value;
        },
      });

      const read = readCurrentActiveGraph(counted, PROJECT_ID);

      // The ANSWER is unchanged; what this pins is HOW discovery read for it.
      expect(read.ok).toBe(true);
      if (!read.ok) throw new Error(`unexpected refusal ${read.code}`);
      expect(read.revisionId).toBe("graph-revision-1");
      // Discovery must key on aggregate ids alone. Paging the global stream
      // through readEventsAfter materializes EVERY stored payload on EVERY
      // read — the cost this projection was measured paying per caller.
      expect(counts.readEventsAfter).toBe(0);
    });
  });

  it("refuses every hostile ordering with its OWN code and refusing layer", () => {
    const legal = drive([
      createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
      approveAndActivateOf(PRIMARY.graphContentHash),
    ]).events;

    /**
     * Each case is ONE deliberate drift from the generated legal history, and
     * each carries the EXACT code and refusing layer it must produce.
     *
     * The previous version of this sweep asserted only `ok === false` plus a
     * layer that `refuse()` hardcodes on every path — a vacuous pair that let a
     * real defect (a create-less history answering ACTIVE_GRAPH_ABSENT, the same
     * answer a clean empty project gives) sit inside a green suite. Carrying the
     * expected code per case is what makes the sweep testable at all.
     */
    const cases: readonly (readonly [
      string, readonly GraphRevisionEvent[], string, string | null,
    ])[] = [
      ["missing create", legal.slice(1),
        "GRAPH_REVISION_REPLAY_MISSING_CREATE", "CORE_GRAPH_REVISION_REPLAY"],
      ["reversed", [...legal].reverse(),
        "GRAPH_REVISION_REPLAY_MISSING_CREATE", "CORE_GRAPH_REVISION_REPLAY"],
      ["activation before submission", [legal[0], legal[2], legal[1]]
        .filter((event): event is GraphRevisionEvent => event !== undefined),
      "GRAPH_REVISION_REPLAY_VERSION_BREAK", "CORE_GRAPH_REVISION_REPLAY"],
    ];

    // A sweep that silently generated zero cases would pass while testing nothing.
    expect(cases.length).toBeGreaterThan(0);
    expect(cases.length).toBe(3);
    expect(new Set(cases.map(([name]) => name)).size).toBe(cases.length);
    // Every case must name a code the projection can actually answer with, and
    // none may be the absent code — that is the collapse this sweep now forbids.
    for (const [, , code] of cases) expect(code).not.toBe("ACTIVE_GRAPH_ABSENT");

    for (const [name, history, code, sourceLayer] of cases) {
      withStore(`hostile-${code}-${history.length}`, (store) => {
        commitEvents(store, "graph-revision-1", history);
        putGraphBody(store, PROJECT_ID, PRIMARY);

        const read = readCurrentActiveGraph(store, PROJECT_ID);
        expect(read.ok, `${name} was accepted`).toBe(false);
        if (read.ok) throw new Error(`${name} produced a snapshot`);
        expect(read.code, `${name} code`).toBe(code);
        // WHICH layer refused, kept distinct from which layer reported. The
        // `layer` field alone is hardcoded by refuse() and proves nothing.
        expect(read.sourceLayer, `${name} sourceLayer`).toBe(sourceLayer);
        expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      });
    }
  });

  it("distinguishes a create-less history from an empty project", () => {
    withStore("no-create", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
        approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      // The submitted+activated events WITHOUT the create that opened them: a
      // genuinely corrupt durable history, not an absent one.
      const withoutCreate = driven.events.filter(
        (event) => event.kind !== "GraphRevisionCreated",
      );
      expect(withoutCreate.length).toBeGreaterThan(0);
      expect(withoutCreate.length).toBe(driven.events.length - 1);
      commitEvents(store, "graph-revision-1", withoutCreate);
      putGraphBody(store, PROJECT_ID, PRIMARY);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a create-less history produced a snapshot");
      // The core replay owns this rule and has a dedicated code for it. Answering
      // ACTIVE_GRAPH_ABSENT here would make a corrupt history indistinguishable
      // from a clean empty project, which is the defect QA measured.
      expect(read.code).toBe("GRAPH_REVISION_REPLAY_MISSING_CREATE");
      expect(read.sourceLayer).toBe("CORE_GRAPH_REVISION_REPLAY");
      expect(read.code).not.toBe("ACTIVE_GRAPH_ABSENT");
    });
  });

  it("answers ABSENT for a genuinely empty project, distinctly", () => {
    withStore("empty", (store) => {
      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("an empty project produced a snapshot");
      expect(read.code).toBe("ACTIVE_GRAPH_ABSENT");
      expect(read.sourceLayer).toBeNull();
    });
  });

  it("is idempotent under byte-identical redelivery of the whole history", () => {
    withStore("redelivery", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
        approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      commitEvents(store, "graph-revision-1", driven.events);
      putGraphBody(store, PROJECT_ID, PRIMARY);
      const once = readCurrentActiveGraph(store, PROJECT_ID);

      // The SAME events delivered again, byte for byte. DoD 3 requires this to be
      // idempotent, and the core replay owns that rule — it ignores an identical
      // redelivery rather than refusing it, so the projection must still answer.
      commitEvents(store, "graph-revision-1", driven.events, "redeliver");
      const twice = readCurrentActiveGraph(store, PROJECT_ID);

      expect(once.ok).toBe(true);
      expect(twice.ok).toBe(true);
      if (!once.ok || !twice.ok) throw new Error("redelivery broke the read");
      expect(twice).toEqual(once);
      expect(twice.graphEpoch).toBe(once.graphEpoch);
      // The raw events DID double; the projected answer did not move.
      expect(revisionEventCount(store, "graph-revision-1"))
        .toBe(driven.events.length * 2);
    });
  });

  it("declares every refusal code it originates, and no more", () => {
    expect([...ACTIVE_GRAPH_PROJECTION_CODES].sort()).toEqual([
      "ACTIVE_GRAPH_ABSENT",
      "ACTIVE_GRAPH_BODY_UNAVAILABLE",
      "ACTIVE_GRAPH_EVIDENCE_UNAVAILABLE",
      "ACTIVE_GRAPH_SPLIT_BRAIN",
    ]);
  });
});

/**
 * DoD 2 of task-8c7e6ce4 — see the same block in `graph-body-record.test.ts`. Every original
 * projection assertion above is retained unchanged; these ADD the authority the v3 body now
 * carries. Each case keeps one operand the producer did not supply, so none is a tautology:
 * the counts come from this file's own snapshot literal and the ordering rule from
 * `readAuthoritySection`'s contract.
 */
describe("v3 node authority", () => {
  it("states one authority per snapshot node, index-aligned with its definition", () => {
    const snapshot = baseSnapshot();
    const section = authoritySectionFor(snapshot);

    expect(snapshot.nodes.length).toBeGreaterThan(0);
    expect(section.authorities).toHaveLength(snapshot.nodes.length);
    expect(section.definitions).toHaveLength(snapshot.nodes.length);
    expect(section.definitions.map((definition) => definition.nodeKey))
      .toEqual(section.authorities.map((entry) => entry.nodeKey));
  });

  it("orders the section strictly ascending by nodeKey, as the field reader demands", () => {
    const keys = authoritySectionFor(baseSnapshot()).authorities.map((entry) => entry.nodeKey);
    expect(keys).toEqual([...keys].sort());
    expect(new Set(keys).size).toBe(keys.length);
  });

  it("carries one distinct 64-hex hash per node, none of them stated by this fixture", () => {
    const hashes = authoritySectionFor(baseSnapshot())
      .authorities.map((entry) => entry.nodeAuthorityHash);
    expect(hashes.filter((hash) => /^[0-9a-f]{64}$/u.test(hash))).toHaveLength(hashes.length);
    expect(new Set(hashes).size).toBe(hashes.length);
  });

  it("derives over exactly the HARD edges of the fixture graph, ADVISORY excluded", () => {
    const snapshot = baseSnapshot();
    const derived = deriveNodeAuthoritySet(
      snapshot, authoritySectionFor(snapshot).definitions,
    );
    expect(derived.ok).toBe(true);
    if (!derived.ok) return;
    expect(derived.hardEdgeCount)
      .toBe(snapshot.edges.filter((edge) => edge.kind === "HARD").length);
  });

  it("carries the authority into the PROJECTED body, not only into the fixture", () => {
    // The projection path is what this file exists to prove, so the authority is read back
    // off the encoded content the projection stores rather than off the builder's return.
    const projected = encoded("human:architect-primary");
    expect(projected.content.nodeAuthority.authorities)
      .toHaveLength(baseSnapshot().nodes.length);
    expect(projected.content.nodeAuthority.definitions.map((d) => d.nodeKey))
      .toEqual(projected.content.nodeAuthority.authorities.map((a) => a.nodeKey));
  });
});
