/**
 * "What is the current active graph for this project?", answered from durable
 * revision events through a REAL file-backed SqliteEventStore.
 *
 * EVERY history here is GENERATED by driving the real `reduceGraphRevision` and
 * committing the events it actually emitted. Hand-written event literals are
 * banned on purpose: nothing writes graph-revision events in production yet
 * (measured, zero non-test writers), so a hand-authored shape would let this
 * projection pass against events production will never produce, and the two
 * would drift together while staying green.
 *
 * The reducer fixtures are RESTATED here rather than imported. `@moe/core`'s
 * `graph-revision-test-fixtures.ts` is test-only and unreachable from its root,
 * and the exports map publishes no subpaths — so a deep import is refused at
 * runtime. What is restated is only the COMMAND INPUT; the events, the state and
 * every lifecycle rule still come from the production reducer.
 *
 * WINDOWS HANDLE DISCIPLINE: the store closes in a `finally` inside the temp
 * directory's own `finally`. A handle held across `rmSync` throws EPERM and kills
 * the vitest worker with no output.
 */

import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { reduceGraphRevision } from "@moe/core";
import type {
  GraphRevisionCommand,
  GraphRevisionEvent,
  GraphRevisionState,
} from "@moe/core";
import { encodeGraphContent } from "@moe/scheduler";
import type {
  GraphContent,
  GraphEdge,
  GraphNode,
  GraphRevisionContent,
  GraphSnapshot,
} from "@moe/scheduler";
import { SqliteEventStore } from "@moe/store";
import { describe, expect, it } from "vitest";

import { putGraphBody } from "./graph-body-record.js";
import {
  ACTIVE_GRAPH_PROJECTION_CODES,
  ACTIVE_GRAPH_PROJECTION_LAYER,
  graphRevisionAggregateId,
  readCurrentActiveGraph,
} from "./active-graph-projection.js";

const PROJECT_ID = "proj-active-graph-0001";
const ENCODER = new TextEncoder();

// --- content fixtures --------------------------------------------------------

function baseSnapshot(completionNodeKey = "dev-c"): GraphSnapshot {
  const nodes: readonly GraphNode[] = [
    { nodeKey: "dev-a", executionBearing: true },
    { nodeKey: "dev-b", executionBearing: true },
    { nodeKey: "dev-c", executionBearing: true },
  ];
  const edges: readonly GraphEdge[] = [
    { edgeKey: "dev-e1", producerNodeKey: "dev-a", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e2", producerNodeKey: "dev-b", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e3", producerNodeKey: "dev-a", consumerNodeKey: "dev-b", kind: "ADVISORY" },
  ];
  return { nodes, edges, completionNodeKey };
}

function encoded(author: string): GraphContent {
  const content = {
    author,
    completionNode: "dev-c",
    decompositionBudget: 24,
    parentRevision: "rev-000000000000",
    policyRevision: "pol-000000000001",
    repositoryBaseTree: "4".repeat(40),
    snapshot: baseSnapshot(),
  } as unknown as GraphRevisionContent;
  const result = encodeGraphContent(content);
  if (!result.ok) throw new Error(`fixture failed to encode: ${JSON.stringify(result.issues)}`);
  return result.value;
}

const PRIMARY = encoded("human:architect-primary");
const SUCCESSOR_CONTENT = encoded("human:architect-successor");

// --- reducer command fixtures (input only; the reducer owns every rule) -------

function seededHash(seed: string): string {
  return seed.repeat(64).slice(0, 64);
}

const PLAN_HASH = seededHash("11");
/**
 * The binding is derived from the revision's OWN content hash. It cannot be a
 * shared constant: the reducer refuses `REVISION_REBOUND` when an approval binds
 * a graph hash the revision was not created with, so a second revision seeded
 * from the first one's binding never reaches ACTIVE at all.
 */
function bindingOf(graphHash: string) {
  return {
    budgetHash: seededHash("55"),
    expectedGoalVersion: 3,
    graphHash,
    policyHash: seededHash("66"),
    qualityHash: seededHash("33"),
  } as const;
}

const SUBMISSION = { submissionRef: "submission-1", truthClass: "DAEMON_VERIFIED" } as const;
const CANONICALIZER = "canon-v1";
const CARRY_HASH = seededHash("44");
const BINDING_HASH = seededHash("66");

function carryFact(digest: string) {
  return {
    canonicalizerVersion: CANONICALIZER, dependenciesPresent: true,
    environmentClosureUnchanged: true, policySliceUnchanged: true,
    predecessorResultUnchanged: true, sourceHash: digest, targetHash: digest,
  };
}

const CARRY = {
  kind: "CARRY", nodeKey: "node-carry", predecessorAuthorityHash: CARRY_HASH,
  safeCarry: { authority: carryFact(CARRY_HASH), inputBinding: carryFact(BINDING_HASH) },
  successorAuthorityHash: CARRY_HASH,
} as const;

type Step = (current: GraphRevisionState | undefined) => GraphRevisionCommand;

function versionOf(current: GraphRevisionState | undefined): number {
  return current === undefined ? 0 : current.version;
}

function createOf(revisionId: string, graphContentHash: string): Step {
  return () => ({
    commandId: `cmd-create-${revisionId}`, expectedVersion: 0, goalRef: "goal-1",
    graphContentHash, kind: "graph_revision.create", planHash: PLAN_HASH, revisionId,
  }) as GraphRevisionCommand;
}

const submit: Step = (current) => ({
  commandId: "cmd-submit", expectedVersion: versionOf(current),
  kind: "graph_revision.submit", witness: SUBMISSION,
}) as GraphRevisionCommand;

/**
 * Approval WITHOUT activation, which lands the revision in APPROVED. Its absence
 * was a real hole: with every fixture jumping straight to ACTIVE via the compound
 * command, widening the projection's lifecycle filter to accept APPROVED changed
 * no test outcome. This is the fixture that makes that filter observable.
 */
function approveOnlyOf(graphHash: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    approval: { ...binding, approvalRef: "approval-1", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

function approveAndActivateOf(graphHash: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    activation: {
      ...binding, activationRef: "activation-1", graphEpoch: 1, truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: "approval-1", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

function successorBindingOf(current: GraphRevisionState) {
  return {
    graphContentHash: SUCCESSOR_CONTENT.graphContentHash,
    graphEpoch: current.graphEpoch + 1,
    predecessorGraphContentHash: current.graphContentHash,
    predecessorRevisionId: current.revisionId,
    revisionId: "graph-revision-2",
  };
}

const supersede: Step = (current) => {
  if (current === undefined) throw new Error("supersede needs a live state");
  return {
    commandId: "cmd-supersede", expectedVersion: current.version, kind: "graph.supersede",
    supersession: {
      dispositions: [CARRY],
      expectedPredecessor: {
        graphContentHash: current.graphContentHash, graphEpoch: current.graphEpoch,
        revisionId: current.revisionId,
      },
      successor: successorBindingOf(current),
      supportedCanonicalizerVersions: [CANONICALIZER],
    },
  } as unknown as GraphRevisionCommand;
};

function approveAndActivateSuccessorOf(predecessor: GraphRevisionState): Step {
  const successor = successorBindingOf(predecessor);
  const binding = bindingOf(successor.graphContentHash);
  return (current) => ({
    activation: {
      ...binding, activationRef: "activation-2", graphEpoch: successor.graphEpoch,
      succession: {
        predecessorGraphContentHash: successor.predecessorGraphContentHash,
        predecessorGraphEpoch: predecessor.graphEpoch,
        predecessorRevisionId: successor.predecessorRevisionId,
      },
      truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: "approval-2", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve-2", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

// --- harness -----------------------------------------------------------------

function withStore<T>(name: string, run: (store: SqliteEventStore) => T): T {
  const directory = mkdtempSync(join(tmpdir(), `moe-active-graph-${name}-`));
  try {
    const store = SqliteEventStore.openForProject(join(directory, "store.sqlite"), PROJECT_ID);
    try {
      return run(store);
    } finally {
      store.close();
    }
  } finally {
    rmSync(directory, { force: true, maxRetries: 5, recursive: true });
  }
}

/** Drives the REAL reducer and returns the events it actually emitted. */
function drive(steps: readonly Step[]): { events: GraphRevisionEvent[]; state: GraphRevisionState } {
  let current: GraphRevisionState | undefined;
  const events: GraphRevisionEvent[] = [];
  for (const step of steps) {
    const result = reduceGraphRevision(current, step(current));
    if (!result.ok) throw new Error(`fixture command rejected: ${result.error.code}`);
    current = result.state;
    events.push(...result.events);
  }
  if (current === undefined) throw new Error("path produced no state");
  return { events, state: current };
}

function commitEvents(
  store: SqliteEventStore,
  revisionId: string,
  events: readonly GraphRevisionEvent[],
  tag = "seed",
): void {
  const aggregateId = graphRevisionAggregateId(PROJECT_ID, revisionId);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(`${tag}-${revisionId}`),
    commandId: `${tag}-${revisionId}`,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: events.map((event, index) => ({
      eventId: `${tag}-${revisionId}-${index}`,
      eventType: event.kind,
      payload: ENCODER.encode(JSON.stringify(event)),
    })),
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** Seed a revision AND the body its content hash names — the normal, whole path. */
function seedActive(store: SqliteEventStore, revisionId: string, content: GraphContent) {
  const driven = drive([
    createOf(revisionId, content.graphContentHash), submit,
    approveAndActivateOf(content.graphContentHash),
  ]);
  commitEvents(store, revisionId, driven.events);
  putGraphBody(store, PROJECT_ID, content);
  return driven;
}

function revisionEventCount(store: SqliteEventStore, revisionId: string): number {
  return store.readEvents(graphRevisionAggregateId(PROJECT_ID, revisionId)).length;
}

// --- tests -------------------------------------------------------------------

describe("current active graph projection", () => {
  it("returns the single ACTIVE revision with identity, epoch and decoded content", () => {
    withStore("accept", (store) => {
      const driven = seedActive(store, "graph-revision-1", PRIMARY);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(true);
      if (!read.ok) throw new Error(`unexpected refusal ${read.code}`);

      expect(read.revisionId).toBe("graph-revision-1");
      expect(read.graphEpoch).toBe(driven.state.graphEpoch);
      expect(read.graphEpoch).toBe(1);
      expect(read.planHash).toBe(PLAN_HASH);
      expect(read.graphContentHash).toBe(PRIMARY.graphContentHash);
      expect(read.content).toEqual(PRIMARY.content);
      expect(read.snapshot).toEqual(baseSnapshot());
      expect(read.provenance.aggregateId)
        .toBe(graphRevisionAggregateId(PROJECT_ID, "graph-revision-1"));

      // dec-64b2391c pinned at the consumer: the structural identity is answered
      // beside the content hash and is never equal to it.
      expect(read.snapshotIdentity).toBe(PRIMARY.snapshotIdentity);
      expect(read.snapshotIdentity).not.toBe(read.graphContentHash);

      expect(Object.isFrozen(read)).toBe(true);
    });
  });

  it("refuses with no snapshot authority when no revision is ACTIVE", () => {
    withStore("absent", (store) => {
      // DRAFT only: a real history that simply never reached ACTIVE.
      const driven = drive([createOf("graph-revision-1", PRIMARY.graphContentHash)]);
      commitEvents(store, "graph-revision-1", driven.events);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a non-active project yielded a snapshot");
      expect(read.code).toBe("ACTIVE_GRAPH_ABSENT");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      expect(read.sourceLayer).toBeNull();
      expect(read).not.toHaveProperty("snapshot");
    });
  });

  it("treats an APPROVED revision as NOT active, even with its body stored", () => {
    withStore("approved", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
        approveOnlyOf(PRIMARY.graphContentHash),
      ]);
      // The revision is genuinely APPROVED — one legal step short of ACTIVE — and
      // its body IS present, so nothing else can be the reason for the refusal.
      expect(driven.state.lifecycle).toBe("APPROVED");
      expect(driven.state.graphEpoch).toBe(0);
      commitEvents(store, "graph-revision-1", driven.events);
      putGraphBody(store, PROJECT_ID, PRIMARY);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("an APPROVED revision was served as the active graph");
      expect(read.code).toBe("ACTIVE_GRAPH_ABSENT");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      expect(read.sourceLayer).toBeNull();
    });
  });

  it("refuses split-brain rather than picking a winner between two ACTIVE revisions", () => {
    withStore("split", (store) => {
      seedActive(store, "graph-revision-1", PRIMARY);
      seedActive(store, "graph-revision-9", SUCCESSOR_CONTENT);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("split-brain was resolved instead of refused");
      expect(read.code).toBe("ACTIVE_GRAPH_SPLIT_BRAIN");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      // Distinct from absence: collapsing the two would hide a real split.
      expect(read.code).not.toBe("ACTIVE_GRAPH_ABSENT");
    });
  });

  it("returns only the successor when a SUPERSEDED predecessor precedes it", () => {
    withStore("supersede", (store) => {
      const first = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit, approveAndActivateOf(PRIMARY.graphContentHash),
        supersede,
      ]);
      expect(first.state.lifecycle).toBe("SUPERSEDED");
      commitEvents(store, "graph-revision-1", first.events);
      putGraphBody(store, PROJECT_ID, PRIMARY);

      const second = drive([
        createOf("graph-revision-2", SUCCESSOR_CONTENT.graphContentHash), submit,
        approveAndActivateSuccessorOf(first.state),
      ]);
      commitEvents(store, "graph-revision-2", second.events);
      putGraphBody(store, PROJECT_ID, SUCCESSOR_CONTENT);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(true);
      if (!read.ok) throw new Error(`unexpected refusal ${read.code}`);
      expect(read.revisionId).toBe("graph-revision-2");
      expect(read.graphContentHash).toBe(SUCCESSOR_CONTENT.graphContentHash);
      // The epoch is a BOUND reference carried from the goal, not a local counter.
      expect(read.graphEpoch).toBe(first.state.graphEpoch + 1);
      expect(read.graphEpoch).toBe(2);
    });
  });

  it("surfaces the CORE REPLAY's own code, naming core as the layer that refused", () => {
    withStore("conflict", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit, approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      commitEvents(store, "graph-revision-1", driven.events);
      // One deliberate drift from a GENERATED history: the same version redelivered
      // with different bytes. The core replay owns this rule; the projection must
      // not have an opinion about it.
      const first = driven.events[0];
      if (first === undefined) throw new Error("generated history was empty");
      const drifted = { ...first, goalRef: "goal-DRIFTED" } as unknown as GraphRevisionEvent;
      commitEvents(store, "graph-revision-1", [drifted], "drift");

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a conflicting history still produced a snapshot");
      expect(read.code).toBe("GRAPH_REVISION_REPLAY_IDENTITY_CONFLICT");
      // WHICH layer refused, kept distinct from which layer reported.
      expect(read.sourceLayer).toBe("CORE_GRAPH_REVISION_REPLAY");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
    });
  });

  it("refuses with its own code when the ACTIVE revision's body is missing", () => {
    withStore("no-body", (store) => {
      // Revision seeded WITHOUT its body: the hash names bytes nobody stored.
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit, approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      commitEvents(store, "graph-revision-1", driven.events);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a bodiless revision produced a snapshot");
      expect(read.code).toBe("ACTIVE_GRAPH_BODY_UNAVAILABLE");
      expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      expect(read.sourceLayer).toBe("GRAPH_BODY_RECORD");
      // The underlying cause survives rather than being flattened away.
      expect(read.sourceCode).toBe("GRAPH_BODY_ABSENT");
    });
  });

  it("is byte-stable across consecutive reads and appends nothing", () => {
    withStore("stable", (store) => {
      seedActive(store, "graph-revision-1", PRIMARY);
      const before = revisionEventCount(store, "graph-revision-1");

      const first = readCurrentActiveGraph(store, PROJECT_ID);
      const second = readCurrentActiveGraph(store, PROJECT_ID);

      expect(JSON.stringify(first)).toBe(JSON.stringify(second));
      expect(first).toEqual(second);
      expect(revisionEventCount(store, "graph-revision-1")).toBe(before);
    });
  });

  it("refuses every hostile ordering with its OWN code and refusing layer", () => {
    const legal = drive([
      createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
      approveAndActivateOf(PRIMARY.graphContentHash),
    ]).events;

    /**
     * Each case is ONE deliberate drift from the generated legal history, and
     * each carries the EXACT code and refusing layer it must produce.
     *
     * The previous version of this sweep asserted only `ok === false` plus a
     * layer that `refuse()` hardcodes on every path — a vacuous pair that let a
     * real defect (a create-less history answering ACTIVE_GRAPH_ABSENT, the same
     * answer a clean empty project gives) sit inside a green suite. Carrying the
     * expected code per case is what makes the sweep testable at all.
     */
    const cases: readonly (readonly [
      string, readonly GraphRevisionEvent[], string, string | null,
    ])[] = [
      ["missing create", legal.slice(1),
        "GRAPH_REVISION_REPLAY_MISSING_CREATE", "CORE_GRAPH_REVISION_REPLAY"],
      ["reversed", [...legal].reverse(),
        "GRAPH_REVISION_REPLAY_MISSING_CREATE", "CORE_GRAPH_REVISION_REPLAY"],
      ["activation before submission", [legal[0], legal[2], legal[1]]
        .filter((event): event is GraphRevisionEvent => event !== undefined),
      "GRAPH_REVISION_REPLAY_VERSION_BREAK", "CORE_GRAPH_REVISION_REPLAY"],
    ];

    // A sweep that silently generated zero cases would pass while testing nothing.
    expect(cases.length).toBeGreaterThan(0);
    expect(cases.length).toBe(3);
    expect(new Set(cases.map(([name]) => name)).size).toBe(cases.length);
    // Every case must name a code the projection can actually answer with, and
    // none may be the absent code — that is the collapse this sweep now forbids.
    for (const [, , code] of cases) expect(code).not.toBe("ACTIVE_GRAPH_ABSENT");

    for (const [name, history, code, sourceLayer] of cases) {
      withStore(`hostile-${code}-${history.length}`, (store) => {
        commitEvents(store, "graph-revision-1", history);
        putGraphBody(store, PROJECT_ID, PRIMARY);

        const read = readCurrentActiveGraph(store, PROJECT_ID);
        expect(read.ok, `${name} was accepted`).toBe(false);
        if (read.ok) throw new Error(`${name} produced a snapshot`);
        expect(read.code, `${name} code`).toBe(code);
        // WHICH layer refused, kept distinct from which layer reported. The
        // `layer` field alone is hardcoded by refuse() and proves nothing.
        expect(read.sourceLayer, `${name} sourceLayer`).toBe(sourceLayer);
        expect(read.layer).toBe(ACTIVE_GRAPH_PROJECTION_LAYER);
      });
    }
  });

  it("distinguishes a create-less history from an empty project", () => {
    withStore("no-create", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
        approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      // The submitted+activated events WITHOUT the create that opened them: a
      // genuinely corrupt durable history, not an absent one.
      const withoutCreate = driven.events.filter(
        (event) => event.kind !== "GraphRevisionCreated",
      );
      expect(withoutCreate.length).toBeGreaterThan(0);
      expect(withoutCreate.length).toBe(driven.events.length - 1);
      commitEvents(store, "graph-revision-1", withoutCreate);
      putGraphBody(store, PROJECT_ID, PRIMARY);

      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("a create-less history produced a snapshot");
      // The core replay owns this rule and has a dedicated code for it. Answering
      // ACTIVE_GRAPH_ABSENT here would make a corrupt history indistinguishable
      // from a clean empty project, which is the defect QA measured.
      expect(read.code).toBe("GRAPH_REVISION_REPLAY_MISSING_CREATE");
      expect(read.sourceLayer).toBe("CORE_GRAPH_REVISION_REPLAY");
      expect(read.code).not.toBe("ACTIVE_GRAPH_ABSENT");
    });
  });

  it("answers ABSENT for a genuinely empty project, distinctly", () => {
    withStore("empty", (store) => {
      const read = readCurrentActiveGraph(store, PROJECT_ID);
      expect(read.ok).toBe(false);
      if (read.ok) throw new Error("an empty project produced a snapshot");
      expect(read.code).toBe("ACTIVE_GRAPH_ABSENT");
      expect(read.sourceLayer).toBeNull();
    });
  });

  it("is idempotent under byte-identical redelivery of the whole history", () => {
    withStore("redelivery", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
        approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      commitEvents(store, "graph-revision-1", driven.events);
      putGraphBody(store, PROJECT_ID, PRIMARY);
      const once = readCurrentActiveGraph(store, PROJECT_ID);

      // The SAME events delivered again, byte for byte. DoD 3 requires this to be
      // idempotent, and the core replay owns that rule — it ignores an identical
      // redelivery rather than refusing it, so the projection must still answer.
      commitEvents(store, "graph-revision-1", driven.events, "redeliver");
      const twice = readCurrentActiveGraph(store, PROJECT_ID);

      expect(once.ok).toBe(true);
      expect(twice.ok).toBe(true);
      if (!once.ok || !twice.ok) throw new Error("redelivery broke the read");
      expect(twice).toEqual(once);
      expect(twice.graphEpoch).toBe(once.graphEpoch);
      // The raw events DID double; the projected answer did not move.
      expect(revisionEventCount(store, "graph-revision-1"))
        .toBe(driven.events.length * 2);
    });
  });

  it("declares every refusal code it originates, and no more", () => {
    expect([...ACTIVE_GRAPH_PROJECTION_CODES].sort()).toEqual([
      "ACTIVE_GRAPH_ABSENT",
      "ACTIVE_GRAPH_BODY_UNAVAILABLE",
      "ACTIVE_GRAPH_SPLIT_BRAIN",
    ]);
  });
});
