/**
 * Inputs only, for the `graph.get` suites.
 *
 * Nothing here re-implements a boundary rule. Every history is GENERATED by
 * driving the real `reduceGraphRevision` and committing the events it actually
 * emitted, exactly as `active-graph-projection.test.ts` does and for the same
 * reason: nothing writes graph-revision events in production yet, so a
 * hand-authored event shape would let the query handler pass against events
 * production will never produce. The command INPUT is restated here — `@moe/core`'s
 * revision fixtures are test-only and unreachable from its root — but every event,
 * every state and every lifecycle rule still comes from the production reducer.
 *
 * No `expect` and no assertion lives in this module: the test files run their
 * assertions against production functions, and a fixture that judged an outcome
 * would be a second authority beside the one under test.
 *
 * WINDOWS HANDLE DISCIPLINE: `withStore` closes the store in a `finally` inside
 * the temp directory's own `finally`. A handle held across `rmSync` throws EPERM
 * and kills the vitest worker with no output at all.
 */

import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  createAcceptanceContract, createPlanRevision, reduceGraphRevision,
} from "@moe/core";
import type {
  GraphRevisionCommand,
  GraphRevisionEvent,
  GraphRevisionState,
} from "@moe/core";
import {
  ADMISSION_PURPOSES,
  createNodeDefinition,
  deriveNodeAuthoritySet,
  encodeGraphContent,
  snapshotIdentityHash,
  validateGraphSnapshot,
} from "@moe/scheduler";
import type {
  GraphContent,
  GraphEdge,
  GraphNode,
  GraphRevisionContent,
  GraphSnapshot,
  NodeAuthoritySection,
  NodeDefinition,
} from "@moe/scheduler";
import { RECOVERY_BINDING_CODEC_VERSION, SqliteEventStore } from "@moe/store";

import { WIRE_PROTOCOL_VERSION } from "../http/http-contract.js";
import type {
  AuthenticatedPrincipal,
  Authenticator,
  CommandAdapterDeps,
} from "../http/http-contract.js";
import { decisionPort, recordingHandler, registryOf } from "../http/http-test-fixtures.js";
import { streamPort } from "../http/event-stream-fixtures.js";
import { createSessionAuthenticator } from "../identity/session-authenticator.js";
import { createMcpDispatchPort } from "../mcp-dispatch-port.js";
import type { HttpDispatchPort } from "@moe/mcp";
import {
  graphRevisionAggregateId,
  readCurrentActiveGraph,
} from "./active-graph-projection.js";
import type { ActiveGraphResult } from "./active-graph-projection.js";
import { putGraphBody } from "./graph-body-record.js";
import { answerGraphQuery } from "./graph-query.js";
import type { GraphQueryPort, GraphQueryResult } from "./graph-query.js";

export const PROJECT_ID = "proj-graph-query-0001";
export const PRINCIPAL_ID = "principal-planner-1";
export const PLANNING_CAPABILITY = "planning.write";
export const GOOD_CREDENTIAL = "credential-good";
export const CSRF = "csrf-token-for-graph-query";
export const ENCODER = new TextEncoder();
export const DECODER = new TextDecoder();

// --- content fixtures --------------------------------------------------------

export function baseSnapshot(): GraphSnapshot {
  const nodes: readonly GraphNode[] = [
    { nodeKey: "dev-a", executionBearing: true },
    { nodeKey: "dev-b", executionBearing: true },
    { nodeKey: "dev-c", executionBearing: true },
  ];
  const edges: readonly GraphEdge[] = [
    { edgeKey: "dev-e1", producerNodeKey: "dev-a", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e2", producerNodeKey: "dev-b", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e3", producerNodeKey: "dev-a", consumerNodeKey: "dev-b", kind: "ADVISORY" },
  ];
  return { nodes, edges, completionNodeKey: "dev-c" };
}

// --- v3 node-authority fixtures (task-8c7e6ce4) ------------------------------

/**
 * `GraphRevisionContent` v3 (task-6ba1ff89) makes `nodeAuthority` MANDATORY, and
 * `encodeGraphContent` RE-DERIVES the set it is handed rather than adopting it
 * (`graph-content.ts:120-141`), so a hand-built section can never pass. Everything below
 * COMPOSES the published producers — `createPlanRevision` / `createAcceptanceContract`
 * (@moe/core), then `createNodeDefinition` and `deriveNodeAuthoritySet` (@moe/scheduler) —
 * and judges nothing: each helper hands back what production returned, or throws carrying
 * production's own code, so a fixture that stopped building is never mistaken for a
 * boundary that stopped refusing.
 */
const AUTHORITY_HEX = (digit: string): string => digit.repeat(64);

const planDraftFor = (nodeKeys: readonly string[]): Record<string, unknown> => ({
  affectedCriterionIds: ["criterion-a"],
  affectedNodeIds: [...nodeKeys],
  approvalState: "APPROVED",
  authorRef: "principal-a",
  graphBinding: { graphContentHash: AUTHORITY_HEX("a"), graphRevisionRef: "graph-revision-a" },
  parentRevisionId: null,
  rejectionRef: null,
  revisionId: "plan-revision-a",
  steps: [{ description: "Land the node.", kind: "IMPLEMENTATION", stepId: "step-a" }],
  verificationRecipeRefs: ["recipe-a"],
});

const acceptanceDraftFor = (nodeKeys: readonly string[]): Record<string, unknown> => ({
  applicability: {
    graphContentHash: AUTHORITY_HEX("a"), graphRevisionRef: "graph-revision-a",
    nodeIds: [...nodeKeys], nodeKind: "LEAF",
  },
  authorRef: "principal-a",
  contractId: "acceptance-contract-a",
  obligations: [{
    criterionId: "criterion-a",
    evidenceRequirements: [
      { evidenceRef: "artifact-a", kind: "ARTIFACT", requirementId: "requirement-a" },
    ],
    statement: "The node ships its focused verification.",
    verificationRecipeRefs: ["recipe-a"],
  }],
});

/** A MONOTONIC contract owes a matching registry proof, else the codec refuses
 *  NODE_AUTHORITY_MONOTONIC_PROOF_MISSING @ NODE_AUTHORITY_PROOFS. */
const AUTHORITY_REGISTRY_ENTRY: Record<string, unknown> = {
  parameterSchema: { digest: AUTHORITY_HEX("b"), kind: "JSON_SCHEMA" },
  predicateRef: "predicate-a",
  proofRationale: "An artifact seal cannot become unsealed.",
  schemaId: "schema-a",
  schemaVersion: 1,
  sourceOperationClass: "ARTIFACT_SEAL",
};

/** ONE contract per HARD edge ENTERING a node. `graphBindingDigest` is PRODUCTION's
 *  `snapshotIdentityHash` over the ACCEPTED graph, never a literal: a digest that did not
 *  come from this structure refuses NODE_AUTHORITY_RECURSION_BINDING_MISMATCH at derive
 *  time (`node-authority-recursion.ts:164-167`). */
const hardEdgeRequirement = (edge: GraphEdge, binding: string): Record<string, unknown> => ({
  edgeKey: edge.edgeKey,
  requirement: {
    contract: {
      alternateProducers: [] as string[],
      alternativeRuling: { kind: "NOT_APPLICABLE", reason: "No alternate producer exists." },
      consumer: {
        contractHash: AUTHORITY_HEX("c"), criterionRef: "criterion-a", kind: "PRECONDITION",
      },
      consumerNodeKey: edge.consumerNodeKey,
      consumptionHorizon: "RESULT_SEAL",
      edgeKind: "ARTIFACT_CONSUMPTION",
      graphBindingDigest: binding,
      invalidationFacts: [
        { sourceFactDigest: AUTHORITY_HEX("e"), sourceFactRef: "fact-a", sourceFactVersion: 1 },
      ],
      minimumQualifyingMilestone: "RESULT_SEALED",
      necessity: {
        failedConsumerCriterionRef: "criterion-a", failureKind: "MISSING_ARTIFACT",
        truthClass: "OBSERVED",
      },
      producer: {
        artifactOrInterfaceRef: "artifact-a", digest: AUTHORITY_HEX("f"),
        kind: "ARTIFACT_CONSUMPTION",
      },
      producerNodeKey: edge.producerNodeKey,
      recheckPredicateRef: "predicate-a",
      satisfactionPredicate: {
        parametersDigest: AUTHORITY_HEX("1"), predicateRef: "predicate-a",
        schemaId: "schema-a", schemaVersion: 1,
      },
      satisfactionWitnesses: [{
        sourceOperationClass: "ARTIFACT_SEAL", witnessDigest: AUTHORITY_HEX("2"),
        witnessRef: "witness-a", witnessVersion: 1,
      }],
      stability: "MONOTONIC",
      truthClass: "OBSERVED",
    },
    edgeKind: "ARTIFACT_CONSUMPTION",
  },
});

/** Admitted by PRODUCTION or not built at all: a body the codec refuses could never reach
 *  the encode this fixture exists to feed. */
function nodeDefinitionFor(
  nodeKey: string, snapshot: GraphSnapshot, binding: string,
): NodeDefinition {
  const nodeKeys = snapshot.nodes.map((node) => node.nodeKey);
  const plan = createPlanRevision(planDraftFor(nodeKeys));
  if (!plan.ok) throw new Error(`plan revision fixture refused: ${plan.code}`);
  const acceptance = createAcceptanceContract(acceptanceDraftFor(nodeKeys));
  if (!acceptance.ok) throw new Error(`acceptance fixture refused: ${acceptance.code}`);
  const completes = nodeKey === snapshot.completionNodeKey;
  const built = createNodeDefinition({
    acceptanceContract: acceptance.contract,
    draft: {
      admissionAmounts: [...ADMISSION_PURPOSES].sort().map((purpose, index) => ({
        meter: "runner.authorized_ms", purpose, quantity: index + 1,
      })),
      admissionGatePolicy: "POLICY_ALLOWANCE",
      capability: "capability-implement",
      completionLinkage: completes ? nodeKey : null,
      constraints: ["constraint-a"],
      directHardDependencies: snapshot.edges
        .filter((edge) => edge.kind === "HARD" && edge.consumerNodeKey === nodeKey)
        .map((edge) => hardEdgeRequirement(edge, binding)),
      joinRole: completes ? "COMPLETION" : "NONE",
      nodeKey,
      objective: `Land ${nodeKey}.`,
      policySliceHash: AUTHORITY_HEX("3"),
      readScopes: ["services/api/src"],
      repositoryBaseTree: AUTHORITY_HEX("4"),
      resources: ["resource-a"],
      verificationRecipeRevisions: ["recipe-a"],
      writeScopes: ["services/api/src/node"],
    },
    planRevision: plan.revision,
    predicateRegistry: [AUTHORITY_REGISTRY_ENTRY],
  });
  if (!built.ok) {
    throw new Error(built.issues.map((issue) => `${issue.code}@${issue.layer}`).join(","));
  }
  return built.value.definition;
}

/**
 * The authenticated half of a v3 record. `definitions` is sorted by `nodeKey` because
 * `readAuthoritySection` requires the two arrays index-aligned and STRICTLY ASCENDING
 * (`graph-content-fields.ts:121-147`), and `deriveNodeAuthoritySet` already returns its
 * entries in that order. `authorities` is the PRODUCER'S own value, never a rebuilt one:
 * `bindAuthority` re-derives and refuses GRAPH_CONTENT_AUTHORITY_DISAGREEMENT on any
 * stated set that is not the derived one.
 */
export function authoritySectionFor(snapshot: GraphSnapshot): NodeAuthoritySection {
  const validated = validateGraphSnapshot(snapshot);
  if (!validated.ok) {
    throw new Error(`graph fixture refused: ${validated.issues[0]?.code ?? "?"}`);
  }
  const binding = snapshotIdentityHash(validated.graph);
  const definitions = snapshot.nodes
    .map((node) => node.nodeKey)
    .slice()
    .sort()
    .map((nodeKey) => nodeDefinitionFor(nodeKey, snapshot, binding));
  const derived = deriveNodeAuthoritySet(snapshot, definitions);
  if (!derived.ok) {
    throw new Error(derived.issues.map((issue) => `${issue.code}@${issue.layer}`).join(","));
  }
  return { authorities: derived.value, definitions };
}

export function encoded(author: string): GraphContent {
  const snapshot = baseSnapshot();
  const content: GraphRevisionContent = {
    author,
    completionNode: "dev-c",
    decompositionBudget: 24,
    nodeAuthority: authoritySectionFor(snapshot),
    parentRevision: "rev-000000000000",
    policyRevision: "pol-000000000001",
    repositoryBaseTree: "4".repeat(40),
    snapshot,
  };
  const result = encodeGraphContent(content);
  if (!result.ok) throw new Error(`fixture failed to encode: ${JSON.stringify(result.issues)}`);
  return result.value;
}

export const PRIMARY = encoded("human:architect-primary");
export const SECONDARY = encoded("human:architect-successor");

// --- reducer command fixtures (input only; the reducer owns every rule) -------

export function seededHash(seed: string): string {
  return seed.repeat(64).slice(0, 64);
}

export const PLAN_HASH = seededHash("11");

export function bindingOf(graphHash: string) {
  return {
    budgetHash: seededHash("55"),
    expectedGoalVersion: 3,
    graphHash,
    policyHash: seededHash("66"),
    qualityHash: seededHash("33"),
  } as const;
}

export type Step = (current: GraphRevisionState | undefined) => GraphRevisionCommand;

export function versionOf(current: GraphRevisionState | undefined): number {
  return current === undefined ? 0 : current.version;
}

export function createOf(revisionId: string, graphContentHash: string): Step {
  return () => ({
    commandId: `cmd-create-${revisionId}`, expectedVersion: 0, goalRef: "goal-1",
    graphContentHash, kind: "graph_revision.create", planHash: PLAN_HASH, revisionId,
  }) as GraphRevisionCommand;
}

export const submit: Step = (current) => ({
  commandId: "cmd-submit", expectedVersion: versionOf(current),
  kind: "graph_revision.submit",
  witness: { submissionRef: "submission-1", truthClass: "DAEMON_VERIFIED" },
}) as GraphRevisionCommand;

export function approveAndActivateOf(graphHash: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    activation: {
      ...binding, activationRef: "activation-1", graphEpoch: 1, truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: "approval-1", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

// --- store harness -----------------------------------------------------------

export function installBinding(
  store: SqliteEventStore,
  incarnationRef = "81".repeat(32),
  keyEpochRef = "82".repeat(32),
): void {
  const installed = store.installRecoveryBinding({
    bindingCodecVersion: RECOVERY_BINDING_CODEC_VERSION,
    incarnationRef,
    installedAt: "2026-08-18T00:00:00.000Z",
    keyEpochRef,
    payload: ENCODER.encode("graph-query-recovery-binding"),
    slot: "ACTIVE",
  });
  if (!installed.ok) throw new Error(`recovery binding setup failed: ${installed.code}`);
}

export function withStore<T>(
  name: string,
  run: (store: SqliteEventStore, storePath: string) => T,
): T {
  const directory = mkdtempSync(join(tmpdir(), `moe-graph-query-${name}-`));
  const storePath = join(directory, "store.sqlite");
  try {
    const store = SqliteEventStore.openForProject(storePath, PROJECT_ID);
    try {
      installBinding(store);
      return run(store, storePath);
    } finally {
      store.close();
    }
  } finally {
    rmSync(directory, { force: true, maxRetries: 5, recursive: true });
  }
}

/** Drives the REAL reducer and returns the events it actually emitted. */
export function drive(
  steps: readonly Step[],
): { events: GraphRevisionEvent[]; state: GraphRevisionState } {
  let current: GraphRevisionState | undefined;
  const events: GraphRevisionEvent[] = [];
  for (const step of steps) {
    const result = reduceGraphRevision(current, step(current));
    if (!result.ok) throw new Error(`fixture command rejected: ${result.error.code}`);
    current = result.state;
    events.push(...result.events);
  }
  if (current === undefined) throw new Error("path produced no state");
  return { events, state: current };
}

/** The whole ACTIVE path, driven through the reducer, for one revision id. */
export function activePathFor(
  revisionId: string,
  content: GraphContent,
): readonly GraphRevisionEvent[] {
  return drive([
    createOf(revisionId, content.graphContentHash), submit,
    approveAndActivateOf(content.graphContentHash),
  ]).events;
}

export function commitEvents(
  store: SqliteEventStore,
  revisionId: string,
  events: readonly GraphRevisionEvent[],
  commandId = `seed-${revisionId}`,
): void {
  const aggregateId = graphRevisionAggregateId(PROJECT_ID, revisionId);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(commandId),
    commandId,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: events.map((event, index) => ({
      eventId: `${commandId}-${index}`,
      eventType: event.kind,
      payload: ENCODER.encode(JSON.stringify(event)),
    })),
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** Commit reducer-produced revision events through the real decision ledger. */
export function commitDecisionEvents(
  store: SqliteEventStore,
  revisionId: string,
  events: readonly GraphRevisionEvent[],
): void {
  const aggregateId = graphRevisionAggregateId(PROJECT_ID, revisionId);
  const groups = new Map<string, GraphRevisionEvent[]>();
  for (const event of events) {
    const group = groups.get(event.commandId) ?? [];
    group.push(event);
    groups.set(event.commandId, group);
  }
  for (const [commandId, group] of groups) {
    const commandKind = group[0]?.kind === "GraphRevisionCreated"
      ? "graph_revision.create"
      : group[0]?.kind === "GraphRevisionSubmitted" ? "graph_revision.submit" : "graph.approve";
    store.commitExpectedVersionDecision({
      commandKind,
      committedResultBytes: ENCODER.encode(JSON.stringify(group)),
      correlationId: `corr-${commandId}`,
      decidedAt: "2026-08-18T00:00:00.000Z",
      events: group.map((event, index) => ({
        eventId: `decision-${commandId}-${index}`,
        eventType: event.kind,
        payload: ENCODER.encode(JSON.stringify(event)),
      })),
      expectedVersion: store.getAggregateVersion(aggregateId),
      key: { commandId, principalId: PRINCIPAL_ID, projectId: PROJECT_ID },
      requestBytes: ENCODER.encode(JSON.stringify({ commandId })),
      targetAggregateId: aggregateId,
    });
  }
}

/** Seed a whole ACTIVE revision through the durable decision writer. */
export function seedDecisionActive(store: SqliteEventStore, revisionId = "graph-revision-1"): void {
  commitDecisionEvents(store, revisionId, activePathFor(revisionId, PRIMARY));
  putGraphBody(store, PROJECT_ID, PRIMARY);
}

/** Seed a revision AND the body its content hash names — the normal, whole path. */
export function seedActive(
  store: SqliteEventStore,
  revisionId = "graph-revision-1",
  content: GraphContent = PRIMARY,
): void {
  commitEvents(store, revisionId, activePathFor(revisionId, content));
  putGraphBody(store, PROJECT_ID, content);
}

/** The revision events WITHOUT the body their content hash names. */
export function seedActiveWithoutBody(
  store: SqliteEventStore,
  revisionId = "graph-revision-1",
): void {
  commitEvents(store, revisionId, activePathFor(revisionId, PRIMARY));
}

export function eventCount(store: SqliteEventStore): number {
  return store.readEventsAfter(0n, 1_000).items.length;
}

export function decisionCount(store: SqliteEventStore): number {
  return store.readCommandDecisionsAfter(0n, 1_000).items.length;
}

// --- authentication harness --------------------------------------------------

export function principalFor(
  projectId: string,
  capabilities: readonly string[] = [PLANNING_CAPABILITY],
): AuthenticatedPrincipal {
  return { capabilities, principalId: PRINCIPAL_ID, projectId };
}

/** The real durable-ledger authenticator; only its operator configuration varies. */
export function authenticatorFor(
  store: SqliteEventStore,
  principal: AuthenticatedPrincipal | null,
): Authenticator {
  const configured = principal ?? principalFor(PROJECT_ID);
  return createSessionAuthenticator(store, {
    clock: () => Date.parse("2026-08-18T00:00:00.000Z"),
    operatorCapabilities: configured.capabilities,
    operatorCredential: principal === null ? "credential-disabled" : GOOD_CREDENTIAL,
    operatorPrincipalId: configured.principalId,
    projectId: configured.projectId,
  });
}

export interface CountingPort extends GraphQueryPort {
  readonly reads: () => number;
}

/**
 * Counts reader invocations so "refused BEFORE the reader ran" is MEASURED. A
 * handler that read first and refused afterwards would leak the existence and
 * shape of another project's graph while still returning a refusal, and no
 * assertion on the returned value can see the difference.
 */
export function countingPort(store: SqliteEventStore, boundProjectId = PROJECT_ID): CountingPort {
  let reads = 0;
  return {
    boundProjectId,
    readCurrentActiveGraph: (projectId: string): ActiveGraphResult => {
      reads += 1;
      return readCurrentActiveGraph(store, projectId);
    },
    reads: () => reads,
  };
}

export interface QueryOptions {
  readonly body?: unknown;
  readonly capabilities?: readonly string[];
  readonly credential?: string | null;
  readonly port?: GraphQueryPort;
  readonly principalProject?: string;
  readonly protocolVersion?: unknown;
}

export function ask(store: SqliteEventStore, options: QueryOptions = {}): GraphQueryResult {
  const principal = principalFor(
    options.principalProject ?? PROJECT_ID,
    options.capabilities ?? [PLANNING_CAPABILITY],
  );
  return answerGraphQuery({
    authenticator: authenticatorFor(store, principal),
    body: options.body ?? {},
    credential: options.credential === undefined ? GOOD_CREDENTIAL : options.credential,
    port: options.port ?? countingPort(store),
    protocolVersion: options.protocolVersion ?? WIRE_PROTOCOL_VERSION,
  });
}

// --- MCP transport harness ---------------------------------------------------

export function depsFor(
  store: SqliteEventStore,
  principal: AuthenticatedPrincipal | null,
): CommandAdapterDeps {
  return {
    authenticator: authenticatorFor(store, principal),
    decisions: decisionPort(),
    registry: registryOf("goal.create", recordingHandler().handler, ["title"]),
  };
}

export interface McpOptions {
  readonly credential?: string | null;
  readonly payload?: unknown;
}

/** Drives the REAL MCP dispatch port and returns the RAW answered bytes. */
export function overMcpBytes(
  store: SqliteEventStore,
  port: GraphQueryPort | undefined,
  options: McpOptions = {},
  principal: AuthenticatedPrincipal | null = principalFor(PROJECT_ID),
): Uint8Array {
  const dispatch = createMcpDispatchPort({
    deps: depsFor(store, principal),
    ...(port === undefined ? {} : { graph: port }),
    subscriptions: streamPort(),
  });
  const envelope = ENCODER.encode(JSON.stringify({
    payload: options.payload ?? {}, queryKind: "graph.get",
  }));
  const credential = options.credential === undefined ? GOOD_CREDENTIAL : options.credential;
  // HELD AS THE HTTP BRIDGE HOLDS IT. `createMcpDispatchPort` is declared to
  // return `StdioDispatchPort`, whose `dispatchQueryBytes(bytes)` takes no
  // context — the stdio server calls it that way and falls back to the process
  // credential. The HTTP MCP bridge holds the same value as an
  // `HttpDispatchPort` and passes a context (http-tool-bridge.ts:156), which is
  // the production path a per-request bearer travels. Driving it through the
  // one-argument type would have tested the fallback and never the context.
  const bridge = dispatch as unknown as HttpDispatchPort;
  const answered = credential === null
    ? (bridge.dispatchQueryBytes as (bytes: Uint8Array) => Uint8Array)(envelope)
    : bridge.dispatchQueryBytes(envelope, { credential });
  if (answered instanceof Promise) throw new Error("the query dispatch answered asynchronously");
  return answered;
}

export function overMcp(
  store: SqliteEventStore,
  port: GraphQueryPort | undefined,
  options: McpOptions = {},
  principal: AuthenticatedPrincipal | null = principalFor(PROJECT_ID),
): Record<string, unknown> {
  return JSON.parse(DECODER.decode(overMcpBytes(store, port, options, principal))) as
    Record<string, unknown>;
}
