/**
 * `graph.get`, answered through the production authentication gate over a REAL
 * file-backed SqliteEventStore and a REAL `Authenticator`.
 *
 * EVERY history here is GENERATED by driving the real `reduceGraphRevision` and
 * committing the events it actually emitted, exactly as
 * `active-graph-projection.test.ts` does and for the same reason: nothing writes
 * graph-revision events in production yet, so a hand-authored event shape would
 * let this handler pass against events production will never produce. The
 * command INPUT is restated here — `@moe/core`'s revision fixtures are test-only
 * and unreachable from its root — but every event, every state and every
 * lifecycle rule still comes from the production reducer.
 *
 * THE DEFINING ASSERTION OF THIS SUITE is that `graphContentHash` and
 * `snapshotIdentity` arrive as two separate fields with two different values
 * (decision dec-64b2391c). They are both 64-char hex and they sit next to each
 * other, so a handler that assigns one from the other typechecks, reads as
 * tidy, and silently binds a durable revision to an identity that omits six of
 * the seven content fields. Both are compared against the READER's own answer
 * rather than against transcribed hex: a test holding both operands would agree
 * with itself no matter what the handler did.
 *
 * WINDOWS HANDLE DISCIPLINE: the store closes in a `finally` inside the temp
 * directory's own `finally`. A handle held across `rmSync` throws EPERM and
 * kills the vitest worker with no output at all.
 */

import { mkdtempSync, rmSync } from "node:fs";
import { request as httpRequest } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";

import type { GraphRevisionEvent } from "@moe/core";
import { SqliteEventStore } from "@moe/store";
import { describe, expect, it } from "vitest";

import { startControlRoomListener } from "../http/http-listener.js";
import type { ControlRoomListener } from "../http/http-listener.js";
import { WIRE_PROTOCOL_VERSION } from "../http/http-contract.js";
import type { AuthenticatedPrincipal } from "../http/http-contract.js";
import { createSessionAuthenticator } from "../identity/session-authenticator.js";
import {
  CREDENTIAL as REPLAY_CREDENTIAL,
  EXPIRES_AT_MS as REPLAY_EXPIRES_AT_MS,
  PROJECT_ID as REPLAY_PROJECT_ID,
  openDefaultSession,
} from "../identity/session-test-fixtures.js";
import {
  graphRevisionAggregateId,
  readCurrentActiveGraph,
} from "./active-graph-projection.js";
import type { ActiveGraphResult } from "./active-graph-projection.js";
import { answerGraphQuery } from "./graph-query.js";
import type { GraphQueryCode, GraphQueryPort, GraphQueryResult } from "./graph-query.js";
import {
  CSRF,
  DECODER,
  ENCODER,
  GOOD_CREDENTIAL,
  PRIMARY,
  PROJECT_ID,
  SECONDARY,
  approveAndActivateOf,
  ask,
  authenticatorFor,
  commitEvents,
  countingPort,
  createOf,
  decisionCount,
  depsFor,
  drive,
  eventCount,
  installBinding,
  overMcp,
  overMcpBytes,
  principalFor,
  seedActive,
  seedActiveWithoutBody,
  submit,
  withStore,
} from "./graph-query-test-fixtures.js";

// --- 1. the accepted control -------------------------------------------------

describe("graph.get accepted answer", () => {
  it("answers with the reader's exact snapshot, revision, epoch and both identities", () => {
    withStore("accept", (store) => {
      seedActive(store);
      const reader = readCurrentActiveGraph(store, PROJECT_ID);
      expect(reader.ok).toBe(true);
      if (!reader.ok) throw new Error(`fixture did not reach ACTIVE: ${reader.code}`);

      const events = eventCount(store);
      const decisions = decisionCount(store);
      const answer = ask(store);

      expect(answer.ok).toBe(true);
      if (!answer.ok) throw new Error(`unexpected refusal ${JSON.stringify(answer)}`);
      expect(answer.revisionId).toBe(reader.revisionId);
      expect(answer.graphEpoch).toBe(reader.graphEpoch);
      expect(answer.planHash).toBe(reader.planHash);
      expect(answer.snapshot).toEqual(reader.snapshot);
      expect(answer.provenance).toEqual(reader.provenance);
      expect(Object.isFrozen(answer)).toBe(true);
      expect(Object.isFrozen(answer.provenance)).toBe(true);

      // A QUERY WRITES NOTHING, measured from the store rather than inferred
      // from a return value that has no way to report a write.
      expect(eventCount(store)).toBe(events);
      expect(decisionCount(store)).toBe(decisions);
    });
  });

  it("carries graphContentHash and snapshotIdentity as two DIFFERENT fields", () => {
    withStore("anti-equation", (store) => {
      seedActive(store);
      const reader = readCurrentActiveGraph(store, PROJECT_ID);
      if (!reader.ok) throw new Error(`fixture did not reach ACTIVE: ${reader.code}`);

      // Self-guard: if the seeded revision's two values were equal, every
      // assertion below would hold for a handler that equated them.
      expect(reader.graphContentHash).not.toBe(reader.snapshotIdentity);

      const answer = ask(store);
      if (!answer.ok) throw new Error(`unexpected refusal ${JSON.stringify(answer)}`);

      // Each bound to the READER's own field, not to transcribed hex — a test
      // holding both operands would agree with itself whatever the handler did.
      expect(answer.graphContentHash).toBe(reader.graphContentHash);
      expect(answer.snapshotIdentity).toBe(reader.snapshotIdentity);
      // dec-64b2391c: content provenance covers all seven content fields, the
      // structural identity covers the snapshot alone. Equating them binds a
      // durable revision to an identity omitting six of them.
      expect(answer.graphContentHash).not.toBe(answer.snapshotIdentity);
      // Both are 64-char hex, which is exactly why a cross-assignment is
      // invisible to the type checker and to any shape-only assertion.
      expect(answer.graphContentHash).toMatch(/^[0-9a-f]{64}$/u);
      expect(answer.snapshotIdentity).toMatch(/^[0-9a-f]{64}$/u);
    });
  });

  it("names its own layer on a refusal it originates", () => {
    withStore("layer", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const refusal = refusalOf(ask(store, { capabilities: [], port }));
      expect(refusal.layer).toBe("GRAPH_QUERY");
      expect(refusal.code).toBe("GRAPH_QUERY_CAPABILITY_DENIED");
      // The reader must not have run: authority is refused before any read.
      expect(port.reads()).toBe(0);
    });
  });
});

// --- 2. the authentication and spoofing matrix -------------------------------

interface Refused {
  readonly code?: unknown;
  /** The runtime error a SEAM refusal carries; the stage alone does not name a reason. */
  readonly error?: Readonly<{ readonly code?: unknown }>;
  readonly httpStatus?: unknown;
  readonly layer?: unknown;
  readonly outcome?: unknown;
  readonly refusal?: Readonly<{ readonly code?: unknown; readonly layer?: unknown }>;
  readonly stage?: unknown;
}

function refusalOf(answer: GraphQueryResult): Refused {
  expect(answer.ok).toBe(false);
  if (answer.ok) throw new Error("an accepted answer was returned where a refusal was required");
  // No authority may ride along on a refusal, whichever layer produced it.
  expect(answer).not.toHaveProperty("snapshot");
  expect(answer).not.toHaveProperty("revisionId");
  expect(answer).not.toHaveProperty("graphContentHash");
  expect(answer).not.toHaveProperty("snapshotIdentity");
  return answer as unknown as Refused;
}

describe("graph.get authentication and project authority", () => {
  it("keeps the AUTHENTICATE stage for an absent credential, without reading", () => {
    withStore("no-credential", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const refusal = refusalOf(ask(store, { credential: null, port }));
      // THE CODE, not just the stage. Two different rules refuse at
      // AUTHENTICATE — an unusable credential and a port that answered REFUSED —
      // and a stage-only assertion cannot tell them apart, so it would stay
      // green if the seam started answering with the wrong one.
      expect(refusal.stage).toBe("AUTHENTICATE");
      expect(refusal.outcome).toBe("REFUSED");
      expect(refusal.error?.code).toBe("AUTHENTICATION_FAILED");
      expect(refusal.httpStatus).toBe(401);
      expect(port.reads()).toBe(0);
    });
  });

  it("keeps the port's OWN refusal for a rejected credential, without reading", () => {
    const directory = mkdtempSync(join(tmpdir(), "moe-graph-query-replayed-"));
    try {
      const store = SqliteEventStore.openForProject(
        join(directory, "store.sqlite"), REPLAY_PROJECT_ID,
      );
      try {
        installBinding(store, "41".repeat(32), "51".repeat(32));
        openDefaultSession(store);
        installBinding(store, "42".repeat(32), "52".repeat(32));
        const authenticator = createSessionAuthenticator(store, {
          clock: () => REPLAY_EXPIRES_AT_MS - 1_000,
          operatorCapabilities: [],
          operatorCredential: "operator-not-used",
          operatorPrincipalId: "principal-not-used",
          projectId: REPLAY_PROJECT_ID,
        });
        const port = countingPort(store, REPLAY_PROJECT_ID);
        const refusal = refusalOf(answerGraphQuery({
          authenticator,
          body: {},
          credential: REPLAY_CREDENTIAL,
          port,
          protocolVersion: WIRE_PROTOCOL_VERSION,
        }));
        expect(refusal.stage).toBe("AUTHENTICATE");
        // PORT_REFUSED, not REFUSED: the authenticator answered and its refusal
        // travels verbatim. Asserting only "refused" would pass if the adapter
        // replaced the port's answer with its own generic one.
        expect(refusal.outcome).toBe("PORT_REFUSED");
        expect(refusal.httpStatus).toBe(401);
        expect(refusal.refusal?.code).toBe("SESSION_REPLAYED");
        expect(refusal.refusal?.layer).toBe("IDENTITY");
        expect(port.reads()).toBe(0);
      } finally {
        store.close();
      }
    } finally {
      rmSync(directory, { force: true, maxRetries: 5, recursive: true });
    }
  });

  it("refuses a wrong protocol version at COMPATIBILITY, a distinct stage", () => {
    withStore("wrong-protocol", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const refusal = refusalOf(ask(store, { port, protocolVersion: "0.0.0-not-ours" }));
      expect(refusal.stage).toBe("COMPATIBILITY");
      expect(refusal.stage).not.toBe("AUTHENTICATE");
      // The compatibility gate's OWN code. Without it this arm would pass on any
      // refusal that happened to be tagged COMPATIBILITY.
      expect(refusal.outcome).toBe("REFUSED");
      expect(refusal.error?.code).toBe("DISTRIBUTION_MISMATCH");
      expect(refusal.error?.code).not.toBe("AUTHENTICATION_FAILED");
      expect(port.reads()).toBe(0);
    });
  });

  it("refuses a principal without the planning capability, without reading", () => {
    withStore("no-capability", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const refusal = refusalOf(ask(store, { capabilities: ["work.write"], port }));
      expect(refusal.code).toBe("GRAPH_QUERY_CAPABILITY_DENIED");
      expect(refusal.layer).toBe("GRAPH_QUERY");
      expect(port.reads()).toBe(0);
    });
  });

  it("refuses a body naming a project other than the principal's, without reading", () => {
    withStore("spoof-body", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const refusal = refusalOf(ask(store, { body: { projectId: "proj-somebody-else" }, port }));
      expect(refusal.code).toBe("GRAPH_QUERY_PROJECT_MISMATCH");
      expect(refusal.layer).toBe("GRAPH_QUERY");
      // THE ASSERTION THAT PROVES NO CALLER-SELECTED AUTHORITY EXISTS: a handler
      // that read first and refused afterwards would still return this refusal.
      expect(port.reads()).toBe(0);
    });
  });

  it("accepts a body naming the principal's OWN project", () => {
    withStore("own-project", (store) => {
      seedActive(store);
      const answer = ask(store, { body: { projectId: PROJECT_ID } });
      // The positive half of the spoofing rule: without it, a handler that
      // refused EVERY body naming a project would pass the case above for the
      // wrong reason.
      expect(answer.ok).toBe(true);
    });
  });

  it("refuses a principal bound to another project than this daemon, without reading", () => {
    withStore("wrong-bound", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const refusal = refusalOf(ask(store, { port, principalProject: "proj-another-daemon" }));
      expect(refusal.code).toBe("GRAPH_QUERY_PROJECT_MISMATCH");
      // WHICH layer refused, not only that something did: the reader has its own
      // project-shaped refusals, and an assertion blind to the layer would stay
      // green if this check moved below the read.
      expect(refusal.layer).toBe("GRAPH_QUERY");
      expect(port.reads()).toBe(0);
    });
  });

  it("refuses when the daemon was composed without a graph port", () => {
    withStore("unavailable", (store) => {
      seedActive(store);
      const refusal = refusalOf(answerGraphQuery({
        authenticator: authenticatorFor(store, principalFor(PROJECT_ID)),
        body: {},
        credential: GOOD_CREDENTIAL,
        port: undefined,
        protocolVersion: WIRE_PROTOCOL_VERSION,
      }));
      // Its own code, not a flat INPUT_INVALID: "this daemon has no graph
      // support" and "your request was bad" are different facts.
      expect(refusal.code).toBe("GRAPH_QUERY_UNAVAILABLE");
      expect(refusal.layer).toBe("GRAPH_QUERY");
    });
  });
});

// --- 3. the generated hostile body sweep -------------------------------------

const POLLUTED = JSON.parse('{"__proto__":{"projectId":"proj-injected"}}') as unknown;

const HOSTILE_BODIES: readonly (readonly [string, () => unknown, GraphQueryCode])[] = [
  ["a string body", () => "not-an-object", "GRAPH_QUERY_REQUEST_INVALID"],
  ["a numeric body", () => 42, "GRAPH_QUERY_REQUEST_INVALID"],
  ["an array body", () => [{ projectId: PROJECT_ID }], "GRAPH_QUERY_REQUEST_INVALID"],
  ["a prototype-polluting key", () => POLLUTED, "GRAPH_QUERY_REQUEST_INVALID"],
  ["an accessor-bearing projectId", () => Object.defineProperty({}, "projectId", {
    configurable: true, enumerable: true, get: () => PROJECT_ID,
  }), "GRAPH_QUERY_REQUEST_INVALID"],
  ["an unlisted extra field", () => ({ graphEpoch: 1, projectId: PROJECT_ID }),
    "GRAPH_QUERY_REQUEST_INVALID"],
  ["a non-NFC project string", () => ({ projectId: PROJECT_ID + "e\u0301" }),
    "GRAPH_QUERY_REQUEST_INVALID"],
  ["an oversized project string", () => ({ projectId: "p".repeat(100_000) }),
    "GRAPH_QUERY_REQUEST_INVALID"],
  ["a non-string projectId", () => ({ projectId: 7 }), "GRAPH_QUERY_REQUEST_INVALID"],
  ["an empty projectId", () => ({ projectId: "" }), "GRAPH_QUERY_REQUEST_INVALID"],
];

describe("graph.get hostile body sweep", () => {
  it("generates a nonzero number of distinct hostile cases", () => {
    // A sweep that silently produced zero cases would pass every arm below
    // while testing nothing.
    expect(HOSTILE_BODIES.length).toBeGreaterThan(0);
    expect(HOSTILE_BODIES).toHaveLength(10);
    expect(new Set(HOSTILE_BODIES.map(([name]) => name)).size).toBe(10);
  });

  for (const [name, build, expectedCode] of HOSTILE_BODIES) {
    it(`refuses ${name} rather than throwing, without reading`, () => {
      withStore("hostile", (store) => {
        seedActive(store);
        const port = countingPort(store);
        // A CRASH IS NOT A REFUSAL: the call itself must not throw.
        let answer: GraphQueryResult | undefined;
        expect(() => { answer = ask(store, { body: build(), port }); }).not.toThrow();
        const refusal = refusalOf(answer as GraphQueryResult);
        expect(refusal.layer).toBe("GRAPH_QUERY");
        expect(refusal.code).toBe(expectedCode);
        expect(port.reads()).toBe(0);
      });
    });
  }
});

// --- 4. the same guard sequence, reached through BOTH transports -------------

interface HttpReply {
  readonly body: Record<string, unknown>;
  readonly status: number;
}

async function withListener(
  store: SqliteEventStore,
  port: GraphQueryPort | undefined,
  principal: AuthenticatedPrincipal | null,
  run: (listener: ControlRoomListener) => Promise<void>,
): Promise<void> {
  const started = await startControlRoomListener({
    csrfToken: CSRF,
    deps: depsFor(store, principal),
    ...(port === undefined ? {} : { graph: port }),
  });
  if (!started.ok) throw new Error(`listener refused to start: ${started.code}`);
  try {
    await run(started);
  } finally {
    // Closed on EVERY exit path, including a throwing body: a leaked handle
    // surfaces later as EBUSY on Windows rather than as the real failure.
    await started.close();
  }
}

async function overHttp(
  listener: ControlRoomListener,
  init: { readonly body?: string; readonly credential?: string | null } = {},
): Promise<HttpReply> {
  const payload = init.body ?? JSON.stringify({});
  const headers: Record<string, string> = {
    "content-length": String(Buffer.byteLength(payload)),
    "content-type": "application/json",
    host: `127.0.0.1:${listener.port}`,
    origin: listener.origin,
    "x-moe-csrf": CSRF,
    "x-moe-protocol-version": WIRE_PROTOCOL_VERSION,
  };
  if (init.credential !== null) {
    headers["x-moe-session-credential"] = init.credential ?? GOOD_CREDENTIAL;
  }
  return await new Promise<HttpReply>((resolve, reject) => {
    const outgoing = httpRequest(
      {
        headers, host: "127.0.0.1", method: "POST", path: "/graph/get",
        port: listener.port, setHost: false,
      },
      (response) => {
        const chunks: Buffer[] = [];
        response.on("data", (chunk: Buffer) => chunks.push(chunk));
        response.on("end", () => resolve({
          body: JSON.parse(Buffer.concat(chunks).toString("utf8")) as Record<string, unknown>,
          status: response.statusCode ?? 0,
        }));
      },
    );
    outgoing.on("error", reject);
    outgoing.end(payload);
  });
}

describe("graph.get over the MCP dispatch port", () => {
  it("answers an authenticated query with both identities, unequated", () => {
    withStore("mcp-accept", (store) => {
      seedActive(store);
      const reader = readCurrentActiveGraph(store, PROJECT_ID);
      if (!reader.ok) throw new Error(`fixture did not reach ACTIVE: ${reader.code}`);
      const answer = overMcp(store, countingPort(store));
      expect(answer["ok"]).toBe(true);
      expect(answer["graphContentHash"]).toBe(reader.graphContentHash);
      expect(answer["snapshotIdentity"]).toBe(reader.snapshotIdentity);
      expect(answer["graphContentHash"]).not.toBe(answer["snapshotIdentity"]);
    });
  });

  it("refuses an unauthenticated query at AUTHENTICATE, without reading", () => {
    withStore("mcp-unauth", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const answer = overMcp(store, port, { credential: null });
      expect(answer["ok"]).toBe(false);
      expect(answer["stage"]).toBe("AUTHENTICATE");
      expect(answer["outcome"]).toBe("REFUSED");
      // The exact reason, carried across the JSON boundary. A stage-only
      // assertion here would survive the transport dropping `error` entirely.
      expect((answer["error"] as Record<string, unknown> | undefined)?.["code"])
        .toBe("AUTHENTICATION_FAILED");
      expect(port.reads()).toBe(0);
    });
  });

  it("refuses a spoofed project over MCP, without reading", () => {
    withStore("mcp-spoof", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const answer = overMcp(store, port, { payload: { projectId: "proj-somebody-else" } });
      expect(answer["ok"]).toBe(false);
      expect(answer["code"]).toBe("GRAPH_QUERY_PROJECT_MISMATCH");
      expect(answer["layer"]).toBe("GRAPH_QUERY");
      expect(port.reads()).toBe(0);
    });
  });

  it("refuses a capability-less principal over MCP, without reading", () => {
    withStore("mcp-capability", (store) => {
      seedActive(store);
      const port = countingPort(store);
      const answer = overMcp(store, port, {}, principalFor(PROJECT_ID, []));
      expect(answer["ok"]).toBe(false);
      expect(answer["code"]).toBe("GRAPH_QUERY_CAPABILITY_DENIED");
      // The refusing layer travels too: the reader can also refuse a read, and
      // only the layer says whether authority was denied before it ran.
      expect(answer["layer"]).toBe("GRAPH_QUERY");
      expect(port.reads()).toBe(0);
    });
  });

  it("refuses graph.get when no graph port is composed", () => {
    withStore("mcp-unavailable", (store) => {
      seedActive(store);
      const answer = overMcp(store, undefined);
      expect(answer["ok"]).toBe(false);
      // THE DISPATCH PORT refused, not the handler. The MCP seam answers an
      // uncomposed port with its own pre-existing `queryRefusal()` shape rather
      // than minting a second one, so the frame carries a runtime error and
      // never the handler's `GRAPH_QUERY_UNAVAILABLE` — asserting only "not ok"
      // could not tell which of the two layers answered.
      expect((answer["error"] as Record<string, unknown> | undefined)?.["code"])
        .toBe("INPUT_INVALID");
      expect(answer["code"]).toBeUndefined();
      expect(answer["layer"]).toBeUndefined();
    });
  });
});

describe("graph.get over the HTTP listener", () => {
  it("answers 200 with both identities for an authenticated request", async () => {
    const directory = mkdtempSync(join(tmpdir(), "moe-graph-query-http-"));
    try {
      const store = SqliteEventStore.openForProject(join(directory, "store.sqlite"), PROJECT_ID);
      try {
        installBinding(store);
        seedActive(store);
        const reader = readCurrentActiveGraph(store, PROJECT_ID);
        if (!reader.ok) throw new Error(`fixture did not reach ACTIVE: ${reader.code}`);
        const port = countingPort(store);
        await withListener(store, port, principalFor(PROJECT_ID), async (listener) => {
          const reply = await overHttp(listener);
          expect(reply.status, JSON.stringify(reply.body)).toBe(200);
          expect(reply.body["ok"]).toBe(true);
          expect(reply.body["graphContentHash"]).toBe(reader.graphContentHash);
          expect(reply.body["snapshotIdentity"]).toBe(reader.snapshotIdentity);
          expect(reply.body["graphContentHash"]).not.toBe(reply.body["snapshotIdentity"]);

          // AN AUTHENTICATION refusal keeps its own status; a frame refusal does
          // not mint one. Both rules asserted on the same live listener.
          const unauthenticated = await overHttp(listener, { credential: null });
          expect(unauthenticated.status).toBe(401);
          expect(unauthenticated.body["stage"]).toBe("AUTHENTICATE");
          expect((unauthenticated.body["error"] as Record<string, unknown> | undefined)?.["code"])
            .toBe("AUTHENTICATION_FAILED");

          const spoofed = await overHttp(listener, {
            body: JSON.stringify({ projectId: "proj-somebody-else" }),
          });
          expect(spoofed.status).toBe(200);
          expect(spoofed.body["code"]).toBe("GRAPH_QUERY_PROJECT_MISMATCH");
          expect(spoofed.body["layer"]).toBe("GRAPH_QUERY");

          const undecodable = await overHttp(listener, { body: "{not json" });
          expect(undecodable.status).toBe(400);
          expect(undecodable.body["code"]).toBe("LISTENER_GRAPH_REQUEST_INVALID");
          // THE LISTENER refused, not the handler: undecodable bytes are this
          // transport's own decode fault, and naming the layer is what keeps it
          // distinct from `GRAPH_QUERY_REQUEST_INVALID`, which the handler
          // returns for a body it could decode but may not admit.
          expect(undecodable.body["layer"]).toBe("CONTROL_ROOM_LISTENER");
          expect(undecodable.body["code"]).not.toBe("GRAPH_QUERY_REQUEST_INVALID");

          // Only the accepted request reached the reader.
          expect(port.reads()).toBe(1);
        });
      } finally {
        store.close();
      }
    } finally {
      rmSync(directory, { force: true, maxRetries: 5, recursive: true });
    }
  });
});

// --- 5. the reader's refusals arrive whole -----------------------------------

interface ReaderRefused {
  readonly code?: unknown;
  readonly layer?: unknown;
  readonly sourceCode?: unknown;
  readonly sourceLayer?: unknown;
}

/**
 * Asserts the QUADRUPLE, not just the outer code. `code` alone cannot tell a
 * missing body from a corrupt one; that distinction lives entirely in
 * `sourceCode`/`sourceLayer`, which is why this module passes the struct through
 * rather than flattening it.
 */
function readerRefusalOf(answer: GraphQueryResult): ReaderRefused {
  const refusal = refusalOf(answer) as ReaderRefused;
  expect(refusal.layer).toBe("ACTIVE_GRAPH_PROJECTION");
  // NOT this module's layer: a restamped refusal would read as though the query
  // handler had made the durable judgement.
  expect(refusal.layer).not.toBe("GRAPH_QUERY");
  return refusal;
}

describe("graph.get passes the reader's refusals through whole", () => {
  it("keeps ACTIVE_GRAPH_ABSENT with a null sourceLayer when nothing is active", () => {
    withStore("reader-absent", (store) => {
      // A real history that simply never reached ACTIVE.
      const driven = drive([createOf("graph-revision-1", PRIMARY.graphContentHash)]);
      commitEvents(store, "graph-revision-1", driven.events);
      const refusal = readerRefusalOf(ask(store));
      expect(refusal.code).toBe("ACTIVE_GRAPH_ABSENT");
      expect(refusal.sourceLayer).toBeNull();
      expect(refusal.sourceCode).toBeNull();
    });
  });

  it("keeps ACTIVE_GRAPH_SPLIT_BRAIN rather than picking a winner", () => {
    withStore("reader-split", (store) => {
      seedActive(store, "graph-revision-1", PRIMARY);
      seedActive(store, "graph-revision-9", SECONDARY);
      const refusal = readerRefusalOf(ask(store));
      expect(refusal.code).toBe("ACTIVE_GRAPH_SPLIT_BRAIN");
      // Distinct from absence: collapsing the two would hide a real split behind
      // "there is no graph", and a caller would go on to create one.
      expect(refusal.code).not.toBe("ACTIVE_GRAPH_ABSENT");
    });
  });

  it("keeps BODY_UNAVAILABLE together with the body record's OWN source code", () => {
    withStore("reader-no-body", (store) => {
      seedActiveWithoutBody(store);
      const refusal = readerRefusalOf(ask(store));
      expect(refusal.code).toBe("ACTIVE_GRAPH_BODY_UNAVAILABLE");
      // The pair that distinguishes a MISSING body from a corrupt one. Asserting
      // only the outer code would stay green if both source fields were dropped.
      expect(refusal.sourceLayer).toBe("GRAPH_BODY_RECORD");
      expect(refusal.sourceCode).toBe("GRAPH_BODY_ABSENT");
    });
  });

  it("keeps the CORE REPLAY's own code, naming core as the layer that refused", () => {
    withStore("reader-conflict", (store) => {
      const driven = drive([
        createOf("graph-revision-1", PRIMARY.graphContentHash), submit,
        approveAndActivateOf(PRIMARY.graphContentHash),
      ]);
      commitEvents(store, "graph-revision-1", driven.events);
      // One deliberate drift from a GENERATED history: the same version
      // redelivered with different bytes. The core replay owns that rule.
      const first = driven.events[0];
      if (first === undefined) throw new Error("generated history was empty");
      const drifted = { ...first, goalRef: "goal-DRIFTED" } as unknown as GraphRevisionEvent;
      const aggregateId = graphRevisionAggregateId(PROJECT_ID, "graph-revision-1");
      store.commit({
        aggregateId,
        commandBytes: ENCODER.encode("drift"),
        commandId: "drift-graph-revision-1",
        committedAt: "2026-08-18T00:00:00.000Z",
        events: [{
          eventId: "drift-graph-revision-1-0",
          eventType: drifted.kind,
          payload: ENCODER.encode(JSON.stringify(drifted)),
        }],
        expectedVersion: store.getAggregateVersion(aggregateId),
      });

      const refusal = readerRefusalOf(ask(store));
      // The replay's OWN spelling, verbatim. The reader deliberately does not
      // merge core codes into its three, so a caller tells them apart by prefix;
      // a test asserting only "refused" would stay green if they merged.
      expect(refusal.code).toBe("GRAPH_REVISION_REPLAY_IDENTITY_CONFLICT");
      expect(refusal.sourceLayer).toBe("CORE_GRAPH_REVISION_REPLAY");
      expect(String(refusal.code).startsWith("GRAPH_REVISION_REPLAY_")).toBe(true);
    });
  });

  it("refuses rather than throwing when the store cannot be read at all", () => {
    withStore("reader-auth", (authStore) => {
      const directory = mkdtempSync(join(tmpdir(), "moe-graph-query-reader-throws-"));
      const graphStore = SqliteEventStore.openForProject(
        join(directory, "store.sqlite"), PROJECT_ID,
      );
      let closed = false;
      try {
        seedActive(graphStore);
        // Keep authentication real and readable while closing only the graph
        // port's store. Otherwise authentication correctly refuses first and
        // this test never reaches the reader failure it claims to exercise.
        graphStore.close();
        closed = true;
        let answer: GraphQueryResult | undefined;
        expect(() => {
          answer = ask(authStore, { port: countingPort(graphStore) });
        }).not.toThrow();
        const refusal = refusalOf(answer as GraphQueryResult);
        expect(refusal.code).toBe("GRAPH_QUERY_READ_FAILED");
        expect(refusal.layer).toBe("GRAPH_QUERY");
      } finally {
        if (!closed) graphStore.close();
        rmSync(directory, { force: true, maxRetries: 5, recursive: true });
      }
    });
  });

  it("carries every reader refusal through the MCP transport unflattened", () => {
    withStore("reader-mcp", (store) => {
      seedActiveWithoutBody(store);
      const answer = overMcp(store, countingPort(store));
      expect(answer["ok"]).toBe(false);
      expect(answer["code"]).toBe("ACTIVE_GRAPH_BODY_UNAVAILABLE");
      expect(answer["layer"]).toBe("ACTIVE_GRAPH_PROJECTION");
      // The JSON boundary is exactly where a four-field struct quietly becomes
      // a two-field one.
      expect(answer["sourceLayer"]).toBe("GRAPH_BODY_RECORD");
      expect(answer["sourceCode"]).toBe("GRAPH_BODY_ABSENT");
    });
  });
});

// --- 6. the production event-to-MCP control ----------------------------------

describe("graph.get end to end, durable events to MCP bytes", () => {
  it("answers the reader's own snapshot across the JSON boundary", () => {
    withStore("e2e", (store) => {
      // Seeded through the REAL reducer and the REAL body writer, then read back
      // through the REAL dispatch port. Nothing on this path is stubbed.
      seedActive(store);
      const reader = readCurrentActiveGraph(store, PROJECT_ID);
      if (!reader.ok) throw new Error(`fixture did not reach ACTIVE: ${reader.code}`);

      const events = eventCount(store);
      const decisions = decisionCount(store);
      const first = overMcpBytes(store, countingPort(store));
      const answer = JSON.parse(DECODER.decode(first)) as Record<string, unknown>;

      expect(answer["ok"]).toBe(true);
      // The SNAPSHOT ITSELF, not a shape check. A deeply frozen object can still
      // lose or reorder structure across `bytesOf`, and only comparing it to the
      // reader's own output proves the transport is faithful rather than merely
      // responsive.
      expect(answer["snapshot"]).toEqual(reader.snapshot);
      expect(answer["revisionId"]).toBe(reader.revisionId);
      expect(answer["graphEpoch"]).toBe(reader.graphEpoch);
      expect(answer["planHash"]).toBe(reader.planHash);
      expect(answer["provenance"]).toEqual(reader.provenance);

      // BOTH IDENTITIES SURVIVE AS DISTINCT FIELDS WITH DISTINCT VALUES. A JSON
      // boundary is exactly where two same-shaped hex strings can be collapsed
      // by a careless projection, and this is the last place to catch it.
      expect(answer["graphContentHash"]).toBe(reader.graphContentHash);
      expect(answer["snapshotIdentity"]).toBe(reader.snapshotIdentity);
      expect(answer["graphContentHash"]).not.toBe(answer["snapshotIdentity"]);
      expect(Object.hasOwn(answer, "graphContentHash")).toBe(true);
      expect(Object.hasOwn(answer, "snapshotIdentity")).toBe(true);

      // BYTE-IDENTICAL ON REPEAT, compared as bytes rather than as decoded
      // objects: key order is part of what the transport must not vary.
      const second = overMcpBytes(store, countingPort(store));
      expect([...second]).toEqual([...first]);

      // A QUERY WRITES NOTHING, across both calls, counted out of the store.
      expect(eventCount(store)).toBe(events);
      expect(decisionCount(store)).toBe(decisions);
    });
  });

  it("returns the frozen reader snapshot without letting a caller mutate it", () => {
    withStore("frozen", (store) => {
      seedActive(store);
      let captured: ActiveGraphResult | undefined;
      const answer = ask(store, {
        port: {
          boundProjectId: PROJECT_ID,
          readCurrentActiveGraph: (projectId: string): ActiveGraphResult => {
            captured = readCurrentActiveGraph(store, projectId);
            return captured;
          },
        },
      });
      if (!answer.ok) throw new Error("the accepted control refused");
      expect(Object.isFrozen(answer)).toBe(true);
      expect(answer.snapshot).toEqual(captured?.ok === true ? captured.snapshot : null);
      // REFERENCE identity against the result the port ACTUALLY returned, not
      // against a second read: each read decodes fresh, so comparing two calls
      // would compare two different objects and could never pass. This is the
      // assertion that the handler hands the reader's own object on rather than
      // rebuilding it — a rebuilt copy is where a field quietly goes missing.
      expect(answer.snapshot).toBe(captured?.ok === true ? captured.snapshot : null);
    });
  });
});
