/**
 * Inputs only, for the `graph.get` suites.
 *
 * Nothing here re-implements a boundary rule. Every history is GENERATED by
 * driving the real `reduceGraphRevision` and committing the events it actually
 * emitted, exactly as `active-graph-projection.test.ts` does and for the same
 * reason: nothing writes graph-revision events in production yet, so a
 * hand-authored event shape would let the query handler pass against events
 * production will never produce. The command INPUT is restated here — `@moe/core`'s
 * revision fixtures are test-only and unreachable from its root — but every event,
 * every state and every lifecycle rule still comes from the production reducer.
 *
 * No `expect` and no assertion lives in this module: the test files run their
 * assertions against production functions, and a fixture that judged an outcome
 * would be a second authority beside the one under test.
 *
 * WINDOWS HANDLE DISCIPLINE: `withStore` closes the store in a `finally` inside
 * the temp directory's own `finally`. A handle held across `rmSync` throws EPERM
 * and kills the vitest worker with no output at all.
 */

import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { reduceGraphRevision } from "@moe/core";
import type {
  GraphRevisionCommand,
  GraphRevisionEvent,
  GraphRevisionState,
} from "@moe/core";
import { encodeGraphContent } from "@moe/scheduler";
import type {
  GraphContent,
  GraphEdge,
  GraphNode,
  GraphRevisionContent,
  GraphSnapshot,
} from "@moe/scheduler";
import { RECOVERY_BINDING_CODEC_VERSION, SqliteEventStore } from "@moe/store";

import { WIRE_PROTOCOL_VERSION } from "../http/http-contract.js";
import type {
  AuthenticatedPrincipal,
  Authenticator,
  CommandAdapterDeps,
} from "../http/http-contract.js";
import { decisionPort, recordingHandler, registryOf } from "../http/http-test-fixtures.js";
import { streamPort } from "../http/event-stream-fixtures.js";
import { createSessionAuthenticator } from "../identity/session-authenticator.js";
import { createMcpDispatchPort } from "../mcp-dispatch-port.js";
import type { HttpDispatchPort } from "@moe/mcp";
import {
  graphRevisionAggregateId,
  readCurrentActiveGraph,
} from "./active-graph-projection.js";
import type { ActiveGraphResult } from "./active-graph-projection.js";
import { putGraphBody } from "./graph-body-record.js";
import { answerGraphQuery } from "./graph-query.js";
import type { GraphQueryPort, GraphQueryResult } from "./graph-query.js";

export const PROJECT_ID = "proj-graph-query-0001";
export const PRINCIPAL_ID = "principal-planner-1";
export const PLANNING_CAPABILITY = "planning.write";
export const GOOD_CREDENTIAL = "credential-good";
export const CSRF = "csrf-token-for-graph-query";
export const ENCODER = new TextEncoder();
export const DECODER = new TextDecoder();

// --- content fixtures --------------------------------------------------------

export function baseSnapshot(): GraphSnapshot {
  const nodes: readonly GraphNode[] = [
    { nodeKey: "dev-a", executionBearing: true },
    { nodeKey: "dev-b", executionBearing: true },
    { nodeKey: "dev-c", executionBearing: true },
  ];
  const edges: readonly GraphEdge[] = [
    { edgeKey: "dev-e1", producerNodeKey: "dev-a", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e2", producerNodeKey: "dev-b", consumerNodeKey: "dev-c", kind: "HARD" },
    { edgeKey: "dev-e3", producerNodeKey: "dev-a", consumerNodeKey: "dev-b", kind: "ADVISORY" },
  ];
  return { nodes, edges, completionNodeKey: "dev-c" };
}

export function encoded(author: string): GraphContent {
  const content = {
    author,
    completionNode: "dev-c",
    decompositionBudget: 24,
    parentRevision: "rev-000000000000",
    policyRevision: "pol-000000000001",
    repositoryBaseTree: "4".repeat(40),
    snapshot: baseSnapshot(),
  } as unknown as GraphRevisionContent;
  const result = encodeGraphContent(content);
  if (!result.ok) throw new Error(`fixture failed to encode: ${JSON.stringify(result.issues)}`);
  return result.value;
}

export const PRIMARY = encoded("human:architect-primary");
export const SECONDARY = encoded("human:architect-successor");

// --- reducer command fixtures (input only; the reducer owns every rule) -------

export function seededHash(seed: string): string {
  return seed.repeat(64).slice(0, 64);
}

export const PLAN_HASH = seededHash("11");

export function bindingOf(graphHash: string) {
  return {
    budgetHash: seededHash("55"),
    expectedGoalVersion: 3,
    graphHash,
    policyHash: seededHash("66"),
    qualityHash: seededHash("33"),
  } as const;
}

export type Step = (current: GraphRevisionState | undefined) => GraphRevisionCommand;

export function versionOf(current: GraphRevisionState | undefined): number {
  return current === undefined ? 0 : current.version;
}

export function createOf(revisionId: string, graphContentHash: string): Step {
  return () => ({
    commandId: `cmd-create-${revisionId}`, expectedVersion: 0, goalRef: "goal-1",
    graphContentHash, kind: "graph_revision.create", planHash: PLAN_HASH, revisionId,
  }) as GraphRevisionCommand;
}

export const submit: Step = (current) => ({
  commandId: "cmd-submit", expectedVersion: versionOf(current),
  kind: "graph_revision.submit",
  witness: { submissionRef: "submission-1", truthClass: "DAEMON_VERIFIED" },
}) as GraphRevisionCommand;

export function approveAndActivateOf(graphHash: string): Step {
  const binding = bindingOf(graphHash);
  return (current) => ({
    activation: {
      ...binding, activationRef: "activation-1", graphEpoch: 1, truthClass: "HUMAN_APPROVED",
    },
    approval: { ...binding, approvalRef: "approval-1", truthClass: "HUMAN_APPROVED" },
    commandId: "cmd-approve", expectedVersion: versionOf(current), kind: "graph.approve",
  }) as unknown as GraphRevisionCommand;
}

// --- store harness -----------------------------------------------------------

export function installBinding(
  store: SqliteEventStore,
  incarnationRef = "81".repeat(32),
  keyEpochRef = "82".repeat(32),
): void {
  const installed = store.installRecoveryBinding({
    bindingCodecVersion: RECOVERY_BINDING_CODEC_VERSION,
    incarnationRef,
    installedAt: "2026-08-18T00:00:00.000Z",
    keyEpochRef,
    payload: ENCODER.encode("graph-query-recovery-binding"),
    slot: "ACTIVE",
  });
  if (!installed.ok) throw new Error(`recovery binding setup failed: ${installed.code}`);
}

export function withStore<T>(name: string, run: (store: SqliteEventStore) => T): T {
  const directory = mkdtempSync(join(tmpdir(), `moe-graph-query-${name}-`));
  try {
    const store = SqliteEventStore.openForProject(join(directory, "store.sqlite"), PROJECT_ID);
    try {
      installBinding(store);
      return run(store);
    } finally {
      store.close();
    }
  } finally {
    rmSync(directory, { force: true, maxRetries: 5, recursive: true });
  }
}

/** Drives the REAL reducer and returns the events it actually emitted. */
export function drive(
  steps: readonly Step[],
): { events: GraphRevisionEvent[]; state: GraphRevisionState } {
  let current: GraphRevisionState | undefined;
  const events: GraphRevisionEvent[] = [];
  for (const step of steps) {
    const result = reduceGraphRevision(current, step(current));
    if (!result.ok) throw new Error(`fixture command rejected: ${result.error.code}`);
    current = result.state;
    events.push(...result.events);
  }
  if (current === undefined) throw new Error("path produced no state");
  return { events, state: current };
}

/** The whole ACTIVE path, driven through the reducer, for one revision id. */
export function activePathFor(
  revisionId: string,
  content: GraphContent,
): readonly GraphRevisionEvent[] {
  return drive([
    createOf(revisionId, content.graphContentHash), submit,
    approveAndActivateOf(content.graphContentHash),
  ]).events;
}

export function commitEvents(
  store: SqliteEventStore,
  revisionId: string,
  events: readonly GraphRevisionEvent[],
  commandId = `seed-${revisionId}`,
): void {
  const aggregateId = graphRevisionAggregateId(PROJECT_ID, revisionId);
  store.commit({
    aggregateId,
    commandBytes: ENCODER.encode(commandId),
    commandId,
    committedAt: "2026-08-18T00:00:00.000Z",
    events: events.map((event, index) => ({
      eventId: `${commandId}-${index}`,
      eventType: event.kind,
      payload: ENCODER.encode(JSON.stringify(event)),
    })),
    expectedVersion: store.getAggregateVersion(aggregateId),
  });
}

/** Seed a revision AND the body its content hash names — the normal, whole path. */
export function seedActive(
  store: SqliteEventStore,
  revisionId = "graph-revision-1",
  content: GraphContent = PRIMARY,
): void {
  commitEvents(store, revisionId, activePathFor(revisionId, content));
  putGraphBody(store, PROJECT_ID, content);
}

/** The revision events WITHOUT the body their content hash names. */
export function seedActiveWithoutBody(
  store: SqliteEventStore,
  revisionId = "graph-revision-1",
): void {
  commitEvents(store, revisionId, activePathFor(revisionId, PRIMARY));
}

export function eventCount(store: SqliteEventStore): number {
  return store.readEventsAfter(0n, 1_000).items.length;
}

export function decisionCount(store: SqliteEventStore): number {
  return store.readCommandDecisionsAfter(0n, 1_000).items.length;
}

// --- authentication harness --------------------------------------------------

export function principalFor(
  projectId: string,
  capabilities: readonly string[] = [PLANNING_CAPABILITY],
): AuthenticatedPrincipal {
  return { capabilities, principalId: PRINCIPAL_ID, projectId };
}

/** The real durable-ledger authenticator; only its operator configuration varies. */
export function authenticatorFor(
  store: SqliteEventStore,
  principal: AuthenticatedPrincipal | null,
): Authenticator {
  const configured = principal ?? principalFor(PROJECT_ID);
  return createSessionAuthenticator(store, {
    clock: () => Date.parse("2026-08-18T00:00:00.000Z"),
    operatorCapabilities: configured.capabilities,
    operatorCredential: principal === null ? "credential-disabled" : GOOD_CREDENTIAL,
    operatorPrincipalId: configured.principalId,
    projectId: configured.projectId,
  });
}

export interface CountingPort extends GraphQueryPort {
  readonly reads: () => number;
}

/**
 * Counts reader invocations so "refused BEFORE the reader ran" is MEASURED. A
 * handler that read first and refused afterwards would leak the existence and
 * shape of another project's graph while still returning a refusal, and no
 * assertion on the returned value can see the difference.
 */
export function countingPort(store: SqliteEventStore, boundProjectId = PROJECT_ID): CountingPort {
  let reads = 0;
  return {
    boundProjectId,
    readCurrentActiveGraph: (projectId: string): ActiveGraphResult => {
      reads += 1;
      return readCurrentActiveGraph(store, projectId);
    },
    reads: () => reads,
  };
}

export interface QueryOptions {
  readonly body?: unknown;
  readonly capabilities?: readonly string[];
  readonly credential?: string | null;
  readonly port?: GraphQueryPort;
  readonly principalProject?: string;
  readonly protocolVersion?: unknown;
}

export function ask(store: SqliteEventStore, options: QueryOptions = {}): GraphQueryResult {
  const principal = principalFor(
    options.principalProject ?? PROJECT_ID,
    options.capabilities ?? [PLANNING_CAPABILITY],
  );
  return answerGraphQuery({
    authenticator: authenticatorFor(store, principal),
    body: options.body ?? {},
    credential: options.credential === undefined ? GOOD_CREDENTIAL : options.credential,
    port: options.port ?? countingPort(store),
    protocolVersion: options.protocolVersion ?? WIRE_PROTOCOL_VERSION,
  });
}

// --- MCP transport harness ---------------------------------------------------

export function depsFor(
  store: SqliteEventStore,
  principal: AuthenticatedPrincipal | null,
): CommandAdapterDeps {
  return {
    authenticator: authenticatorFor(store, principal),
    decisions: decisionPort(),
    registry: registryOf("goal.create", recordingHandler().handler, ["title"]),
  };
}

export interface McpOptions {
  readonly credential?: string | null;
  readonly payload?: unknown;
}

/** Drives the REAL MCP dispatch port and returns the RAW answered bytes. */
export function overMcpBytes(
  store: SqliteEventStore,
  port: GraphQueryPort | undefined,
  options: McpOptions = {},
  principal: AuthenticatedPrincipal | null = principalFor(PROJECT_ID),
): Uint8Array {
  const dispatch = createMcpDispatchPort({
    deps: depsFor(store, principal),
    ...(port === undefined ? {} : { graph: port }),
    subscriptions: streamPort(),
  });
  const envelope = ENCODER.encode(JSON.stringify({
    payload: options.payload ?? {}, queryKind: "graph.get",
  }));
  const credential = options.credential === undefined ? GOOD_CREDENTIAL : options.credential;
  // HELD AS THE HTTP BRIDGE HOLDS IT. `createMcpDispatchPort` is declared to
  // return `StdioDispatchPort`, whose `dispatchQueryBytes(bytes)` takes no
  // context — the stdio server calls it that way and falls back to the process
  // credential. The HTTP MCP bridge holds the same value as an
  // `HttpDispatchPort` and passes a context (http-tool-bridge.ts:156), which is
  // the production path a per-request bearer travels. Driving it through the
  // one-argument type would have tested the fallback and never the context.
  const bridge = dispatch as unknown as HttpDispatchPort;
  const answered = credential === null
    ? (bridge.dispatchQueryBytes as (bytes: Uint8Array) => Uint8Array)(envelope)
    : bridge.dispatchQueryBytes(envelope, { credential });
  if (answered instanceof Promise) throw new Error("the query dispatch answered asynchronously");
  return answered;
}

export function overMcp(
  store: SqliteEventStore,
  port: GraphQueryPort | undefined,
  options: McpOptions = {},
  principal: AuthenticatedPrincipal | null = principalFor(PROJECT_ID),
): Record<string, unknown> {
  return JSON.parse(DECODER.decode(overMcpBytes(store, port, options, principal))) as
    Record<string, unknown>;
}
